Unify the way of parsing enums sent over Ably channels
ably/ably-asset-tracking-android pull request #208
Opened 2021-03-11 14:32 UTC by KacperKluka

I've created message models for all domain classes that are being sent through Ably channels. After that I was able to specify the format of enums to be in the `SCREAMING_CAMEL_CASE`

2021-03-15 19:46 UTC, QuintinWillison requested changes

2021-03-15 19:46 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/MessageModels.kt
> +    MAXIMUM
Missing comma and end of line.

2021-03-15 19:46 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/MessageModels.kt
> +    ACTUAL
Missing comma and end of line.

2021-03-15 19:46 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/MessageModels.kt
> +    @SerializedName("MINIMUM")
Surprising that these can't be generated from the enum values somehow.

2021-03-16 09:08 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/MessageModels.kt
> +    @SerializedName("MINIMUM")
They can be generated but as it's pointed out in [this article](https://medium.com/key-lessons-from-books/ditching-gsons-field-naming-strategy-4dd217b51f82) we should be careful with using automated field naming policies. 
Firstly, there's no default naming policy that supports SCREAMING SNAKE CASE, so we would need to implement this by ourselves. 
Secondly, we will need to be extra careful where we're using that naming policy because it will change the names of all fields it will parse, so we will need to introduce some hacks so it will only change enums names. 
Overall it seems that it's far simpler and safer to just use that `@SerializedName` annotation which also makes thing very explicit :wink:

2021-03-16 09:09 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/MessageModels.kt
> +    MAXIMUM
https://github.com/ably/ably-asset-tracking-android/pull/208/commits/9242554c5bdbc6ba7c6e0c23a60809f470debb5a

2021-03-16 09:09 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/MessageModels.kt
> +    ACTUAL
https://github.com/ably/ably-asset-tracking-android/pull/208/commits/9242554c5bdbc6ba7c6e0c23a60809f470debb5a

2021-03-17 07:56 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/MessageModels.kt
> +    @SerializedName("MINIMUM")
Fair point and thanks for explaining your reasoning. I guess there will always be a tension between "being explicit" and our general desire and tidy programmers to keep things [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). As usual, neither is a panacea. 😁 Let's leave it as is.

2021-03-17 08:00 UTC, QuintinWillison approved these changes

2021-03-17 08:00 UTC, merged