Add token based authentication
ably/ably-asset-tracking-android pull request #222
Opened 2021-03-16 15:23 UTC by KacperKluka

I've added the possibility to authenticate in Ably with a token. The old way of authentication with secret key is still available.
In order to adjust the code for Java users I've used the same approach that I took with `LocationSource` classes.

The PR is in the "Draft" state because we've not yet decided if we'd like to allow the users to use TokenRequest and TokenDetails besides the token string.

2021-04-06 15:18 UTC, kavalerov commented
@paddybyers do you mind having a look at this?

2021-04-07 11:18 UTC, paddybyers reviewed
Overall this looks right, but:
- I think there need to be tests and examples that actually generate valid token requests;
- I've not reviewed the naming of everything. I'm not sure calling things `ToAbly()` is right, because the asset tracking SDK is still an Ably SDK, it's just not an Ably realtime messaging SDK.

2021-04-07 11:18 UTC, paddybyers commented on publishing-example-java-app/src/test/java/com/ably/tracking/example/javapublisher/PublisherInterfaceUsageExamples.java
> +        ConnectionConfiguration configuration = ConnectionConfigurationToken.create((params) -> new TokenRequest(0, "", "", 0, "", "", ""), "CLIENT_ID");
I don't think this is a very useful example, and the code won't work because it's not a valid `TokenRequest`. If we're including an example, shouldn't the token callback generate a valid token?

2021-04-12 07:27 UTC, KacperKluka commented on publishing-example-java-app/src/test/java/com/ably/tracking/example/javapublisher/PublisherInterfaceUsageExamples.java
> +        ConnectionConfiguration configuration = ConnectionConfigurationToken.create((params) -> new TokenRequest(0, "", "", 0, "", "", ""), "CLIENT_ID");
I agree but in reality that `TokenRequest` will be generated by the user's backend server :thinking: How should we showcase it here? Will it be enough to create a method called `getTokenRequestFromServer()` or something like that and make that method will return this "dummy" token request object?

2021-04-12 17:23 UTC, QuintinWillison requested changes

2021-04-12 17:23 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/AblyHelpers.kt
> +fun TokenRequest.toAbly(): Auth.TokenRequest =
In response to [this comment](https://github.com/ably/ably-asset-tracking-android/pull/222#pullrequestreview-629883418), I would suggest renaming `toAbly` to `toAuth`.

2021-04-12 17:23 UTC, QuintinWillison commented on publishing-example-java-app/src/test/java/com/ably/tracking/example/javapublisher/PublisherInterfaceUsageExamples.java
> +        ConnectionConfiguration configuration = ConnectionConfigurationToken.create((params) -> new TokenRequest(0, "", "", 0, "", "", ""), "CLIENT_ID");
Perhaps what is not clear here is that this code is only really in place to demonstrate that these APIs are callable from a Java-based codebase... all we were aiming to see from tests in this suite is that they pass the compiler.

The test Paddy speaks of would be elsewhere, and probably pure Kotlin in the first instance.

2021-04-12 17:23 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +    /**
There should be a blank line above these comments. It's all too bunched up for both this class and the one below.

2021-04-12 17:23 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> + * Represents a set of parameters that are used when requesting an auth token.
I think this comment could be much clearer.

I'm reading it and finding myself immediately asking, for example, _who_ is requesting an auth token? i.e. who defines these params and who modifies their behaviour based upon them.

2021-04-12 17:23 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +class TokenRequest(
This class needs a comment. Who creates this thing? What do they pass it to? How will it be used? Is there any additional documentation we can point to?

2021-04-13 10:15 UTC, KacperKluka commented on publishing-example-java-app/src/test/java/com/ably/tracking/example/javapublisher/PublisherInterfaceUsageExamples.java
> +        ConnectionConfiguration configuration = ConnectionConfigurationToken.create((params) -> new TokenRequest(0, "", "", 0, "", "", ""), "CLIENT_ID");
We've decided that we will show token auth directly in the example apps 
https://github.com/ably/ably-asset-tracking-android/issues/285

2021-04-13 11:45 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/AblyHelpers.kt
> +fun TokenRequest.toAbly(): Auth.TokenRequest =
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/3ff96860584e53990c8d710c1a27894d197b8053

2021-04-13 11:45 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +    /**
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/973f248a5aa9caef59a14f5f97d49f4e013a007f

2021-04-13 11:45 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> + * Represents a set of parameters that are used when requesting an auth token.
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/8d38156fc51d3cab161d811a6dfb2e582b6da7cb

2021-04-13 11:46 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +class TokenRequest(
I'm not sure if I've used the correct documentation link :thinking: https://github.com/ably/ably-asset-tracking-android/pull/222/commits/8d38156fc51d3cab161d811a6dfb2e582b6da7cb

2021-04-13 14:10 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +class TokenRequest(
The link location is ok, but your markup is not recognised by dokka. See staging deployment [here](https://sdk.ably.com/builds/ably/ably-asset-tracking-android/pull/222/dokka/core-sdk/core-sdk/com.ably.tracking/-token-request/index.html). I would just make the word "here" your hyperlink.

2021-04-13 14:50 UTC, QuintinWillison requested changes
In this morning's standup we discussed the likely need for a call on this, after I expressed my concern at the number of properties simply cloned 1:1 from Ably by `TokenRequest` given I had the impression it should be more opaque.

It seems this pull request is currently following [approach 2.1 "Ably TokenRequest is created by your servers and passed to clients"](https://ably.com/documentation/core-features/authentication#token-request-process), necessitating quite a lot of API surface area.

Could we be much more opinionated and only offer a JWT based flow? That would mean refactoring to just follow approach [2.3 "Ably JWT is created by your servers and passed to clients"](https://ably.com/documentation/core-features/authentication#ably-jwt-process), with much less API surface area required in the AAT SDKs.

@paddybyers and @kavalerov - are there any reasons we can't do that? The JWT flow looks architecturally simpler to me. Do we know enough about likely use cases and/or Ably's preferred best practice in this area to insist on that flow?

2021-04-13 14:50 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> + * Interface provided for those using the [ConnectionConfigurationToken] from Java code.
Sorry, I should have spotted this in my first round of review but should this interface not be defined in [core-sdk-java](https://github.com/ably/ably-asset-tracking-android/tree/main/core-sdk-java)?

2021-04-13 14:50 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +    private constructor() : this({ TokenRequest(0, "", "", 0, "", "", "") }, "")
I don't understand why this exists. These dummy values are clearly not viable.

2021-04-13 14:50 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +    private constructor() : this("", "")
What is this doing? These values are clearly not viable.

2021-04-13 15:48 UTC, lmars commented
@QuintinWillison I saw this in passing:

> Could we be much more opinionated and only offer a JWT based flow?

If you do chose this, you can include a link to this example I recently wrote of doing so using AWS Lambda 🙂 

https://github.com/ably-labs/ably-serverless-auth

2021-04-14 07:55 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> + * Interface provided for those using the [ConnectionConfigurationToken] from Java code.
Unfortunately, if it was defined in the `core-sdk-java` module then we wouldn't be able to access it here in the `ConnectionConfigurationToken` class.

2021-04-14 08:00 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +    private constructor() : this({ TokenRequest(0, "", "", 0, "", "", "") }, "")
For some reason, I've thought that I need to add an empty private constructor to forbid creating that object in the Java code. But it turns out that it's not needed at all, thanks for pointing it out :wink: 
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/20bc91e0d59d1edb2ec9cb1e2c8e3e64006e3215

2021-04-14 08:00 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +    private constructor() : this("", "")
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/20bc91e0d59d1edb2ec9cb1e2c8e3e64006e3215

2021-04-14 08:01 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +class TokenRequest(
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/07f971ad8bc8d754c75a7e2790825ec443fb6e3e

2021-04-14 16:12 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> + * Interface provided for those using the [ConnectionConfigurationToken] from Java code.
After our discussion in Slack I've changed the `ConnectionConfiguration` to be an `interface` instead of a `sealed class` in order to move that Java specific code to the `core-sdk-java`. 
Please take a look and let me know if the naming and that whole factory thing is looking alright :wink: https://github.com/ably/ably-asset-tracking-android/pull/222/commits/124b05c26952f3c9a9b01af612c71567d048f8e8

2021-04-14 16:13 UTC, KacperKluka commented
As discussed in a call today, I'll add an integration test that will create and use the token auth flow as a part of this PR.

2021-04-14 19:37 UTC, QuintinWillison requested changes

2021-04-14 19:37 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfigurationKey : ConnectionConfiguration {
I would prefer that the base interface is a suffix, not a prefix. I also think that `Key` may not be the right naming at this level - given the presentation in our [Auth and Security docs](https://ably.com/documentation/core-features/authentication).

On the assumption that we move these interfaces to a new package `com.ably.tracking.connection` and rename the super-interface to `AuthenticationConfiguration` then I propose that this interface be renamed to `BasicAuthenticationConfiguration`.

2021-04-14 19:37 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfigurationToken : ConnectionConfiguration {
I would rename this interface to `TokenAuthenticationConfiguration` and make it a generic type, where that type specifies the return type from the callback. When we fully fledge this API out then this will be one of:

- Token Request (see [2.1](https://ably.com/documentation/core-features/authentication#token-request-process))
- Token (see [2.2](https://ably.com/documentation/core-features/authentication#token-process))
- JWT (see [2.3](https://ably.com/documentation/core-features/authentication#ably-jwt-process) and [2.3(a)](https://ably.com/documentation/core-features/authentication#jwt-embed-process))

For now we're only going to offer interfaces for the token request route, as discussed.

2021-04-14 19:37 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +open class TokenRequestParameters(
Looking at the common themes across all diagrams in our [Token Authentication docs](https://ably.com/documentation/core-features/authentication#token-authentication), I wonder whether we could rename this to `LoginCredentials` given all four ways of doing token authentication all have this entity labelled as "custom login credentials". 🤔

2021-04-15 07:42 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +    private class DefaultConfiguration(
After giving it a second thought I think that it shouldn't be an interface and it doesn't have to be one. I've changed the connection configurations classes to interfaces because I thought it would be necessary in order to move the `TokenRequestCallback` to the `core-java-sdk` module. 
But since I've had to introduce that static factory of configurations for Java users we can safely return to the sealed classes which are more appropriate here. That's because we have a defined set of configurations available and we don't want the users to have the ability to implement their own ones :wink: 
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/bb3ddceec1f734f9c45d031ffecaead84a36edb8

2021-04-15 07:43 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfiguration {
Moved all connection configuration classes to the `com.ably.tracking.connection` package https://github.com/ably/ably-asset-tracking-android/pull/222/commits/dce98de6d285677034320d946541335b73399c8f
Renamed `ConnectionConfiguration` to `AuthenticationConfiguration` https://github.com/ably/ably-asset-tracking-android/pull/222/commits/46ce3469f0417c5f77d7de7693634cc7b3c7942e

I'm wondering if after that renaming we should also modify our API and in both Publisher and Subscriber builder interfaces rename the
```
        fun connection(configuration: AuthenticationConfiguration): Builder
```
to
```
        fun authentication(configuration: AuthenticationConfiguration): Builder
```
WDYT?

2021-04-15 07:43 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfigurationKey : ConnectionConfiguration {
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/224026ae0b8e069788c6f2d6dacbdc76590476be

2021-04-15 07:43 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfigurationToken : ConnectionConfiguration {
https://github.com/ably/ably-asset-tracking-android/pull/222/commits/251f620ae45167a1e9c039e69728a2e95726eada

2021-04-15 09:01 UTC, paddybyers commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +open class TokenRequestParameters(
Login? No, I don't think so

2021-04-15 09:34 UTC, kavalerov commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +open class TokenRequestParameters(
I think we need to keep it the same across Ably SDKs, so if we use one terminology in our platform SDKs, we should use the same here. My understanding is that it means we should keep it as `TokenRequest`

2021-04-15 10:12 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +open class TokenRequestParameters(
I'm specifically talking about the nomenclature for the entity passed to the app developer's auth callback, where there are broadly three "ways" of doing this (see [this comment](https://github.com/ably/ably-asset-tracking-android/pull/222#discussion_r613533504)). I was just keen to challenge our terminology as there's an opportunity to make it clearer with these new SDKs.

What this means, as I understand it, is that we're keeping with:

| "way" | docs | entity passed to the app's auth callback | entity received back from app's auth callback |
| - | - | - | - |
| Token Request | [2.1](https://ably.com/documentation/core-features/authentication#token-request-process) | TokenRequestParameters | Token Request |
| Token | [2.2](https://ably.com/documentation/core-features/authentication#token-process) | Token Request Parameters | Token |
| JWT | [2.3](https://ably.com/documentation/core-features/authentication#ably-jwt-process), [2.3(a)](https://ably.com/documentation/core-features/authentication#jwt-embed-process) | Token Request Parameters | JSON Web Token |

It just feels to me that "token request parameters" isn't necessarily the right naming for all those "ways".

2021-04-15 10:21 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfiguration {
I guess this boils down to the reasoning behind [TO3j](https://docs.ably.io/client-lib-development-guide/features/#TO3j) (being that `ClientOptions` "embeds" `AuthOptions`), meaning that we're naturally leaning towards blending these two as is the case in the underlying client library.

I like the method name `connection`, but perhaps we need an intermediate layer for `ConnectionConfiguration` that has a single property `authentication: AuthenticationConfiguration`?

2021-04-15 10:44 UTC, tbedford commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +open class TokenRequestParameters(
Couple of questions. In your table you call the entity passed "Token Request Parameters" but aren't they "token parameters", as for example: `createTokenRequest(TokenParams tokenParams, AuthOptions authOptions, callback(ErrorInfo err, TokenRequest tokenRequest))` or `requestToken(TokenParams tokenParams, AuthOptions authOptions, callback(ErrorInfo err, TokenDetails tokenDetails))`? Also, when you say passed to app's auth callback, could that also be an auth URL?

2021-04-15 12:08 UTC, KacperKluka commented
@QuintinWillison I added the test that exercises the token authentication https://github.com/ably/ably-asset-tracking-android/pull/222/commits/effda4361aeba0dca4df7c40be3c3df6bbb17773

2021-04-15 12:19 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfiguration {
We could but then the users would have to use it like this:
```
// before
connection(BasicAuthenticationConfiguration(ABLY_KEY, CLIENT_ID))

// after
connection(ConnectionConfiguration(BasicAuthenticationConfiguration(ABLY_KEY, CLIENT_ID)))
```
I mean it's not a big deal but it adds some boilerplate code for the users. On the advantages though if we would ever consider adding some additional options for the Ably SDK then they could just be put in that `ConnectionConfiguration` and won't make any breaking change in the API. :thinking: I'd like to hear what others think about that idea :wink: @paddybyers @kavalerov WDYT?

2021-04-15 12:23 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfiguration {
@QuintinWillison btw I've forgotten to rename the code for java users - I've fixed it in this commit https://github.com/ably/ably-asset-tracking-android/pull/222/commits/418bba3b96e90f6dfc8983b13defc401493cb5aa

2021-04-16 10:28 UTC, kavalerov commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfiguration {
I don't mind adding a bit of boilerplate in exchange for more powerful extensibility in the future.

2021-04-16 13:30 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +interface ConnectionConfiguration {
`ConnectionConfiguration` added :wink:  https://github.com/ably/ably-asset-tracking-android/pull/222/commits/1b9747eff2f3ed4a2410d6c48ae4ecdb796708ce

2021-04-16 13:53 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +open class TokenRequestParameters(
I was taking that from the class name I originally commented on and will admit I didn't look back to the Ably client library to double check the naming there. I'll take a look. FYI, @KacperKluka

2021-04-20 08:03 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConnectionConfigurationModels.kt
> +open class TokenRequestParameters(
We had a call on this yesterday followed by some refactoring commits by me and some more to come this morning from @KacperKluka, so this has evolved to the point that I am happy to close this conversation.

2021-04-20 09:25 UTC, KacperKluka commented on publishing-example-java-app/src/test/java/com/ably/tracking/example/javapublisher/PublisherInterfaceUsageExamples.java
> +        // https://stackoverflow.com/questions/35161913/kotlin-cannot-access-kotlin-jvm-functions-function1-when-calling-kotlin-function/55742956
@QuintinWillison do you intend to leave this commented code for now or was it committed by mistake? :wink:

2021-04-20 09:25 UTC, KacperKluka commented on subscribing-example-java-app/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +        // TODO reinstate once Java interop figured out
We should create an issue for that probably :wink:

2021-04-20 09:34 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
We should create an issue for adding token authentication support to Java users

2021-04-20 10:08 UTC, QuintinWillison commented on publishing-example-java-app/src/test/java/com/ably/tracking/example/javapublisher/PublisherInterfaceUsageExamples.java
> +        // https://stackoverflow.com/questions/35161913/kotlin-cannot-access-kotlin-jvm-functions-function1-when-calling-kotlin-function/55742956
Since our conversation this morning you have reminded me that this would not be solved by anything mentioned in that Stackoverflow post.

2021-04-20 10:08 UTC, QuintinWillison commented on subscribing-example-java-app/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +        // TODO reinstate once Java interop figured out
Yes, I'll do that and will link the issue into this thread shortly.

2021-04-20 10:09 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
Yes, I'll do that. Relates to [your other comment](https://github.com/ably/ably-asset-tracking-android/pull/222#discussion_r616492523).

2021-04-20 10:12 UTC, QuintinWillison approved these changes

2021-04-20 19:28 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
Issue created: https://github.com/ably/ably-asset-tracking-android/issues/297

2021-04-20 19:44 UTC, QuintinWillison commented on publishing-example-java-app/src/test/java/com/ably/tracking/example/javapublisher/PublisherInterfaceUsageExamples.java
> +        // https://stackoverflow.com/questions/35161913/kotlin-cannot-access-kotlin-jvm-functions-function1-when-calling-kotlin-function/55742956
I've removed these empty tests now: https://github.com/ably/ably-asset-tracking-android/pull/222/commits/f9c7c91b73543dc281fef9c68ed84044c62751ea

2021-04-20 19:46 UTC, QuintinWillison commented on subscribing-example-java-app/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +        // TODO reinstate once Java interop figured out
Added [as a comment](https://github.com/ably/ably-asset-tracking-android/issues/297#issuecomment-823553952) to existing issue.

2021-04-20 19:46 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
https://github.com/ably/ably-asset-tracking-android/issues/297

2021-04-20 21:13 UTC, merged