Annotate DTO classes
ably/ably-asset-tracking-android pull request #302
Opened 2021-04-26 07:59 UTC by KacperKluka

Annotated DTO classes with a `@Dto` annotation.

There's a problem with the `GeoJsonMessage` class because it is technically a DTO class but it's exposed in our API in `LocationHistoryData`. The `@Dto` annotation is placed in the `common` module and is not accessible from the `core-sdk` module in which that `GeoJsonMessage` is placed. The easiest solution would be to just move that `@Dto` annotation to the `core-sdk` module but it will make it visible for SDK users. @QuintinWillison WDYT? What should we do with it?

2021-04-28 10:05 UTC, QuintinWillison requested changes

2021-04-29 07:08 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Dto.kt
> +annotation class Dto
Given your commentary (i.e. the part about exported files), I've moved that annotation to the core module https://github.com/ably/ably-asset-tracking-android/pull/302/commits/917f70c563140555616b04bd819c4906c179b073
Because of above, I was able to annotate GeoJSON classes with that annotation https://github.com/ably/ably-asset-tracking-android/pull/302/commits/8b3b1f3467541d9bc08ec70990a999bedc758bbe
Then I've renamed the annotation and added commentary https://github.com/ably/ably-asset-tracking-android/pull/302/commits/aa82010d1ba705e838f8c3155ee6f475700d5129

2021-04-29 07:31 UTC, QuintinWillison requested changes
Thanks. Just one final tweak, please. 😁

2021-04-29 07:31 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/Shared.kt
> +package com.ably.tracking
Now that you've moved it, the name `Shared` is now in the "global" namespace (as it were) which looks odd.

I think a more appropriate package name would be `com.ably.tracking.annotations`.

2021-04-29 07:35 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/Shared.kt
> +package com.ably.tracking
Good point :smile: https://github.com/ably/ably-asset-tracking-android/pull/302/commits/34c20a6e18b9f4ceb376881a6ee1a47eec96d253

2021-04-29 09:39 UTC, QuintinWillison approved these changes

2021-04-29 09:51 UTC, merged