Bring back section about secrets to the readme.
ably/ably-asset-tracking-android pull request #330
Opened 2021-05-14 14:16 UTC by kavalerov

SDK users who visit it's Github page should see all information that is needed to get started in the README. This includes the instruction on how to configure required secrets.

This was moved to the CONTRIBUTING previously, but this should also be mentioned in the core README as it is needed by SDK users as well, not just contributors.

2021-05-14 14:23 UTC, tbedford approved these changes

2021-05-14 18:41 UTC, KacperKluka approved these changes
LGTM :+1:

2021-05-17 16:15 UTC, QuintinWillison requested changes
In respect of:

> needed by SDK users as well, not just contributors

That is not entirely true, so I would like to iterate this PR a little further to make that clear. @kavalerov, I'm happy to take it from here.

2021-05-18 08:46 UTC, kavalerov commented
Right now to run example apps one needs to be able to provide secrets to Gradle. This is not related to contributing to the repo or to the SDK - customer may be running these example apps just to see how SDK works.

However, I agree that this is only related to running example apps from source, and not applicable to "production" use of the SDKs. Let me quickly suggest another change if that's ok :)

2021-05-19 15:40 UTC, QuintinWillison approved these changes
Thanks, @kavalerov - that's much better. 😁

2021-05-19 15:40 UTC, merged