Send trip start and trip end events on a meta channel from Publisher SDK
ably/ably-asset-tracking-android pull request #357
Opened 2021-06-02 08:52 UTC by KacperKluka

When a trackable is added we're sending trip start event. When a trackable is removed we're sending trip end event. When the publisher is stopped we're sending end trip events for all trackables in the publisher.

I've changed the approach of postponing operations until a raw location is present. Before we had a static field with a `Destination` that was used to postpone setting the destination until any raw location is received. Now we have a list of commands that are run when a raw location is received. This way it's much more flexible and allows to queue multiple operations that depend on raw location.

2021-06-04 13:27 UTC, AndyNicks approved these changes

2021-06-07 15:28 UTC, QuintinWillison requested changes
Some immediate observations.

However, I'm also wondering if there's a corresponding issue defining the scope of this work?

2021-06-07 15:28 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val METADATA_TRIP = "[meta]asset-tracking:trip-lifecycle"
If this is a channel name prefix, then shouldn't it be `tracking` (not `asset-tracking`) to match [what's defined elsewhere](https://github.com/ably/ably-asset-tracking-android/blob/774c02cc52038e91e5c12a3a8a44645e9961ff78/common/src/main/java/com/ably/tracking/common/Ably.kt#L137)?

2021-06-07 15:28 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val TRIP_START = "trip.start"
Is there a foundation for this naming convention?

It seems incongruous with the concrete value of `ENHANCED`.

2021-06-07 17:43 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val METADATA_TRIP = "[meta]asset-tracking:trip-lifecycle"
As far as I understand this channel shouldn't be treated in the same way as other trackable channels. This is a unique channel that will be used across all AAT users. Is it right @AndyNicks @kavalerov ? :wink:

2021-06-07 17:44 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val TRIP_START = "trip.start"
@AndyNicks @kavalerov I think that you've come up with those names, was there any particular reason behind them? :wink:

2021-06-08 08:18 UTC, AndyNicks commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val TRIP_START = "trip.start"
If this naming convention conflicts with the agreed  scheme, let's change it.

2021-06-08 08:22 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val TRIP_START = "trip.start"
As far as I'm aware there's no agreed scheme, it just seems like we may be forming one. 😁

2021-06-08 08:26 UTC, AndyNicks commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val TRIP_START = "trip.start"
So let it be :-)

2021-06-08 08:45 UTC, kavalerov commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val METADATA_TRIP = "[meta]asset-tracking:trip-lifecycle"
This is a metachannel, which will be defined across Ably infrastructure, therefore `tracking` wouldn't be enough (in wider Ably context tracking can mean many things, whereas `asset-tracking` specifies a product). So it should be `asset-tracking`.

2021-06-08 08:50 UTC, kavalerov commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val TRIP_START = "trip.start"
So this approach (`trip.start`) is similar to what we use in lifecycle events on Ably metachannels (see more: https://ably.com/documentation/realtime/metachannels#lifecycle-events).

This way we align the metachannel message format. 

Now, I can see potential reason for us changing the `ENHANCED` in the future, but I think it would be outside of the scope of this PR for sure.

2021-06-08 09:35 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val METADATA_TRIP = "[meta]asset-tracking:trip-lifecycle"
Great, thanks @kavalerov ... @KacperKluka could you please add commentary to that effect and add the commit reference to this conversation when done so I can resolve. Thanks.

2021-06-08 09:36 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val TRIP_START = "trip.start"
Great, thanks. @KacperKluka, could you please add commentary including the essence of what Ivan states above. Thanks.

2021-06-08 09:57 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val METADATA_TRIP = "[meta]asset-tracking:trip-lifecycle"
https://github.com/ably/ably-asset-tracking-android/pull/357/commits/a72c54c1cac051079205596db03562a24abdacac

2021-06-08 09:58 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Constants.kt
> +    const val TRIP_START = "trip.start"
https://github.com/ably/ably-asset-tracking-android/pull/357/commits/b9a00dcda319422ff9612a317a386fed44d61bbd

2021-06-08 13:05 UTC, merged

2021-06-08 13:08 UTC, kavalerov commented
Just to confirm - we have tested that this does produce all required events on the metachannel on Ably (as in - one can see them by subscribing to the metachannel, i.e. in the dashboard)?

2021-06-08 13:53 UTC, QuintinWillison commented
I've not tested it myself. I don't know whether @KacperKluka did while developing this.

2021-06-08 13:56 UTC, kavalerov commented
Ok, then I don't think this should've been merged

2021-06-09 08:58 UTC, QuintinWillison commented
Thanks, @kavalerov - I agree. 😁 

As discussed in yesterday afternoon's retro and planning meeting, we failed to validate against the acceptance criteria specified in https://github.com/ably/ably-asset-tracking-android/issues/374.

We are going to address that under https://github.com/ably/ably-asset-tracking-android/issues/376.