Show custom notification for Mapbox trip service
ably/ably-asset-tracking-android pull request #389
Opened 2021-06-29 10:08 UTC by KacperKluka

Replaced the default Mapbox trip notification with a custom one and added a method to the builder which allows users to specify their own notification. I had to exclude the original notification module and specify which of our classes will be responsible for handling the notification. I've been following this and this guides.

Thanks to that we're able to run 2 services under one notification. Additionally, the original notification had a button that allowed the user to stop Mapbox service while Publisher was working which led to malfunction.

2021-06-30 10:25 UTC, AndyNicks approved these changes

2021-07-06 12:42 UTC, QuintinWillison approved these changes

2021-07-06 12:42 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/MapboxTripNotification.kt
> +    private val NOTIFICATION_ID = 819203
I'm curious as to where this number comes from - it seems a bit "magic". Could you perhaps add a comment to explain?

2021-07-06 12:56 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/MapboxTripNotification.kt
> +    private val NOTIFICATION_ID = 819203
Yes, so this is one of those things that are not very clear in Android :sweat_smile: In [the docs](https://developer.android.com/training/notify-user/build-notification#notify) they say that `notificationId is a unique int for each notification that you must define` and that it's used to `update or remove the notification`. 
However, they don't let us know if this should be unique device-wise, app-wise or only SDK-wise :unamused: 
So as my rule of thumb, I try to come up with some random number that hopefully won't collide with any other notification ID. But this may be just my superstition :sweat_smile:

2021-07-07 20:02 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/MapboxTripNotification.kt
> +    private val NOTIFICATION_ID = 819203
@KacperKluka Looking at [the API reference for the `notify` method](https://developer.android.com/reference/android/app/NotificationManager#notify(int,%20android.app.Notification)), it states:

> An identifier for this notification unique within your application

Which, I feel, clears up the confusion (i.e. it is "app-wise").

I'm not happy with this being baked into the SDK as there is no reason why the app developer who has embedded our SDK might not pluck this number out of the air themselves also.

It's also made me take a closer look at what we're doing anyway with these notifications which is, in turn, making me challenge whether this is something that's appropriate for the SDK to be doing at all! Not to mention the lack of [localisation](https://developer.android.com/guide/topics/resources/localization) opportunity for the textual strings used.

2021-07-07 20:04 UTC, QuintinWillison requested changes
On [further reflection](https://github.com/ably/ably-asset-tracking-android/pull/389#discussion_r665669644) this needs more work. We'll discuss internally and then move this pull request forwards.

2021-07-09 10:40 UTC, KacperKluka commented
After today's call we've decided to not provide a default notification but to make the `notification()` builder method (which will be renamed to `backgroundTrackingNotificationProvider()` as a part of those changes) a required one.
Moreover, we'll make some changes to the `AssetTrackingNotification` so it will be responsible of providing the notification only and the notification ID will become a param of the builder method.

2021-07-09 11:46 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/MapboxTripNotification.kt
> +    private val NOTIFICATION_ID = 819203
I've made the changes we've discussed on our today's call :wink: Here are they https://github.com/ably/ably-asset-tracking-android/pull/389/files/f05c3610d4303b202b0f274abd2072ebd9fc145e..5d7df052bb647abdd1e62084c4fada47a4235b80

2021-07-09 12:28 UTC, AndyNicks approved these changes

2021-07-21 04:25 UTC, QuintinWillison approved these changes

2021-07-21 06:16 UTC, ben-xD approved these changes

2021-07-22 08:10 UTC, merged