Stop the publisher when the PublisherService is destroyed
ably/ably-asset-tracking-android pull request #427
Opened 2021-09-02 15:15 UTC by KacperKluka

To stay on the safe side we're stopping the publisher when the `PublisherService` is being destroyed (which happen when it's stopped by user or force closed by the OS). Without it there's a chance that there will be multiple active publishers.

2021-09-10 08:46 UTC, QuintinWillison requested changes

2021-09-10 08:46 UTC, QuintinWillison commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt
> +        scope.launch { publisher?.stop() }
I think there should be some commentary here, or perhaps on this method, to explain why we're doing this and why it's important.

2021-09-10 10:11 UTC, KacperKluka commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt
> +        scope.launch { publisher?.stop() }
https://github.com/ably/ably-asset-tracking-android/pull/427/commits/034980adfb4168e89c64c5bcf7f714bacda8aa4b

2021-09-15 15:28 UTC, QuintinWillison approved these changes

2021-09-15 20:51 UTC, merged