Change AppPreferences to the singleton pattern
ably/ably-asset-tracking-android pull request #445
Opened 2021-09-22 10:37 UTC by KacperKluka

Because we don't want to complicate the app by introducing a DI tool, I've changed the `AppPreferences` to a singleton manually.

2021-09-22 11:51 UTC, AndyNicks approved these changes

2021-09-24 10:14 UTC, QuintinWillison requested changes

2021-09-24 10:14 UTC, QuintinWillison commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/AppPreferences.kt
> +            if (instance == null) {
I would have expected this check to be _within_ the `synchronized` scope. 🤔

2021-09-24 10:45 UTC, KacperKluka commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/AppPreferences.kt
> +            if (instance == null) {
We have 2 null checks here: one inside and one outside the `synchronized` scope. 
```kotlin
if(instance == null) {
    synchronized {
        if(instance == null) {
            instance = AppPreferences(context)
        }
    }
}
return instance
```
Thanks to this we only run the `synchronized` code when we need to. After the instance will be created the `synchronized` won't be called again saving us some performance :wink: If we only had one null check inside the `synchronized` scope it would look like this
```kotlin
synchronized {
    if(instance == null) {
        instance = AppPreferences(context)
    }
}
return instance
```
and it would call the `synchronized` block each time we would call this method, which is unnecessary.

2021-09-24 11:56 UTC, QuintinWillison commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/AppPreferences.kt
> +            if (instance == null) {
I see. That makes sense. Thanks for explaining.

That pattern has never particularly occurred to me and/or I've not noticed it used elsewhere. I guess it's an alternative to using something like `volatile` on the field.

In my defence there could be an argument that this is a premature optimisation that's slightly counter to the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), but my feelings aren't too strong on that as this does look harmless enough.

2021-09-24 11:56 UTC, QuintinWillison approved these changes

2021-09-24 13:00 UTC, merged