Add hepler extension function for showing toasts
ably/ably-asset-tracking-android pull request #452
Opened 2021-09-29 08:27 UTC by KacperKluka

I've spotted that we had a lot of duplicated `showToast()` methods across the publisher example app so I've extracted the code to helper extension functions, making them available to everything that is or has a `Context` object.

2021-09-29 10:43 UTC, ben-xD approved these changes

2021-09-29 10:43 UTC, ben-xD commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/Extensions.kt
> +fun Context.showLongToast(message: String) {
i dont wanna add random work but these 2 methods could be `showToast()` with optional parameters (e.g. duration) with a default (`LENGTH_SHORT`). This would make it more consistent with the existing makeText API.

2021-09-29 13:22 UTC, KacperKluka commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/Extensions.kt
> +fun Context.showLongToast(message: String) {
Right, I've also considered the approach you're talking about but in the end, I've chosen the explicit function name way :wink: This might be simply a matter of personal preferences but I'd love to hear @QuintinWillison and @ikbalkaya opinion on that :grin:

2021-09-29 13:32 UTC, ikbalkaya requested changes
LGTM except for a minor readability improvement request

2021-09-29 13:32 UTC, ikbalkaya commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/AddTrackableActivity.kt
> +                showLongToast("Insert tracking ID")
Am I right to think that string is not localised here as it's for an example  
🤔

2021-09-29 13:32 UTC, ikbalkaya commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/Extensions.kt
>          0
I don't want to create extra work but I'd definitely benefit from naming of these arguments here, at least 0 here does give me very little clue about what it is

2021-09-29 13:32 UTC, ikbalkaya commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/Extensions.kt
> +fun Context.showLongToast(message: String) {
I'd say Kotlin style goes better with different naming (eg. list.isEmpty, list.isNotEmpty). Additional parameters gives flexibility but I think in this case it's better to stay with separate naming. It makes it easier for clients

2021-09-30 06:23 UTC, ben-xD commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/Extensions.kt
> +fun Context.showLongToast(message: String) {
Okay I don't mind, please resolve this conversation once you're satisfied with everyones comments

2021-09-30 06:23 UTC, KacperKluka commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/AddTrackableActivity.kt
> +                showLongToast("Insert tracking ID")
That's right, however, I think that we should stick to best practices and move all messages to the `strings.xml` file and make it possible to easily localize the app. It may be useful for someone who would like to use it as an example in some other language :wink: I've created an issue for that https://github.com/ably/ably-asset-tracking-android/issues/455 thanks for spotting this :bow:

2021-09-30 06:33 UTC, KacperKluka commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/Extensions.kt
>          0
I agree with you, that magic number isn't saying anything :sweat_smile: However, that feels a bit outside of this PR's scope so I've put it in another PR https://github.com/ably/ably-asset-tracking-android/pull/456 :wink:

2021-09-30 06:34 UTC, ikbalkaya commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/AddTrackableActivity.kt
> +                showLongToast("Insert tracking ID")
Great. I'll resolve this conversation than

2021-09-30 07:16 UTC, ikbalkaya approved these changes
LGTM

2021-09-30 11:31 UTC, QuintinWillison commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/Extensions.kt
> +fun Context.showLongToast(message: String) {
I've not got a massively strong opinion either way, but if I think the following considerations probably swing this towards keeping with the longer names for these extension methods, not adding a `duration` parameter:

- these extensions are internal to this example app codebase - so consistency with the underlying APIs they use is not such a major concern as they serve a domain with a narrow scope
- these extensions are designed to be used 'quickly' from this example app codebase - so it could be argued that having another parameter to think about, especially when it's 'borrowed' from another API, adds cognitive load to maintainers
- the longer names do exactly what they say on the tin - whereas a default parameter means that at the call sites there is no indication that the toast is 'short' by default - more cognitive load and opportunity for future maintainers to accidentally spawn a short toast when they wanted a long one

Side-note: I had to look up [makeText](https://developer.android.com/reference/android/widget/Toast#makeText(android.content.Context,%20int,%20int)) to understand this conversation (next time, @ben-xD, it would be great if you could turn mentions of third-party / external foundational APIs into links to make it easier for others participating in the conversation).

2021-09-30 11:39 UTC, KacperKluka commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/Extensions.kt
> +fun Context.showLongToast(message: String) {
Thank you all for your input :bow: Given [Ben's permission](https://github.com/ably/ably-asset-tracking-android/pull/452#discussion_r719092835) I'm resolving this conversation :wink:

2021-10-01 13:15 UTC, merged