Add API level 21 to the testing matrix
ably/ably-asset-tracking-android pull request #454
Opened 2021-09-29 10:54 UTC by KacperKluka

Added API 21 to our emulate workflow testing matrix. This is our `minSdkVersion` for the Kotlin SDKs.

2021-09-29 10:55 UTC, ben-xD approved these changes

2021-09-29 14:42 UTC, ikbalkaya approved these changes
LGTM

2021-10-04 08:31 UTC, QuintinWillison requested changes
Sorry, @KacperKluka ... I was sure I had submitted my review for this pull request but just noticed that I had left it 'Pending'. 🤦

2021-10-04 08:39 UTC, KacperKluka commented on .github/workflows/emulate.yml
> +          script: ${{ matrix.excludeModules && './gradlew cC -x :publishing-java-testing:cC -x :subscribing-java-testing:cC -x :publishing-example-app:cC -x :subscribing-example-app:cC' || './gradlew
https://github.com/ably/ably-asset-tracking-android/pull/454/commits/78c493215f63234754eb6d9361a14243f9d3b25d

2021-10-04 09:43 UTC, QuintinWillison approved these changes

2021-10-04 09:46 UTC, merged