Extract hardcoded strings from example apps to string resources
ably/ably-asset-tracking-android pull request #486
Opened 2021-10-21 08:43 UTC by KacperKluka

We should keep all potentially translatable strings in the `strings.xml` resources file to make it easier to localize the app. I've changed the toast helper methods to accept string resource ID to prevent using hardcoded strings in the future.

2021-11-03 01:45 UTC, QuintinWillison requested changes
I think there are some consistency issues with the names you have defined for string resources not matching the textual values they have, or necessarily the class of message they display to the user. 

In terms of consistency, a good example would be `error_stop_publisher` returning value "Stopping publisher error" - whereas `error_publisher_service_not_started` returning a more logically 1:1 mapped value "Publisher service not started".

In terms of message class, in some cases it's a straight up "I failed, sorry" whereas in others it's more like "Things failed, but you can do something to fix this, and this is what it is". I think it might be helpful to differentiate these somehow.

2021-11-03 01:45 UTC, QuintinWillison commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/MainActivity.kt
> +                            showLongToast(R.string.error_stop_publisher)
In this particular case (and a few others where the toast is shown from within a `catch` block) I would have expected it to be useful to display to the user at least the message from `e`. Have you considered that some of these strings may need to take an argument to produce a dynamically formatted output?

2021-11-03 07:38 UTC, KacperKluka commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/MainActivity.kt
> +                            showLongToast(R.string.error_stop_publisher)
Toasts are not a great tool for showing longer messages since they disappear after a while and the message is gone. Also, the area and text they show are rather small and cramped. Therefore, I would prefer to not show information from exceptions in them. A better place for such errors would be the console log or (if we want users to see them) an alert dialogue. :wink:

2021-11-04 05:20 UTC, QuintinWillison commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/MainActivity.kt
> +                            showLongToast(R.string.error_stop_publisher)
https://github.com/ably/ably-asset-tracking-android/issues/500

2021-11-04 05:21 UTC, QuintinWillison approved these changes

2021-11-04 05:21 UTC, merged