Conform readme and docs
ably/ably-asset-tracking-android pull request #487
Opened 2021-10-22 11:05 UTC by ikbalkaya

This pull request aims to make Readme file conforming template described in this link
https://github.com/ably/ably-common/blob/main/templates/sdk-readme.md

Some notes 
* Documentation here has more sections here than in the standard template. I did not remove them as it made sense to have those additional sections (as there are subscribing / publishing SDKs)
* Sections are ordered with consideration of their semantics (For example I put resolution policy under "Usage" section as it was related)
* I renamed "Documentation" to "Resources" and changed "Useful resources" to "Useful links". I'm not sure if that's the correct approach but I thought it made sense

2021-10-31 09:44 UTC, QuintinWillison requested changes

2021-10-31 09:44 UTC, QuintinWillison commented on README.md
> +#### Useful links
For consistency, please add vertical whitespace below this line.

2021-10-31 09:44 UTC, QuintinWillison commented on README.md
> +
For consistency, please only ever use a single line of vertical whitespace.

2021-11-01 08:57 UTC, ikbalkaya commented on README.md
> +
https://github.com/ably/ably-asset-tracking-android/commit/dc5caa61414f94e61f2bed9d372c48acd9e8e67c

2021-11-01 08:57 UTC, ikbalkaya commented on README.md
> +#### Useful links
https://github.com/ably/ably-asset-tracking-android/commit/dc5caa61414f94e61f2bed9d372c48acd9e8e67c

2021-11-01 10:03 UTC, QuintinWillison approved these changes

2021-11-01 10:03 UTC, merged