Send raw locations from the Publisher
ably/ably-asset-tracking-android pull request #493
Opened 2021-10-29 13:31 UTC by KacperKluka

Enabled sending of the raw locations on the same channel on which the enhanced locations are being sent. The raw locations have all the mechanisms that the enhanced ones have, especially resolution and `skippedLocations`. As the raw locations shouldn't be normally published, there is a new option on the builder that enables the raw locations. The commentary on this method states clearly that this should not be enabled in the production environment. Additionally, information about whether the raw locations are enabled is added to the `PresenceData` of the publisher.

2021-11-02 07:50 UTC, QuintinWillison requested changes
Overall looks very good, thanks. I guess I'm surprised at how much code you needed to add to gain this functionality - it clearly cuts quite deep.

2021-11-02 07:50 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +     * If a channel for the [trackableId] doesn't exist then it just calls [callback] with success.
Do you rely on this behaviour? This feels surprising to me, at least when examining this API in isolation. I generally feel it's better to prefer failure (a.k.a. fail early) rather than 'hide' unexpected cases. 🤔

2021-11-02 07:50 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt
> +        fun enableRawLocations(): Builder
I would prefer to remove the `enable` prefix and accept a boolean here.

2021-11-02 08:41 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt
> +        fun enableRawLocations(): Builder
https://github.com/ably/ably-asset-tracking-android/pull/493/commits/cf983ce2676aceaac726873fa72bef6f7d7a5ea5

2021-11-02 08:44 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +     * If a channel for the [trackableId] doesn't exist then it just calls [callback] with success.
I don't think that we use this behaviour but since it is how all methods in this interface work I would prefer to create a separate issue to change this instead of changing it in this PR :wink: WDYT? Should I create the issue?

2021-11-03 01:47 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +     * If a channel for the [trackableId] doesn't exist then it just calls [callback] with success.
Yes. Happy to see an issue created for this, under [code-quality](https://github.com/ably/ably-asset-tracking-android/labels/code-quality).

2021-11-03 01:48 UTC, QuintinWillison approved these changes

2021-11-03 07:22 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +     * If a channel for the [trackableId] doesn't exist then it just calls [callback] with success.
Issue created: https://github.com/ably/ably-asset-tracking-android/issues/496

2021-11-04 12:06 UTC, ikbalkaya requested changes
I made a request which should improve readability slightly

2021-11-04 12:06 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/message/MessageMappers.kt
> +fun LocationUpdate.toJson(gson: Gson): String =
To me, this name is a bit misleading. It implies that the `LocationUpdate` is going to be serialised but it's a `LocationUpdateMessage` serialization. Is that how this object will be serialised all the time? If not, could you rename this to something like `toMessageJson` ? Thank you 🙏

2021-11-04 12:06 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/message/MessageMappers.kt
>  fun EnhancedLocationUpdate.toJson(gson: Gson): String =
Similar as above

2021-11-04 13:02 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/message/MessageMappers.kt
> +fun LocationUpdate.toJson(gson: Gson): String =
https://github.com/ably/ably-asset-tracking-android/pull/493/commits/5ebd47d7cb347705074d1d995a72d08ead22e26a

2021-11-04 13:02 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/message/MessageMappers.kt
>  fun EnhancedLocationUpdate.toJson(gson: Gson): String =
https://github.com/ably/ably-asset-tracking-android/pull/493/commits/5ebd47d7cb347705074d1d995a72d08ead22e26a

2021-11-04 13:34 UTC, ikbalkaya approved these changes
Looks good 😎

2021-11-04 14:09 UTC, merged