Add raw locations to the Subscriber SDK
ably/ably-asset-tracking-android pull request #495
Opened 2021-11-02 13:14 UTC by KacperKluka

I've enabled listening for raw locations in the Subscriber SDK. I've also added this to the Java facade of Subscriber. Additionally, I've added an integration test that checks if there is a raw data flow between publisher and subscriber.

2021-11-03 01:54 UTC, QuintinWillison requested changes
I think this is more complicated than it needs be, with too much new API added.

2021-11-03 01:54 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    fun subscribeForRawEvents(trackableId: String, listener: (LocationUpdate) -> Unit)
I recognise that I'm looking at an internal API here, however I think we should highlight in as many places as possible that these raw location updates will only be received if opted in to (overriding builder default) at publisher end.

2021-11-03 01:54 UTC, QuintinWillison commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/Subscriber.kt
> +        fun rawLocations(enabled: Boolean): Builder
I don't feel we need this API at all. If the application developer has not added a consumer to the `rawLocations` shared flow then they are clearly already signalling that they do not care about this data. Same goes for the `rawLocations` method you've added to the subscriber builder in this pull request.

2021-11-03 08:50 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/Subscriber.kt
> +        fun rawLocations(enabled: Boolean): Builder
This `rawLocations()` method was added to prevent us from subscribing to the raw messages when it's unnecessary (see [here](https://github.com/ably/ably-asset-tracking-android/pull/495/files#diff-b61a79b87abd92c047c791b03922a3c91ad39f1e9c3c32c30c32ee55847a47cbR141-R143)) :thinking: If we remove it then we will always have to subscribe for raw locations and push them to the `SharedFlow` even if the user won't be using them. If that's fine then we can safely remove this from the subscriber's builder :wink:

2021-11-03 08:51 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    fun subscribeForRawEvents(trackableId: String, listener: (LocationUpdate) -> Unit)
https://github.com/ably/ably-asset-tracking-android/pull/495/commits/82cc783b8da37d78b0ccf07eaca8e5b17fec0747

2021-11-04 12:24 UTC, QuintinWillison commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/Subscriber.kt
> +        fun rawLocations(enabled: Boolean): Builder
The service will be sending all data regardless, given subscription filtering is a client-side only thing at the subscriber. As discussed in Slack, I think we should remove this API. It can always be introduced in future if there's some perceived benefit - but, for now, the simple availability of the shared flow is ample.

2021-11-04 12:57 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/Subscriber.kt
> +        fun rawLocations(enabled: Boolean): Builder
https://github.com/ably/ably-asset-tracking-android/pull/495/commits/f501664c42451cefa819a9aadcd3cb02b97d87d1

2021-11-04 14:02 UTC, ikbalkaya approved these changes
LGTM

2021-11-08 16:14 UTC, QuintinWillison approved these changes

2021-11-08 16:15 UTC, merged