Fixed Copyright footer
ably/ably-asset-tracking-android pull request #503
Opened 2021-11-04 15:23 UTC by ikbalkaya

This pull request fixes Copyright information in the footer.

Unfortunately I couldn't find (and probably there isn't) a safe way to configure this in a 'type safe' way as dokka plugin is written in Kotlin. I have found another project using it in the way I have done it here so I thought I will give it a go and it worked well.  The usage is here https://github.com/GetStream/stream-chat-android/blob/main/scripts/publish-module.gradle

2021-11-05 07:24 UTC, KacperKluka requested changes
Overall looks good, I only have some code formatting suggestions :wink:

2021-11-05 07:24 UTC, KacperKluka commented on build.gradle
> +tasks.dokkaHtmlMultiModule.configure {
Maybe let's add an explanatory comment above this to show why it's here and what is it doing? :wink:

2021-11-05 07:24 UTC, KacperKluka commented on build.gradle
>  allprojects {
I think there should be a new line between `}` and `allprojects` :wink:

2021-11-05 07:24 UTC, KacperKluka commented on build.gradle
>      // The version of Ably's client library for Java that we're using.
We could insert a newline between those two lines :wink:

2021-11-05 07:24 UTC, KacperKluka commented on build.gradle
> +            // override because v.9.4.1 of org.jlleitschuh.gradle.ktlint plugin is at 0.38.1 which has issues
We should be careful with those code reformatting tools, look that it took the comment about the `version` field and put it below it, which suggests that it belongs to the `verbose' below :sweat_smile: Please put the comment above the `version` field :wink:

2021-11-05 07:24 UTC, KacperKluka commented on build.gradle
> +        final hasDokkaPlugin = evaluatedSubProject.pluginManager.hasPlugin('org.jetbrains.dokka')
I'd put it at the top of the `afterEvaluate` block, where all the `final evaluatedSubProjectIsXYZ` lines are :wink:
And also maybe let's stay consistent and rename it to `evaluatedSubProjectHasDokka`? :thinking:

2021-11-05 07:24 UTC, KacperKluka commented on build.gradle
> +
I think we can safely remove those lines :wink:

2021-11-05 13:06 UTC, KacperKluka commented on build.gradle
> +tasks.dokkaHtmlMultiModule.configure {
Resolving because of changes from https://github.com/ably/ably-asset-tracking-android/pull/503/commits/285b113e490859fad31050e84088cf1203eb8fc5

2021-11-05 13:07 UTC, KacperKluka commented on build.gradle
>  allprojects {
Resolving because of changes from https://github.com/ably/ably-asset-tracking-android/pull/503/commits/285b113e490859fad31050e84088cf1203eb8fc5

2021-11-05 13:50 UTC, ikbalkaya commented on build.gradle
> +        final hasDokkaPlugin = evaluatedSubProject.pluginManager.hasPlugin('org.jetbrains.dokka')
https://github.com/ably/ably-asset-tracking-android/pull/503/commits/285b113e490859fad31050e84088cf1203eb8fc5

2021-11-05 13:51 UTC, ikbalkaya commented on build.gradle
> +
https://github.com/ably/ably-asset-tracking-android/pull/503/commits/285b113e490859fad31050e84088cf1203eb8fc5

2021-11-05 14:01 UTC, KacperKluka commented on build.gradle
> +            // override because v.9.4.1 of org.jlleitschuh.gradle.ktlint plugin is at 0.38.1 which has issues
This was most likely done automatically by the IDE :wink: I don't have any configuration that I'm aware of that could make it work better :thinking: I guess we just need to be careful when running code reformatting and fix things like this manually :shrug:

2021-11-05 14:04 UTC, KacperKluka commented on build.gradle
> -
Sorry for being picky, but I would prefer to leave this newline for better readability :sweat_smile:

2021-11-08 16:44 UTC, ikbalkaya commented on build.gradle
> -
Hey no worries. I don't even remember removing the line. It's here https://github.com/ably/ably-asset-tracking-android/pull/503/commits/a7118dd448a0af7ecb4d50fbd9e5ae7d4a09a77e

2021-11-08 16:48 UTC, ikbalkaya commented on build.gradle
> +            // override because v.9.4.1 of org.jlleitschuh.gradle.ktlint plugin is at 0.38.1 which has issues
Tried to address this here https://github.com/ably/ably-asset-tracking-android/pull/503/commits/a7118dd448a0af7ecb4d50fbd9e5ae7d4a09a77e but Android studio will cut it due to line width setting. As I'm using a bigger font, it will break line a little bit earlier. Can you let me know what size of font do you use so that I can hopefully adjust my line settings accordingly?

2021-11-08 17:38 UTC, KacperKluka commented on build.gradle
> +            // override because v.9.4.1 of org.jlleitschuh.gradle.ktlint plugin is at 0.38.1 which has issues
Oh, I simply thought about moving the comment above the `version = '0.41.0'` line :sweat_smile: So it would look like this
```groovy
// override because v.9.4.1 of org.jlleitschuh.gradle.ktlint plugin is at 0.38.1 which has issues
version = '0.41.0'
```

2021-11-08 17:42 UTC, ikbalkaya commented on build.gradle
> +            // override because v.9.4.1 of org.jlleitschuh.gradle.ktlint plugin is at 0.38.1 which has issues
Oh right. Here it is https://github.com/ably/ably-asset-tracking-android/pull/503/commits/98e7a53cd51fef06da714da92de11abb07761df6

2021-11-08 18:26 UTC, KacperKluka commented on build.gradle
> +            // override because v.9.4.1 of org.jlleitschuh.gradle.ktlint plugin is at 0.38.1 which has issues
Awesome, thank you :bow:

2021-11-08 18:26 UTC, KacperKluka approved these changes
LGTM :+1:

2021-11-19 13:52 UTC, QuintinWillison requested changes
https://github.com/ably/ably-asset-tracking-android/pull/503/commits/1f25e2509e097854e413a41fd855ea6caeb01789 includes a lot of unrelated indentation changes. These make it difficult for reviewers to focus on the actual change being made.

2021-11-19 13:52 UTC, QuintinWillison commented on build.gradle
> +        //dokka configuration for modules
for readability and consistency with other comments in this file, please include adequate horizontal space:

```suggestion
        // dokka configuration for modules
```

2021-11-19 13:52 UTC, QuintinWillison commented on build.gradle
> +//https://github.com/Kotlin/dokka/issues/2202#issuecomment-950666269
```suggestion
// https://github.com/Kotlin/dokka/issues/2202#issuecomment-950666269
```

2021-11-19 13:52 UTC, QuintinWillison commented on build.gradle
> +                        ["org.jetbrains.dokka.base.DokkaBase": """{ "footerMessage": "$copyright_message"}"""]
The indentation level for this line seems very deep.

2021-11-19 13:52 UTC, QuintinWillison commented on build.gradle
> +            ["org.jetbrains.dokka.base.DokkaBase": """{ "footerMessage": "$copyright_message"}"""]
The indentation for this line seems very deep.

Also, why is this needed here _as well_ as later on at subproject evaluation? I would have expected it to only be needed in one of these. And, if it is needed in both, then I think a comment explaining what each is achieving is helpful.

2021-11-19 14:18 UTC, ikbalkaya commented on build.gradle
> +        //dokka configuration for modules
https://github.com/ably/ably-asset-tracking-android/pull/503/commits/f7fd7a9927ffaa09b7caa0bb4ca925428b0df3df

2021-11-19 14:19 UTC, ikbalkaya commented on build.gradle
> +//https://github.com/Kotlin/dokka/issues/2202#issuecomment-950666269
https://github.com/ably/ably-asset-tracking-android/pull/503/commits/f7fd7a9927ffaa09b7caa0bb4ca925428b0df3df

2021-11-19 14:21 UTC, ikbalkaya commented on build.gradle
> +                        ["org.jetbrains.dokka.base.DokkaBase": """{ "footerMessage": "$copyright_message"}"""]
Indentation issues were about that I hadn't enabled EditorConfig support on my IDE, so it would use the default indentation level, I enabled it and re-run the formatter which should hopefully fix the indentations here https://github.com/ably/ably-asset-tracking-android/pull/503/commits/2c29e5183b89b1338db36362138c0275e0acbd11

2021-11-19 14:37 UTC, ikbalkaya commented on build.gradle
> +            ["org.jetbrains.dokka.base.DokkaBase": """{ "footerMessage": "$copyright_message"}"""]
For indentation change, see https://github.com/ably/ably-asset-tracking-android/commit/2c29e5183b89b1338db36362138c0275e0acbd11

2021-11-19 14:37 UTC, ikbalkaya commented on build.gradle
> +            ["org.jetbrains.dokka.base.DokkaBase": """{ "footerMessage": "$copyright_message"}"""]
I also provided an explanation comment here https://github.com/ably/ably-asset-tracking-android/pull/503/commits/30cab1ed9fd9b766561784392553b6d90ad74a9a

2021-11-19 14:56 UTC, ikbalkaya commented
> [1f25e25](https://github.com/ably/ably-asset-tracking-android/commit/1f25e2509e097854e413a41fd855ea6caeb01789) includes a lot of unrelated indentation changes. These make it difficult for reviewers to focus on the actual change being made.

This was due to me not having BuildConfig setting on AS. I attempted to revert-recommit this but unfortunately I wasn't able to due to conflicts and I didn't want to play with more git history.

2021-11-22 09:50 UTC, QuintinWillison commented on build.gradle
> +                        ["org.jetbrains.dokka.base.DokkaBase": """{ "footerMessage": "$copyright_message"}"""]
Nice, thanks. 😄

2021-11-22 09:51 UTC, QuintinWillison approved these changes

2021-11-22 10:36 UTC, merged