Refactor ably wrapper
ably/ably-asset-tracking-android pull request #511
Opened 2021-11-11 14:05 UTC by ikbalkaya

2021-11-12 15:45 UTC, ikbalkaya commented
I'm having issues with reformatting code to match ktlint style. It will complain about my indentation being 4 and not 5. But I will indent code to 5 and then it will complain otherwise 😩  Help please @KacperKluka

2021-11-15 13:56 UTC, KacperKluka requested changes
I'm not sure how wrapping the callbacks in a `scope.launch()` will make the code safer :thinking:
Given we are using a single-threaded dispatcher for the launch we have a guarantee that the `launch()` calls will be executed in the order in which they were called. However, why do we need this? :thinking: 
I noticed that in two places we are mutating the `channels` map from this scope so I guess this gives us some safety in terms of modifying this state, but then we are still accessing the state without any protection (all the `channels[trackableId]?.let {...}` calls).

Given that the only state that needs protection is the `channels` map maybe it would be better to use some multithread-safe data structure like [`ConcurrentHashMap`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html) to handle everything related to thread safety? :thinking: WDYT? :wink:

2021-11-15 13:56 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    override fun disconnect(trackableId: String, callback: (Result<Unit>) -> Unit) {
Do we know if the `detach` will send the `presenceData` when it leaves the presence? We are expecting to see the `presenceData` when leaving the presence and some of the Subscriber SDK logic relies on that :thinking:

2021-11-15 13:56 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt
> +            DefaultAbly(connectionConfiguration!!, logHandler, singleThreadDispatcher),
Here you are using the same single thread dispatcher that the core publisher's events queue uses. This is quite dangerous as any blocking code in the `DefaultAbly` can cause the whole `Publisher` to block and in the worst-case scenario end in a deadlock :thinking: Is there any particular reason why you are reusing this dispatcher instead of creating a new one?

2021-11-15 13:56 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    val callbackDispatcher: CoroutineDispatcher
I think it should be a `private val` :wink:

2021-11-16 17:38 UTC, ikbalkaya commented
Superseded by https://github.com/ably/ably-asset-tracking-android/pull/513

2021-11-16 17:38 UTC, closed without merging