Make ably wrapper safer
ably/ably-asset-tracking-android pull request #513
Opened 2021-11-16 17:37 UTC by ikbalkaya

This pull request aims to improve Ably wrapper (for a little bit) by
* Using a ConcurrentHashMap for channels in order to make it  thread safe
* Moving unsubscription operations to detach success callback to maintain a single point for success.
* Reconnection if detach fails.

For now, reconnection happens with an empty listener. That is because it's solely to undo effect of presence.leave and registering a listener will highly complicate the situation. However it's still not completely safe as reconnection might also fail and thus the channel is in inconsistent state. I think we should aim to reduce the amount of state changing operations to 1 but it does not seem possible for now.

2021-11-18 10:38 UTC, KacperKluka requested changes
We're on a good way but we need to make a few adjustments :wink:

2021-11-18 10:38 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private val channels: ConcurrentHashMap<String, Channel> = ConcurrentHashMap()
I know that I've suggested using the `ConcurrentHashMap()` but after looking into [the docs](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html) and running a small test I'm starting to think that it's not the right tool for us :disappointed: 

In the class summary in the docs you can find that it is:
```
A hash table supporting full concurrency of retrievals and high expected concurrency for updates.
[...]
Retrieval operations (including get) generally do not block, so may overlap with update operations 
(including put and remove). Retrievals reflect the results of the most recently completed update 
operations holding upon their onset. (More formally, an update operation for a given key bears 
a happens-before relation with any (non-null) retrieval for that key reporting the updated value.)
```

I've checked and the `map.get()` and `map.put()` operations doesn't seem to be thread secure. In my test I've run this line of code `map["test_counter"] = map["test_counter"] + 1` in a multi-threaded fashion and there were races happening and the result was unpredictable. When I've replaced it with `map.compute("test_counter") { key, value -> value + 1 }` then there were no races and everything was looking good.

Given the above, I wonder if we will need to add some safety mechanisms by ourselves. Our main goal is to provide synchronized access to the `channels` map. We would like to both access and modify it in a secure way. The `ConcurrentHashMap` doesn't seem to serve this purpose. I'm a bit afraid that our only way would be to use `mutex`es or some other locks but we need to be careful with them. We probably don't want to block the whole `Ably` on a single operation but rather do this on a trackable basis :thinking: Let me know what you think about this :wink:

2021-11-19 10:17 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private val channels: ConcurrentHashMap<String, Channel> = ConcurrentHashMap()
There is another map called Synchronised map and I think read/writes are fully synchronised with that one with a performance drawback but I don't think we need a map with high performance
https://www.baeldung.com/java-synchronizedmap-vs-concurrenthashmap

2021-11-19 11:32 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
>                                  }
https://github.com/ably/ably-asset-tracking-android/pull/513/commits/428bb63a34c0156c00165669fe1d23ae908b9b15

2021-11-19 11:41 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private val channels: ConcurrentHashMap<String, Channel> = ConcurrentHashMap()
As you pointed out  `ConcurrentHashMap` is not completely thread safe as opposed to its name suggests. So we normally could use a mutex (or might have used an actor) to protect the map ourselves. However I think we are good to go with the synchronisedMap that Java collections framework gives us. It's basically going to do job for us and synchronise the underlying map to it. The only downside I see here is that we have to import a java framework. 
Change is here https://github.com/ably/ably-asset-tracking-android/pull/513/commits/7cc5255c6fcf90f81f5313668fbe0cdac15bb25e

2021-11-23 08:19 UTC, KacperKluka requested changes

2021-11-23 08:19 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                                    Gson().toJson(presenceData),
The Gson parsing part is not correct, it should be `gson.toJson(presenceData.toMessage())` :wink:

2021-11-23 08:27 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private val channels: ConcurrentHashMap<String, Channel> = ConcurrentHashMap()
So now with `SynchronizedMap` both accessing and modification of the `channels` map is multithread safe :+1: However, I think it doesn't make it much better than before :thinking: I mean that now we are sure there will be no races when looking into the `channels` map, but there still can be a case that one channel is being used by multiple threads at the same time. For example, thread A can get a channel, try to use it for sending but at the same time thread B can also get the channel and close it. 

I think that to make the Ably wrapper secure we need to make sure that each operation is atomic, meaning that if it starts then we should make sure no one will interrupt it while it's working. So there won't be a case like I've described above, that one thread is trying to send and at the same time, the channel it's using is being closed by another thread. WDYT? :wink:

2021-11-23 09:22 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private val channels: ConcurrentHashMap<String, Channel> = ConcurrentHashMap()
In this case I think there is a misunderstanding of the issue from my side. Reframing the issue for a more concrete understanding will do it. I think this would be a good suit after I do the refactoring work. What do you think?

2021-11-23 09:29 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private val channels: ConcurrentHashMap<String, Channel> = ConcurrentHashMap()
No worries, I think that my description of the issue could be better :sweat_smile:  Yes, we should wait for the refactor as the API of the `Ably` wrapper might change due to that :wink:

2022-01-12 14:10 UTC, KacperKluka commented
I've noticed that there is no comment on why this is in the draft state now, so I'll add it before I forget it :sweat_smile:. 
The reason behind this PR being a draft is that we want to wait for the event queue refactoring https://github.com/ably/ably-asset-tracking-android/pull/525 to be completed before moving on with this PR :wink:

2022-07-18 10:12 UTC, KacperKluka commented
We've decided on a call today that we will close this PR and carry on the conversation in its [corresponding issue](https://github.com/ably/ably-asset-tracking-android/issues/440)

2022-07-18 10:12 UTC, closed without merging