Add GitHub Packages installation instruction to the README
ably/ably-asset-tracking-android pull request #523
Opened 2021-11-19 13:37 UTC by KacperKluka

I've added the steps required to add AAT as a dependency in Gradle. It isn't as straightforward as one might think so it's great that we will have this information in our README :wink:

2021-11-19 14:05 UTC, AndyNicks approved these changes

2021-11-23 10:28 UTC, QuintinWillison requested changes
I've spotted a few small things that could be improved.

Also, in terms of your reference to use of a PAT - is this really the only way to do this? What about those who may need to get this working from CI/CD environment - perhaps using the `GITHUB_TOKEN` issued for use by a workflow? Even if you don't document _how_ to do that specifically, I think you could enhance this documentation with:

1. An indication that PAT is just one way of achieving this - perhaps the easiest for personal development
2. At least one link back to GitHub's documentation where the use of GitHub packages is covered in respect of auth

2021-11-23 10:28 UTC, QuintinWillison commented on README.md
> +#### GitHub Packages
Vertical white space, please - we need a blank line below this heading.

2021-11-23 10:28 UTC, QuintinWillison commented on README.md
> +To install the dependency you will first need to create a "Personal Access Token" in your GitHub account. The token must have the `read:packages` permission.
```suggestion
To install the dependency you will first need to create a "Personal Access Token" in your GitHub account. That token must have the `read:packages` permission.
```

2021-11-23 10:28 UTC, QuintinWillison commented on README.md
> +Then use your generated token to authenticate in the AAT GitHub Packages repository:
```suggestion
Then use your generated token to authenticate with the AAT GitHub Packages repository:
```

2021-11-23 10:28 UTC, QuintinWillison commented on README.md
> +```gradle
Vertical white space - please can you insert a blank line above this code fenced block.

2021-11-24 08:21 UTC, KacperKluka commented on README.md
> +```gradle
https://github.com/ably/ably-asset-tracking-android/pull/523/commits/8128cf2d374e40d3a50f3f968dba4df0f6d7ae53

2021-11-24 08:21 UTC, KacperKluka commented on README.md
> +#### GitHub Packages
https://github.com/ably/ably-asset-tracking-android/pull/523/commits/8128cf2d374e40d3a50f3f968dba4df0f6d7ae53

2021-11-24 08:21 UTC, KacperKluka commented on README.md
> +Then use your generated token to authenticate in the AAT GitHub Packages repository:
https://github.com/ably/ably-asset-tracking-android/pull/523/commits/a45961cd3ba1b37410c8daec8809e47d8a4981ab

2021-11-24 08:21 UTC, KacperKluka commented on README.md
> +To install the dependency you will first need to create a "Personal Access Token" in your GitHub account. The token must have the `read:packages` permission.
https://github.com/ably/ably-asset-tracking-android/pull/523/commits/a45961cd3ba1b37410c8daec8809e47d8a4981ab

2021-11-24 08:25 UTC, KacperKluka commented
@QuintinWillison thanks for the suggestion :bow: I've added the information that you can use both `GITHUB_TOKEN` and PAT to authenticate https://github.com/ably/ably-asset-tracking-android/pull/523/commits/635982ec33b6e36957e3a14f0c7bcb4f51e60f0c :wink:

2021-11-24 13:13 UTC, QuintinWillison approved these changes

2021-11-24 13:13 UTC, merged