Add trackable refactor trials
ably/ably-asset-tracking-android pull request #525
Opened 2021-11-24 12:03 UTC by ikbalkaya

Initial refactor Draft PR, Update this description later

2021-11-25 12:55 UTC, KacperKluka reviewed
For the sake of readability and keeping the scope of this PR as small as possible I'd like to ask you to revert the `Handler -> CallbackFunction` rename as this adds a lot of noise and makes it harder to notice the actual architectural changes :sweat_smile: Thanks :bow:

2021-11-26 12:22 UTC, ikbalkaya commented
> For the sake of readability and keeping the scope of this PR as small as possible I'd like to ask you to revert the `Handler -> CallbackFunction` rename as this adds a lot of noise and makes it harder to notice the actual architectural changes 😅 Thanks 🙇

That's done. Hopefully it made PR a bit simple to read 🙃

2021-11-30 09:12 UTC, KacperKluka requested changes
We're heading in a good direction :muscle: But there are 2 main issues (one minor and one major):
1) [minor] As this is the core of the SDKs we should document the classes and interfaces in the best possible way :grin: Please take a look in [this file](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt) for reference on how the docs look like in the other parts of the SDK :wink: 
2) [major] We should not block any core queue in the SDK. The current solution will block the `CorePublisher` until the worker (and all its subsequent workers) finish the work. This potentially can lead to delays in sending messages which we don't want. So we have to find another solution to connect the two queues until the refactoring is finished :thinking:

2021-11-30 09:12 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                    }
I wonder if it is safe to access the `properties` from inside of this `asyncWork` :thinking: I mean that the `asyncWork` is invoked in an async call and potentially the `properties` might have changed by that time. I think we should make it more secure in terms of creating the async work. Maybe when creating the `asyncWork` we could provide a copy of the `properties` that then could be safely used to read from in the asynchronous function start? :thinking: WDYT?

2021-12-01 09:35 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/EventWorkerQueue.kt
> +    private val publisherState: DefaultCorePublisher.Properties,
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/3d87333d650463a35a89b9ba5fb3fc2ee623de37

2021-12-01 09:44 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/AddTrackableResultHandler.kt
> +        return null
I did that to suppress IDE complaining about me not covering all cases as workResult is a wider type, we cannot cover all cases here. Nevertheless I removed it here .https://github.com/ably/ably-asset-tracking-android/pull/525/commits/5cf688fcd4453a393110e616087864389b57ad81. And actually it is better we leave IDE complaining about this as it might lead to a better design. Unfortunately I wasn't able to use generics to provide the narrow types for those concrete classes as it would lead to unchecked casts. I am open to other recommendations that would give us this.

2021-12-01 09:50 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/WorkResultHandlers.kt
> +}
Here https://github.com/ably/ably-asset-tracking-android/pull/525/commits/b08d0703111f79ddd965e3a24434cf20ad224e98. However I invite you to check the comment above.

2021-12-01 10:19 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                    }
That's a good point. As solution to this I think exposing the copy of whole properties is convenient, however exposing the whole state to an asyncwork may not be necessary. How about we only expose the copies of neccessary parameters for functions inside lambda for now. In this case `presenceData` I have made a commit here. https://github.com/ably/ably-asset-tracking-android/pull/525/commits/4abff37cb695d745f169b93f56a67a114e6bb11f.

2021-12-01 10:21 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +            properties.trackables.contains(trackable) -> {
Yes I realised this when writing tests for the class. I will fix it here too :)

2021-12-01 10:29 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +            properties.trackables.contains(trackable) -> {
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/4b206f56ea3d85470e5c0f25ce74b52d4b9db9ae

2021-12-01 11:05 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                )
https://github.com/ably/ably-asset-tracking-android/commit/4b206f56ea3d85470e5c0f25ce74b52d4b9db9ae

2021-12-01 11:06 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                    syncWorkResult = null,
https://github.com/ably/ably-asset-tracking-android/commit/4b206f56ea3d85470e5c0f25ce74b52d4b9db9ae

2021-12-01 11:26 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/CorePublisher.kt
> +                        )
I suppose we don't really need suspending functions here at all (maybe until we carry the channel to this class). Hence I'm going to remove all suspending functions. The only one will stay inside asyncwork block which should not block the queue

2021-12-01 11:29 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/CorePublisher.kt
> +                        )
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/4941f7edc01b0fc3bc8b0820bb8d48618a092fdc

2021-12-01 11:50 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/Worker.kt
> +    fun doWork(properties: DefaultCorePublisher.Properties): SyncAsyncResult
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/953bb2e54d199aab26f26c724030efd4d9084187

2021-12-01 12:02 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/WorkerQueue.kt
> +     * **/
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/9b7ea22024c66e2282972e8974111c5803efd1d4

2021-12-01 12:06 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/WorkerQueue.kt
> +     * **/
Not sure if it's Github but your comments seem to have dublicated

2021-12-01 12:06 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/WorkerQueue.kt
> +     * **/
And this

2021-12-01 12:10 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/WorkResultHandler.kt
> +     * @param [workResult] : [WorkResult] to be handled
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/2edff69a404aaf626e2c714d38e5b99f9dbb4a00

2021-12-01 12:45 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/WorkerQueue.kt
> +     * **/
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/66d22c10e62ac25b638098ad2490712ad5abe5ed

2021-12-06 08:47 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/WorkerQueue.kt
> +     * **/
If you simply add vertical space between your note and the `@param` it won't change anything :wink: That's how it looks like now:
![Screenshot from 2021-12-06 09-43-08](https://user-images.githubusercontent.com/62378170/144814996-10b5a08e-ff16-495a-8358-74e17bded63f.png)
There's the `:` at the start and your note at the end :wink: Your note should be placed before the `@param` annotation as everything after it is treaded as part of the parameter description.

2021-12-06 08:47 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/WorkerQueue.kt
> +     * **/
It looks like a duplicate, I'll resolve it :wink:

2021-12-06 08:51 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                )
Thanks for using the named parameter :bow: But the `return` is still there :wink: Let's either remove it here or add it to the rest of the `when` cases.

2021-12-06 09:53 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/WorkerQueue.kt
> +     * **/
I suppose I'm a documentation noob 😉  Here is the change https://github.com/ably/ably-asset-tracking-android/pull/525/commits/e34862eadf0227189b78b79a26a1af14aa4be496

2021-12-06 09:56 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> + * [asyncWork] is any work that is not immediately executed but returned to caller for it to execute later. It is a
This was fixed last week, I must have forgotten to put comment here. The commit should be here https://github.com/ably/ably-asset-tracking-android/pull/525/commits/66d22c10e62ac25b638098ad2490712ad5abe5ed

2021-12-06 09:59 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                )
oops https://github.com/ably/ably-asset-tracking-android/pull/525/commits/ffabff68de400b7b65ceaaf5abaf5866e35feaa2

2021-12-06 16:10 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/AddTrackableResultHandler.kt
> +        workResult: WorkResult,
As we chatted about this, that was my original intention and I reverted it because of the unchecked cast situation. Though I think it's a bit late for this change on this PR. I will make that change in another PR

2021-12-06 16:27 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +) : WorkResult()
This is an intentional design choice so that we have a common interface for work results whether they are synchronous, asynchronous or some combined results. In the case of `SyncAsyncResult` it is a combination and this combination is expressed by wrapping an optional result and an optional async work. 

`WorkResult` is the super type of any work result but `SyncAsyncResult` is the optional return type for doWork in `Worker` classes. 
  `val asyncWork: AsyncWork<WorkResult>? = null`
It is a more generic work result than the `SyncAsyncResult`. In the future the result of AsyncWork might change for a more concrete result of course but it's outside of scope of this PR.

2021-12-06 16:32 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/CorePublisher.kt
> +            val workerQueue = EventWorkerQueue(this@DefaultCorePublisher, properties, scope)
Good point. I have made the change here https://github.com/ably/ably-asset-tracking-android/pull/525/commits/6945fa102c9aa4a2d8eab5717c4a20d403504eb5 however I do not see a long life for this to stay here. It will likely end up being a dependency like all immortals 😄

2021-12-06 16:35 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/EventWorkerQueue.kt
> + * An implementation of [WorkerQueue] that executes incoming workers defined in [executeWorks] method. Please note
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/dedb1984e513f0adf53e97d6c9d45bd7e9dc81c2

2021-12-06 16:50 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/WorkResultHandler.kt
> +package com.ably.tracking.publisher.workerqueue
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/7184ca5d468d8e6b3a88ab0e7dc453c646ea4e80

2021-12-06 16:51 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +package com.ably.tracking.publisher.workerqueue
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/d1aa95519cb1ba17517a9ad524329f16b1dabb03

2021-12-07 08:51 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +) : WorkResult()
I like the fact that the `SyncAsyncResult` is a wrapper :+1: I'm just not convinced that it should extend the `WorkResult` class itself :wink: I thought that the `WorkResult` is a base class for worker results that require some `WorkResultHandler`s to handle them. The `SyncAsyncResult` is returned from all the workers and is always the same and therefore is always handled in the same way in the `WorkerQueue`.

I guess that I'm trying to ask what do we benefit from having the `SyncAsyncResult` as a subclass of the `WorkResult`? Because we're returning the `SyncAsyncResult` from workers (and not the abstract `WorkResult`) it makes me think that maybe it should simply be a wrapper/container object that isn't a part of the `WorkResult` hierarchy :thinking: WDYT? :wink:

2021-12-07 08:59 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/AddTrackableResultHandler.kt
> +        workResult: WorkResult,
You're right, this probably should be a separate PR :wink: Could you create an issue for that so we won't forget to do it? :wink:

2021-12-07 09:12 UTC, KacperKluka requested changes
Almost there :sweat_smile:

2021-12-07 09:12 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +typealias AsyncWork<T> = (suspend () -> T)
Two things:
1. This should be an `internal` type alias :wink: 
2. I think we can drop the generic type `T` from this and simply change it to an alias for a suspending function that returns a work result :wink: 
```suggestion
internal typealias AsyncWork = (suspend () -> WorkResult)
```

2021-12-07 09:28 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +) : WorkResult()
I think we might be chasing the wrong offender here 😄  Let me explain:
`WorkResult` was created especially to represent a work result of `doWork()`. So it is an essential part of the API. Later we discovered that our workers actually can do a sync work, return an optional sync result and another optional async work that can be processed in the background later. Therefore the offender seems to be the `Worker` interface itself. As we do not have any other type of workers (for now) our base type returns a `SyncAsyncResult` which is a `WorkResult`. 

Looks like we have another candidate for a generic interface here A `Worker<T:WorkResult>` would give us the ability to design any worker which would essentially return any type of `WorkResult`.

2021-12-07 09:30 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +) : WorkResult()
I will add an issue to address this in another PR

2021-12-07 09:41 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/AddTrackableResultHandler.kt
> +        workResult: WorkResult,
https://github.com/ably/ably-asset-tracking-android/issues/544

2021-12-07 09:49 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +) : WorkResult()
https://github.com/ably/ably-asset-tracking-android/issues/545

2021-12-07 10:07 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +typealias AsyncWork<T> = (suspend () -> T)
AsyncWork was initally designed to reference any suspending work and not referring to any of our works. However I think it's a good idea to narrow it to WorkResult as we try to narrow the type scopes in this API
https://github.com/ably/ably-asset-tracking-android/pull/525/commits/d379881e191630b3e691237e18c34978dbce6869 and https://github.com/ably/ably-asset-tracking-android/pull/525/commits/b285571e06adf538dcc2ecc5c32409926d51d00e

2021-12-07 13:53 UTC, KacperKluka approved these changes
Thank you for bearing with me during the review :bow: Now it all looks good :+1: But please wait with merging for now as we're planning a release soon :wink:

2021-12-10 14:12 UTC, KacperKluka reviewed
I'm revoking my approval only because this has changed to an integration branch and should be merged into the `main` branch only after the whole refactoring is complete :wink:

2022-01-19 19:06 UTC, QuintinWillison commented
I see that the work represented by this PR forms the foundations from which the current backlog of PRs from @KacperKluka stems (starting at https://github.com/ably/ably-asset-tracking-android/pull/581). For that reason, I'm going to mark this PR as Ready for Review as it's a pre-requisite.

2022-01-19 19:40 UTC, merged