Add trackable worker tests
ably/ably-asset-tracking-android pull request #529
Opened 2021-11-25 13:58 UTC by ikbalkaya

AddTrackableWorker tests and some refactoring / fake class creations to make tests easier. Update this description when this pull request is ready

2021-11-30 15:29 UTC, KacperKluka requested changes
Sorry for being so picky but this is a major change in the SDK and we need to be very careful with it :grin: Overall I love the fact that we will be finally able to test the domain logic in small chunks with the workers queue refactor :smile:

2021-11-30 15:29 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +    private val ably = FakeAbly(true)
Why are you using fakes instead of mocks? We could get rid of the `FakeXyz` classes and simply use the `mockk` library to both mock and verify the behaviour of each of the classes :wink:

2021-11-30 15:29 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherProperties.kt
> +internal interface PublisherProperties {
Creating an interface just to make the tests easier to write doesn't sound good :thinking: If something can't be tested without creating an interface then it's fine to do so, but in this situation I think that a better thing to do would be to add some test helpers that would create the required objects in the desired configuration :thinking: Especially that the `PublisherProperties` is just a container of objects, it does not hold any business logic that you might want to fake :wink:

2021-11-30 15:29 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/guards/DublicateTrackableGuard.kt
> +internal interface DuplicateTrackableGuard {
Same situation as with the `PublisherProperties` :thinking: Do we really need this interface and do we want to mock/fake the behaviour of this class? I guess that if the `DuplicateTrackableGuard` is well enough tested then it shouldn't be a problem to simply use it as it is in unit tests of some other classes, WDYT? :wink:

2021-12-01 17:58 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    suspend fun suspendingConnect(
Good idea. Here it is https://github.com/ably/ably-asset-tracking-android/pull/529/commits/6e85b5101259a594682ac67479eef691c3933bc4

2021-12-01 18:03 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/CorePublisher.kt
> +                                        )
https://github.com/ably/ably-asset-tracking-android/pull/529/commits/3417d6c58ec855c44dbab7eaeac1dd1ebba3f663

2021-12-01 18:07 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +    private val ably = FakeAbly(true)
Short answer is that I have not used mocks for faking behaviour before. I used them to verify some behaviour but not for faking them. I'll attempt to use mockk. Looks like you have already created an extension that I can use

2021-12-01 18:19 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherProperties.kt
> +internal interface PublisherProperties {
While  I am also sceptical on this instance whether we need this interface, tests can be used to expose some design flaws in code. Looking at this; 
https://en.wikipedia.org/wiki/Dependency_inversion_principle

Even in this particular instance this interface was introduced to help for testing, it is not only useful in that situation. I think any dependency that is injected to another class should have a common interface and not expose any implementation details.

2021-12-02 09:34 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/guards/DublicateTrackableGuard.kt
> +internal interface DuplicateTrackableGuard {
This was done for the same reason as above. However I think your point is valid in terms that it exposes some design flaw. So I'd say, if you don't think this should be interfaced, I'd say it then shouldn't be a dependency. So maybe duplicate trackable guarding is responsibility of the work queue which enqueues / processes the works. But I don't think it's in the scope of this PR

2021-12-02 09:53 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +    private val ably = FakeAbly(true)
Here is I replaced fake Ably with mockk Ably 😉

2021-12-08 13:40 UTC, KacperKluka requested changes
Looks good but we can make a few improvements :wink:

2021-12-08 13:40 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +        Assert.assertTrue(alreadyIn.handler == resultCallbackFunction)
We should be using `Assert.assertEquals` instead because this will give us more information when the assertion fails :wink:

2021-12-08 13:40 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +            result.asyncWork?.let {
Since you check if the `asyncWork` is not null I think we can safely use the `!!` operator to simplify this :wink:

2021-12-08 13:40 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +            result.asyncWork?.let {
Like above :wink:

2021-12-08 13:40 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +class AddTrackableWorkerTest {
Please add vertical spaces in all tests methods so the `given when then` comments have a vertical space before them, for example:
```
        // given
        val publisherProperties = FakeProperties(FakeDuplicateGuard(false))

        // when
        val result = worker.doWork(publisherProperties)

        // then
        Assert.assertNotNull(result.asyncWork)
```

2021-12-09 11:36 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/FakeProperties.kt
> +internal class FakeDuplicateGuard(private val currentlyAdding: Boolean) : DuplicateTrackableGuard {
I created an issue for this https://github.com/ably/ably-asset-tracking-android/issues/551

2021-12-09 11:37 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +    private val resultCallbackFunction = mockk<ResultHandler<StateFlow<TrackableState>>>()
I will address this in another PR. See https://github.com/ably/ably-asset-tracking-android/issues/551

2021-12-09 11:38 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +            result.asyncWork?.let {
Do you really think this is necessary?

2021-12-09 11:52 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +        Assert.assertTrue(alreadyIn.handler == resultCallbackFunction)
Fair enough https://github.com/ably/ably-asset-tracking-android/pull/529/commits/b9163eecc3e1e192fb71895a370fa60702de4c70

2021-12-09 11:55 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +class AddTrackableWorkerTest {
https://github.com/ably/ably-asset-tracking-android/pull/529/commits/8ceee9d5b50cf8429a556b71687e73698b2ae28b

2021-12-10 07:17 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +        Assert.assertTrue(alreadyIn.handler == resultCallbackFunction)
Thanks but there are still a few `assertTrue()` in your tests when they should be `assertEquals`, please change them too :wink: 
Also, I think that the order of the arguments should be inverted :thinking: In the `assertEquals` the first argument is the expected value and the second one is the actual one, so in this case, it should probably be `Assert.assertEquals(resultCallbackFunction, alreadyIn.handler)` because we expect to see `resultCallbackFunction` and the `alreadyIn.handler` is the thing that we receive. It is important because then you have clear and precise assertion error messages and you don't have to wonder what's actually wrong in the test :wink:

2021-12-10 07:20 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +            result.asyncWork?.let {
Yes, I think that clean and well-written tests are very important in maintaining a healthy codebase :wink: So we should aim to make them as good as our production code :grin: However, if this will cause you a lot of trouble due to the chain of PRs I'm fine with creating an issue for that and making the change later :wink:

2021-12-10 09:36 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +            result.asyncWork?.let {
Ah no, my objection is that I do not think it is a good idea to forcely unwrap an optional. Consider that we added !! operator and then later 
`Assert.assertNotNull(result.asyncWork)`
 is not needed and removed. Wouldn't you be left with a code that unwraps a potentially null value. Of course for this particular tests it's on the next line, but in any client situation I wouldn't use !! operator for an optional value.

2021-12-10 09:38 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +        Assert.assertTrue(alreadyIn.handler == resultCallbackFunction)
Thanks for your suggestions. I applied your suggestion to the place of comment. I will address others in a different PR.

2021-12-10 09:40 UTC, ikbalkaya commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorkerTest.kt
> +        Assert.assertTrue(alreadyIn.handler == resultCallbackFunction)
https://github.com/ably/ably-asset-tracking-android/issues/558

2021-12-10 14:08 UTC, KacperKluka approved these changes
LGTM :+1:

2021-12-15 09:14 UTC, merged