Connection for trackable created worker
ably/ably-asset-tracking-android pull request #537
Opened 2021-12-02 16:28 UTC by ikbalkaya

Worker implementation for ConnectionForTrackableCreatedEvent

Note to reviewers: Please review https://github.com/ably/ably-asset-tracking-android/pull/529 before this one

2021-12-08 14:25 UTC, KacperKluka requested changes
Some improvements are needed :wink:

2021-12-08 14:25 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/ConnectionCreatedResultHandler.kt
> +                )
This can be safely joined into one line without reaching the line break limit :wink: 
```kotlin
AddTrackableFailedEvent(workResult.trackable, workResult.handler, workResult.exception)
```

2021-12-08 14:25 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/ConnectionCreatedResultHandler.kt
> +                        )
I think that when we correct the `ably.disconnect()` suspending method signature then this whole `if` will become unnecessary and we will be able to simply pass forward the `result` from the `disconnect` here :wink:

2021-12-08 14:25 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +        val presenceUpdateListener: (presenceMessage: PresenceMessage) -> Unit
This is never used - perhaps we should remove it? :thinking:

2021-12-08 14:25 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +    internal data class PresenceSuccess(
I think we should be more verbose with names and rename it to `SubscribeToPresenceSuccess` :wink:

2021-12-08 14:25 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +    internal data class PresenceFail(
I think we should be more verbose and rename it to `SubscribeToPresenceFailed` :wink:

2021-12-08 14:25 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionCreatedWorker.kt
> +    private suspend fun subscribeToPresenceMessages(presenceData: PresenceData): ConnectionCreatedWorkResult {
Why it's here and not in the `Ably` interface? :thinking:

2021-12-08 14:25 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionCreatedWorker.kt
> +                }
I think that too much is happening here, instead of returning the `WorkResult` I'd suggest simply returning a success or failure and then using it to perform more actions. Thanks to this you'll be, for example, able to use suspending `disconnect` instead of the callback-based one :wink:

2021-12-08 14:30 UTC, KacperKluka commented
I've hoped to find another PR that would contain tests for this worker but it looks like there isn't one. Please add tests for this worker as a part of this PR :bow:

2021-12-09 12:02 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionCreatedWorker.kt
> +    private suspend fun subscribeToPresenceMessages(presenceData: PresenceData): ConnectionCreatedWorkResult {
I didn't want to pollute Ably interface with more suspending functions. Instead return a suspending result for the use case. Ably interface refactorings is not part of this refactoring work (I know I did one in one of previous PRs but I think it gets out of the scope). If you still think this should move to Ably, please add an issue and I'll adress it there

2021-12-09 12:12 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +    internal data class PresenceSuccess(
These are subclasses for ConnectionCreatedWorkResult and I think they do not need to be verbose as they are already scoped inside a particular result

2021-12-09 12:12 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +    internal data class PresenceFail(
As above

2021-12-09 13:36 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    suspend fun disconnect(trackableId: String, presenceData: PresenceData): Result<Boolean>
The original intention was to return whether the disconnect success or failed, but I see that those are already handled by Result class. I'll update

2021-12-09 13:41 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    suspend fun disconnect(trackableId: String, presenceData: PresenceData): Result<Boolean>
https://github.com/ably/ably-asset-tracking-android/pull/537/commits/646dd114c1682ef61caf7b3b1495e00fe40c6f88

2021-12-09 13:44 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/resulthandlers/ConnectionCreatedResultHandler.kt
> +                )
[I'm wondering  ](https://github.com/ably/ably-asset-tracking-android/pull/537/commits/9aad9b1309824fbbcb68583f08aec0226d0709cb)

2021-12-09 16:11 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +        val presenceUpdateListener: (presenceMessage: PresenceMessage) -> Unit
I added this for the future iteration of refactorings. Just like other callbacks we will probably end up dealing with this callback in a result handler. See CorePublisher class and see how ConnectionCreatedWorker is invoked

```
  workerQueue.execute(
                            ConnectionCreatedWorker(
                                event.trackable,
                                event.handler,
                                ably
                            ) { presenceMessage ->
                                enqueue(PresenceMessageEvent(event.trackable, presenceMessage))
                            }
                        )
```
`enqueue(PresenceMessageEvent(event.trackable, presenceMessage))
` 
will have to be handled from the corresponding work handler. However this refactoring will happen in the future iterations

2021-12-09 16:16 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionCreatedWorker.kt
> +                }
Good point 👍  However as in others I intentionally kept the async block as it's original implementation. I am going to add an issue to address this later

2021-12-09 16:18 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionCreatedWorker.kt
> +                }
https://github.com/ably/ably-asset-tracking-android/issues/554

2021-12-09 16:20 UTC, ikbalkaya commented
> I've hoped to find another PR that would contain tests for this worker but it looks like there isn't one. Please add tests for this worker as a part of this PR 🙇

I'm going to add test PRs for workers after refactoring for workers is complete.

2021-12-10 08:53 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +        val presenceUpdateListener: (presenceMessage: PresenceMessage) -> Unit
I think that we should follow the YAGNI rule and don't add stuff that will probably be used sometime in the future :wink: If we will need it then we can always add it in the future, if it's not needed now, then let's not add it :grin:

2021-12-10 09:18 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +    internal data class PresenceSuccess(
Yes, they are scoped, but what does exactly `PresenceSuccess` mean in the scope of `ConnectionCreated`? :thinking: Does it mean that the presence was successfully joined? Or that we've successfully subscribed to the presence channel? This is not obvious, therefore, I still think that the name should change to something that would explicitly tell you what has happened :wink:

2021-12-10 09:26 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionCreatedWorker.kt
> +    private suspend fun subscribeToPresenceMessages(presenceData: PresenceData): ConnectionCreatedWorkResult {
You're right, it makes sense to not add anything to the Ably interface as this feels a bit outside of the scope of the refactoring :wink:

2021-12-10 09:41 UTC, KacperKluka requested changes
Almost there :wink:

2021-12-10 09:41 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                    continuation.resume(Result.failure(exception))
Because you've changed the error path behaviour the documentation of this function needs to be updated :wink: We should remove this line as it is no longer valid:
```
@throws ConnectionException if something goes wrong during disconnect.
```

2021-12-10 09:41 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionCreatedWorker.kt
> +                    }
Both branches of this `if / else` execute the same code (I wonder why lint isn't complaining about it :thinking:). Therefore, we don't need this `if` and this can be simplified :wink: 
```kotlin
ConnectionCreatedWorkResult.RemovalRequested(trackable, handler, result)
```

2021-12-10 10:03 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +        val presenceUpdateListener: (presenceMessage: PresenceMessage) -> Unit
Well. As far as I know YAGNI means "you aren't gonna need it" as I tried to explain in comment above "you are gonna need it". I make this intent explicit for now so that it is not forgotten later.

2021-12-10 10:11 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> +    internal data class PresenceSuccess(
All cases were extracted from the original code as use case results. In this case you can for example read it as
"I have tried to create a connection, and the presence succeeded as a result of this work, what should I do?" 
You can ask the same question for other 2 cases. As they are both part of`ConnectionCreatedWorkResult` it is only possible to use them on those particular cases

2021-12-10 14:23 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                    continuation.resume(Result.failure(exception))
https://github.com/ably/ably-asset-tracking-android/pull/537/commits/0c45da6151272009587fbc8f9f4eee3a16c3863b

2021-12-10 14:27 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionCreatedWorker.kt
> +                    }
Very interesting of IDE is not complaining about this. Change is here https://github.com/ably/ably-asset-tracking-android/pull/537/commits/0c45da6151272009587fbc8f9f4eee3a16c3863b

2021-12-10 14:58 UTC, KacperKluka approved these changes
LGTM :+1:

2021-12-15 09:15 UTC, merged