Presence message worker
ably/ably-asset-tracking-android pull request #540
Opened 2021-12-03 11:46 UTC by ikbalkaya

PresenceMessageEvent refactoring implementation
Please review https://github.com/ably/ably-asset-tracking-android/pull/539 before this one

2021-12-08 16:09 UTC, KacperKluka requested changes
Looks good but there are a few things to improve :wink: Also there are no tests, please add tests for the worker as a part of this PR :wink:

2021-12-08 16:09 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/EventWorkerQueue.kt
> +            }
I would choose some other scope function for this use-case, as the `apply` does not seem very idiomatic here :thinking: According to the [docs](https://kotlinlang.org/docs/scope-functions.html#apply) the `apply` function is mostly used for object configuration and here we're doing something different :wink: 

I'd either use the `let` function but with a named parameter, something like this
```suggestion
            it.event.let { event ->
                when (event) {
                    is Request<*> -> corePublisher.request(event)
                    is AdhocEvent -> corePublisher.enqueue(event)
                }
            }
```

or we can use `run` which will still use `this` as the event
```suggestion
            it.event.run {
                when (this) {
                    is Request<*> -> corePublisher.request(this)
                    is AdhocEvent -> corePublisher.enqueue(this)
                }
            }
```

2021-12-08 16:09 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/PresenceMessageWorker.kt
> +    private val corePublisher: CorePublisher
I don't think that we should be referencing the `CorePublisher` from any worker :thinking: Wasn't the main reason behind having `WorkResultHandlers` to decouple the workers from the queue? If I understand it correctly we should create a work result handler for this worker and use the core publisher in that result handler :wink:

2021-12-09 17:21 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/EventWorkerQueue.kt
> +            }
In order to avoid conflicts from merge, I will address stylistic changes on next set of PRs. I will link the issue here when I create it

2021-12-09 17:27 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/PresenceMessageWorker.kt
> +    private val corePublisher: CorePublisher
I remember chatting about this. Core publisher is here only because it is implementing the functions that are used in this particular worker. As everything was inside the same class before refactoring, an easy way would be to define the functions as CorePublisher and use them on worker. However these functions will become part of another interface (Eg. SubscriptionEditor) and is going to replace CorePublisher as dependency. But is not part of this PR. I shall create an issue for this.

2021-12-09 17:33 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/PresenceMessageWorker.kt
> +    private val corePublisher: CorePublisher
https://github.com/ably/ably-asset-tracking-android/issues/555

2021-12-09 17:35 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/EventWorkerQueue.kt
> +            }
https://github.com/ably/ably-asset-tracking-android/issues/556

2021-12-10 14:19 UTC, KacperKluka approved these changes
LGTM :+1:

2021-12-15 10:11 UTC, merged