Clear the route when the destination is reached
ably/ably-asset-tracking-android pull request #548
Opened 2021-12-07 13:37 UTC by KacperKluka

I've added an arrival observer which notifies us when we reach the destination. Then we clear the route in order to improve the Mapbox behaviour after reaching the destination.

2021-12-07 14:16 UTC, AndyNicks approved these changes

2021-12-07 15:19 UTC, ikbalkaya requested changes
Looks good overall 😎 Just one clarification needed (not necessarily a code change request)

2021-12-07 15:19 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/Mapbox.kt
> +    private var arrivalObserver: ArrivalObserver? = null
I can see that this is being initialised in init block. Shouldn't this be a non-optional val if I'm not missing something 🤔

2021-12-08 06:40 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/Mapbox.kt
> +    private var arrivalObserver: ArrivalObserver? = null
Good idea :+1: However, I couldn't use `val` for some reason so I've changed it to a non-null `lateinit var` :wink: https://github.com/ably/ably-asset-tracking-android/pull/548/commits/94d35cafa3b40665d5ad3e597c52c64f20eef8f0

2021-12-08 09:16 UTC, ikbalkaya approved these changes

2021-12-10 05:46 UTC, QuintinWillison approved these changes

2021-12-10 05:46 UTC, merged