Integration: Refactor event queue
ably/ably-asset-tracking-android pull request #607
Opened 2022-01-27 07:36 UTC by KacperKluka

This is an aggregate PR of the whole event queue refactoring work. All refactoring PRs should be landed on `integration/refactor-event-queue` branch. After all the work is done, this PR will be landed on the `main` branch and the refactoring work will be completed.
Additionally, this PR will show the state of tests for the refactoring work.

2022-03-24 09:21 UTC, ikbalkaya requested changes
I was only able to skim read and spot some areas of improvement as I was involved in this. For now I requested some changes for some functions that can be shortened in smaller chunks to increase readability.

2022-03-24 09:21 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionReadyWorker.kt
> +        return SyncAsyncResult()
I think this function is a bit long. Could it be splitted to smaller chunks?

2022-03-24 09:21 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionReadyWorker.kt
> +        return SyncAsyncResult()
I think this function is a bit long. Could it be splitted to smaller chunks?

2022-03-24 09:21 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/DisconnectSuccessWorker.kt
> +        callbackFunction(Result.success(Unit))
I think this function also can be split in smaller functions.

2022-03-24 09:21 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/DisconnectSuccessWorker.kt
> +        callbackFunction(Result.success(Unit))
I think this function also can be split in smaller functions.

2022-03-24 15:04 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/DisconnectSuccessWorker.kt
> +        callbackFunction(Result.success(Unit))
Good idea :+1: https://github.com/ably/ably-asset-tracking-android/pull/607/commits/ac6e25cee47556aa01fa1a04cc14c70000d25653

2022-03-24 15:05 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionReadyWorker.kt
> +        return SyncAsyncResult()
This looks like a duplicate of https://github.com/ably/ably-asset-tracking-android/pull/607#discussion_r834080395 :wink:

2022-03-24 15:05 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/DisconnectSuccessWorker.kt
> +        callbackFunction(Result.success(Unit))
This looks like a duplicate of https://github.com/ably/ably-asset-tracking-android/pull/607#discussion_r834082234 :wink:

2022-03-24 15:55 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/ConnectionReadyWorker.kt
> +        return SyncAsyncResult()
I realised that happening when I submitted my review, I think there is a bug with Github 🙄

2022-03-24 15:56 UTC, ikbalkaya approved these changes
As long as it passes integration tests looks good to me

2022-03-28 11:26 UTC, QuintinWillison approved these changes
I'm happy to merge this in its current state, despite minor observations (which could be handled in a subsequent PR in order not to block this one).

I've not reviewed line by line, so definitely a lighter weight review from me.

I notice use of the `Impl` suffix on at least one class. Generally I would prefer to avoid abbreviations if possible, plus I don't feel that - as a suffix, in this form - it's that friendly to maintainers. Could you have considered a prefix like `Default`? [I wrote [a similar comment elsewhere](https://github.com/ably/kafka-connect-ably/pull/50#discussion_r835094816) last week]

2022-03-28 11:26 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> + * @param syncWorkResult : Any work result that has resulted from synchronous work. This work result is expected to be
Minor thing but `@param` syntax differs from the argument below. I would change to:

```suggestion
 * @param syncWorkResult any work result that has resulted from synchronous work. This work result is expected to be
```

2022-03-28 11:26 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/EventWorkerQueue.kt
> + * that this is currently an acting bridge between the older event queue (CorePublisher) . All methods must be called
I'm not sure I understand this sentence:

> Please not that this is currently an acting bridge between the older event queue (CorePublisher).

Use of 'between' would suggest there also needs to be an 'and' - e.g. a bridge _between_ A _and_ B. 😕

2022-03-29 05:54 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/EventWorkerQueue.kt
> + * that this is currently an acting bridge between the older event queue (CorePublisher) . All methods must be called
This is an old description from the time when we were using both the old EventQueue and the new WorkerQueue, I've forgotten to update it, thanks for catching it :grin: I've updated the docs and renamed the class as this has no longer anything in common with `Event`s :wink: https://github.com/ably/ably-asset-tracking-android/pull/607/commits/020ec36779fab45ac9edbc312a5d148062bb85a4

2022-03-29 05:58 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/results/WorkResult.kt
> + * @param syncWorkResult : Any work result that has resulted from synchronous work. This work result is expected to be
I've gone through the docs and aligned their style to match it project-wise https://github.com/ably/ably-asset-tracking-android/pull/607/commits/afb536853418b5bfdbdf9691ebe0b0737536adda

2022-03-29 05:59 UTC, KacperKluka commented
@QuintinWillison thanks for the suggestion, I've replaced the `Impl` suffix with `Default` prefix in classes :wink: https://github.com/ably/ably-asset-tracking-android/pull/607/commits/aaca9be261cbd8f416b049e8e16d46b26f209c00

2022-03-31 09:40 UTC, QuintinWillison approved these changes

2022-03-31 11:41 UTC, merged