Add animations module with location animators
ably/ably-asset-tracking-android pull request #645
Opened 2022-02-21 16:22 UTC by KacperKluka

I've created a new module that is meant to be released as a maven package. This module will contain all animation related code that will make it easier to have a good subscriber UI/UX out of the box. For now, I've moved there the animation related code that was previously in the subscriber example app.

2022-02-21 16:23 UTC, AndyNicks approved these changes

2022-02-22 11:03 UTC, ikbalkaya approved these changes
Looks good to me 👍

2022-02-22 11:52 UTC, QuintinWillison requested changes
The name `animation` feels too specific for where I reckon this module might end up going. I would like to suggest:

- rename `animation/` to `ui-sdk/` (module folder)
- rename module root package from `com.ably.tracking.animation` to `com.ably.tracking.ui`
- move all of your current API surface to package `com.ably.tracking.ui.animation`

I also wonder about the `Position` data class... I've not looked for lack of time available to me in this moment, but can't that be in `core-sdk/`? 🤔

2022-02-22 12:00 UTC, ikurek approved these changes

2022-02-22 12:13 UTC, QuintinWillison commented on animation/src/main/java/com/ably/tracking/animation/LocationAnimator.kt
> +        expectedIntervalBetweenLocationUpdatesInMilliseconds: Long,
My preference has always been to include trailing commas in any language that supports this, as it makes future Git diffs much cleaner. The tools can catch up, or be configured. 😉

2022-02-22 12:19 UTC, KacperKluka commented on animation/src/main/java/com/ably/tracking/animation/LocationAnimator.kt
> +    val cameraPositionsFlow: SharedFlow<Position>
Thanks, for some reason I've forgotten that `SharedFlow` is a subtype of the `Flow` :sweat_smile: https://github.com/ably/ably-asset-tracking-android/pull/645/commits/bbd5d333692f9b3833f349c69a5630dfe626ea1b

2022-02-22 12:20 UTC, KacperKluka commented on animation/src/main/java/com/ably/tracking/animation/LocationAnimator.kt
> +        expectedIntervalBetweenLocationUpdatesInMilliseconds: Long,
We have not yet experienced any issues with trailing commas so I will leave it as it is but thanks for the information, I didn't know that :grin:

2022-02-22 12:25 UTC, KacperKluka commented
@QuintinWillison I've renamed the module to `ui-sdk` https://github.com/ably/ably-asset-tracking-android/pull/645/commits/e40154bfe43c33263a50d6cda4aece0f2df73fba and also moved the animation classes to the `ui.animation` package https://github.com/ably/ably-asset-tracking-android/pull/645/commits/f45ee6e28de965d17a4f1b99829cfa9d22c0178c

Regarding the `Position` class, it is a plain Kotlin class with primitive values but it is only used in the `LocationAnimator` that's why I have left it there :wink:

2022-02-22 13:32 UTC, QuintinWillison requested changes

2022-02-22 13:32 UTC, QuintinWillison commented on ui-sdk/build.gradle
> +    implementation project(':subscribing-sdk')
Sorry, I should have spotted this in my first-pass review of this... why is this here?

```
ably-asset-tracking-android % cd ui-sdk
ui-sdk % git grep -i subscriber
src/main/java/com/ably/tracking/ui/animation/LocationAnimator.kt: * Extension for the [com.ably.tracking.subscriber.Subscriber] that enables smooth location updates animation.
src/main/java/com/ably/tracking/ui/animation/LocationAnimator.kt:     * This should be called each time a new location update is received from the [com.ably.tracking.subscriber.Subscriber].
src/main/java/com/ably/tracking/ui/animation/LocationAnimator.kt:     * @param locationUpdate The newest location update received from the Subscriber SDK.
```

This is an unnecessary dependency. If anything, I would have assumed you would need an API/interface dependency on `':core-sdk'` for `LocationUpdate`. 🤔 

I can clearly see that you are referencing `Subscriber` in the comments my `grep` revealed, but that should not then require you to make it an implementation dependency because the code shows that not to be true.

2022-02-22 13:45 UTC, KacperKluka commented on ui-sdk/build.gradle
> +    implementation project(':subscribing-sdk')
Since this module is meant to be an extension for the `subscirber-sdk` module it felt like a good choice to make it dependent on the subscriber module :thinking: But from the technical point of view we can replace it with the `core-sdk` :wink:

2022-02-22 13:47 UTC, QuintinWillison commented on ui-sdk/build.gradle
> +    implementation project(':subscribing-sdk')
Let's stick to the concrete. Please change this. Thanks.

2022-02-22 14:04 UTC, KacperKluka commented on ui-sdk/build.gradle
> +    implementation project(':subscribing-sdk')
https://github.com/ably/ably-asset-tracking-android/pull/645/commits/d9c96a0f80c603edb2a77a5d54b084c3f7b16ca3

2022-02-22 15:11 UTC, QuintinWillison approved these changes

2022-02-22 15:21 UTC, merged