Improve add trackable process
ably/ably-asset-tracking-android pull request #664
Opened 2022-04-04 15:12 UTC by KacperKluka

Previously, the add operation was failing if there was an error when subscribing to presence messages (after successfully entering the presence).
Now, the add operation won't fail but will return a new state which indicates that the trackable is online but is not used optimally (due to lack of presence data). In the meantime the SDK will listen for the channel state changes and will try to resubscribe to presence data each time the channel becomes online. If it succeeds in subscribing to presence the state of the trackable will be updated to notify that it is now using all of its potential.

2022-04-06 08:18 UTC, ikbalkaya requested changes
Not a very detailed review, but it looks good, except for a naming suggestion

2022-04-06 08:18 UTC, ikbalkaya commented on core-sdk/src/main/java/com/ably/tracking/ConfigurationModels.kt
> +    object OnlineNonOptimal : TrackableState()
I think this name should change to something else. `NonOptiomal` immediately sounds like to me, that it's working but somehow with low frequency of data etc. How about `OnlineNotActive` or `OnlineNonReceiving`?

2022-04-06 09:07 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConfigurationModels.kt
> +    object OnlineNonOptimal : TrackableState()
That's a good suggestion, thanks :bow: How about being very explicit and changing it to `OnlineNotSubscribed`? :thinking: @AndyNicks @ikbalkaya WDYT

2022-04-11 13:35 UTC, QuintinWillison requested changes
I've had a fairly brief skim through (for lack of time) and it all looks sensible to me... just a need, as identified by @ikbalkaya, to perhaps rename that state.

2022-04-11 13:35 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConfigurationModels.kt
> +     * Trackable state is [OnlineNonOptimal] when it's being actively tracked but is neither able to detect nor receive data from subscribers.
I'm not sure that the use of the word 'neither' is correct here, as my understanding is that this state is seen when transitioning from offline to online, therefore transitory in nature also.

2022-04-11 13:35 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/ConfigurationModels.kt
> +    object OnlineNonOptimal : TrackableState()
Perhaps we don't try to overload 'online' anymore and instead go for a single word that represents what it's doing in this transitory state - I'm thinking perhaps either `Publishing` or `Presenting`.

Then I would update the commentary for the `Online` state to make it clear that it includes everything expected of `Presenting`.

I also think it might be worth documenting the possible state transitions, perhaps by indicate on each state's commentary whether it's final and, if not, what state(s) could follow it.

2022-04-11 14:31 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConfigurationModels.kt
> +    object OnlineNonOptimal : TrackableState()
I like the `Publishing` name as it describes exactly what we`re doing - we are publishing this trackable's locations, nothing more, nothing less :wink:
Here I've renamed the state https://github.com/ably/ably-asset-tracking-android/pull/664/commits/6ba46df352155c8bb1c8cba1ad2c465b09dca0f3 and here I've updated the docs https://github.com/ably/ably-asset-tracking-android/pull/664/commits/eae1f34149040989a02ceb47ec6e5cb2ef7f4b48

2022-04-11 14:32 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/ConfigurationModels.kt
> +     * Trackable state is [OnlineNonOptimal] when it's being actively tracked but is neither able to detect nor receive data from subscribers.
I've changed the docs to make them clearer https://github.com/ably/ably-asset-tracking-android/pull/664/commits/eae1f34149040989a02ceb47ec6e5cb2ef7f4b48 :wink:

2022-04-12 10:30 UTC, QuintinWillison approved these changes

2022-04-12 10:43 UTC, ikbalkaya approved these changes

2022-04-12 11:36 UTC, merged