Handle connection resume exception
ably/ably-asset-tracking-android pull request #665
Opened 2022-04-05 13:31 UTC by KacperKluka

From time to time we might get the "Connection resume failed" exception from `ably-android` due to the fact that a new connection was established. Because of that, all messages that we were trying to send using the old connection will receive the error. This should not be propagated immediately to the SDK users and it should be handled on the AAT side.

Therefore, I've wrapped all the Ably SDK calls that might throw this exception in a method that will retry those calls if a "connection resume failed" error is received. https://github.com/ably/ably-asset-tracking-android/pull/665/commits/cfadcae2fb075295f72d9fe769498ffd31a1235a
To do that in a clean way I had to first refactor the `Ably` wrapper to use coroutines (but still have the callback-based API). https://github.com/ably/ably-asset-tracking-android/pull/665/commits/72ce740fdbbd0330813f44d1a3e668113bae9022

2022-04-11 13:53 UTC, QuintinWillison requested changes

2022-04-11 13:53 UTC, QuintinWillison commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private suspend fun retryIfChannelConnectionFails(channel: Channel, operation: suspend () -> Unit) {
A couple of thoughts here:

1. Perhaps this method could have a better name, including resume, so perhaps `retryChannelOperationIfConnectionResumeFails`.
2. Could you reduce potential for the `operation` to be doing something different (e.g. on a different channel) by making the `operation` take the `Channel` as an argument? Looking at the upstream call sites, you're having to pass the `channel` variable twice - once to this first arg and then for a second time within the `operation` implementation.

2022-04-11 14:55 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private suspend fun retryIfChannelConnectionFails(channel: Channel, operation: suspend () -> Unit) {
Good suggestions :+1: 
1. https://github.com/ably/ably-asset-tracking-android/pull/665/commits/02542e29ea43b97d28e1124b9afdf9efb04d535c
2. https://github.com/ably/ably-asset-tracking-android/pull/665/commits/0336a82cb3aa465563fbb9ce1210901ba21ab177

2022-04-12 10:32 UTC, QuintinWillison approved these changes

2022-04-12 10:42 UTC, ikbalkaya approved these changes
Warning, light review! LGTM

2022-04-12 12:11 UTC, merged