Add location updates validation
ably/ably-asset-tracking-android pull request #692
Opened 2022-06-17 11:29 UTC by KacperKluka

It turns out that the gson is not very secure and can break Kotlin's null safety. I guess that's because it uses the reflection mechanism from Java and therefore is allowed to put a null in a non-nullable field. Because of that, I've added a few checks that make sure that the objects we receive are in a valid format. If that's not the case we are simply logging it to the log handler.

2022-06-27 10:49 UTC, ikbalkaya requested changes
Minor comments

2022-06-27 10:49 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        logHandler?.w("Could not deserialize a raw location update message")
This is probably a product question but I am wondering how risky this would be just to log a warning

2022-06-27 10:49 UTC, ikbalkaya commented on common/src/main/java/com/ably/tracking/common/GsonHelpers.kt
> +fun <T> Gson.fromJsonOrNull(json: String?, classOfT: Class<T>): T? =
As this function already returns an optional type, I think 'OrNull' part could be dropped.

2022-06-27 11:48 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/GsonHelpers.kt
> +fun <T> Gson.fromJsonOrNull(json: String?, classOfT: Class<T>): T? =
The problem is that there's already a function called `fromJson()` that does not return a null but throws an exception in case anything goes wrong :sweat_smile: That's why I've added the `OrNull` suffix to this method :wink:

2022-07-01 05:54 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        logHandler?.w("Could not deserialize a raw location update message")
After a discussion on an [internal channel](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1656498487121459?thread_ts=1656331319.885969&cid=C01EPJENRD0) we've decided that an invalid message is a protocol error and should change the trackable state to `Failed`. I'll adjust this PR accordingly :wink:

2022-07-21 09:33 UTC, KacperKluka commented
Changed to draft as we have to wait for an infrastructure for assigning error codes to complete this PR.

2022-07-22 15:06 UTC, KacperKluka commented
The [error code](https://github.com/ably/ably-asset-tracking-common/tree/main/specification#error-codes) is ready so we can continue the work.

2022-08-02 07:44 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        logHandler?.w("Could not deserialize a raw location update message")
https://github.com/ably/ably-asset-tracking-android/pull/692/commits/58cab833d4a88c94d2c98d419ca3a681be7a1379

2022-08-02 08:06 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        logHandler?.w("Could not deserialize a raw location update message")
I've also added a test that checks the failure of the subscriber channel :wink: https://github.com/ably/ably-asset-tracking-android/pull/692/commits/992b1bd47053e0877003104bfc6bcdc836c7f13c

2022-08-03 12:12 UTC, davyskiba approved these changes
LGTM

2022-08-04 07:55 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +            if (isRawLocation) message.getRawLocationUpdate(gson) else message.getEnhancedLocationUpdate(gson)
I generally prefer to use `{}` as well but here I treat this `if(a) x else y` as a ternary operator `a ? x : y` and would prefer to keep it in one line, would that be okay with you :wink:

2022-08-04 10:47 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +            logHandler?.e("Could not deserialize ${if (isRawLocation) "raw" else "enhanced"} location update message")
Good idea :+1: https://github.com/ably/ably-asset-tracking-android/pull/692/commits/1de5741f8114495b3c880733ac20d30bce4dc048

2022-08-04 12:28 UTC, davyskiba approved these changes

2022-08-04 15:27 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        logHandler?.w("Could not deserialize a raw location update message")
Because Ikbal is away and we have to merge this PR I'm going to resolve this conversation. Please feel free to let me know if you are not happy with the PR and would like to add some changes, I'll add them in a separate PR :bow:

2022-08-04 15:35 UTC, KacperKluka commented
I'm going to use my admin powers to merge this PR despite the change requests. However, those requests seem to be fixed so I hope it is okay. Let me know if you feel otherwise and we'll work on that in another PR :wink:

2022-08-04 15:35 UTC, merged