Replace @JvmSynthetic with a custom type alias annotation
ably/ably-asset-tracking-android pull request #716
Opened 2022-07-15 08:44 UTC by KacperKluka

The `@JvmSynthetic` annotation is not very descriptive and does not explain why we are using it. That's why we've introduced a type alias for it, to change its name and make it more meaningful.

2022-07-15 12:37 UTC, QuintinWillison requested changes
Regarding the `typealias` duplication, I think we need to halt this work for now, as I think to do this properly there's work to be done outside of this repository.

2022-07-15 12:37 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +private typealias KotlinOnly = JvmSynthetic
I think we should aim to do this properly, which may mean another project/module to be the canonical root for these annotations.

I'm thinking along the lines of a new repository for "Ably Kotlin Common", with the aspiration that we will be using it soon enough for `ably-java` also.

2022-07-15 12:49 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +private typealias KotlinOnly = JvmSynthetic
Good idea, I didn't like that duplication as well :sweat_smile: Would it be okay to put it in a separate module in the AAT project for now?

2022-07-19 12:04 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +private typealias KotlinOnly = JvmSynthetic
I would rather create a new repository for it. Let's discuss in Slack the naming and then I shall share it here.

2022-12-06 14:05 UTC, ikbalkaya commented
This will be addressed elsewhere https://github.com/ably/ably-asset-tracking-android/issues/711

2022-12-06 14:05 UTC, closed without merging