Add documentation about location animator flows
ably/ably-asset-tracking-android pull request #725
Opened 2022-08-04 11:39 UTC by KacperKluka

I added information about the frequency of updates from the flows from `CoreLocationAnimator`. Additionally, I added information about optional animator configuration.

2022-08-04 12:32 UTC, davyskiba approved these changes
LGTM

2022-08-04 13:34 UTC, owenpearson requested changes

2022-08-04 13:34 UTC, owenpearson commented on UPDATING.md
> +- `animationStepsBetweenCameraUpdates` - How often should the camera updates be sent. Setting a higher value might improve UX but if it's too big it can lead to map marker moving out of the screen.
```suggestion
- `animationStepsBetweenCameraUpdates` - How often should the camera updates be sent. Setting a higher value might improve UX but, if set too high, may cause the map marker to move out of the screen.
```

Also, I think "How often should the camera updates be sent" is vague. Judging by the name 'animationStepsBetweenCameraUpdate' I would assume that this is the number of animation steps the location animator will send between each camera update, however, judging by this description it sounds like it's actually the frequency of the camera updates. If it's the latter we should make it clear what the units are, ie if I set it to `1` does that mean 1 update per second?

2022-08-04 13:34 UTC, owenpearson commented on UPDATING.md
> +- `intentionalAnimationDelayInMilliseconds` - A constant delay added to the animation duration. It helps to smooth out movement when we receive a location update later than we've expected.
```suggestion
- `intentionalAnimationDelayInMilliseconds` - A constant delay added to the animation duration. This helps to smooth out movement when a location update is received later than expected due to network conditions.
```

2022-08-04 13:34 UTC, owenpearson commented on UPDATING.md
> +You can add optional configuration options during `CoreLocationAnimator` creation:
```suggestion
The `CoreLocationAnimator` class takes the following configuration options:
```

2022-08-04 13:34 UTC, owenpearson commented on UPDATING.md
> +- `intentionalAnimationDelayInMilliseconds` - A constant delay added to the animation duration. It helps to smooth out movement when we receive a location update later than we've expected.
Should we also include the default values for both of these options?

2022-08-04 13:34 UTC, owenpearson commented on UPDATING.md
> +The map marker flow emits 60 positions per second, so you should simply update marker's position each time the flow emits a new position.
```suggestion
The map marker flow emits 60 positions per second, so you should simply update the marker's position each time the flow emits a new position.
```

2022-08-04 13:37 UTC, KacperKluka commented on UPDATING.md
> +- `intentionalAnimationDelayInMilliseconds` - A constant delay added to the animation duration. It helps to smooth out movement when we receive a location update later than we've expected.
I was wondering about it but if we do, then each time we change those values in the code we will also have to remember to update them here (and I think we will most likely forget to do that :sweat_smile: ) WDYT? :wink:

2022-08-04 15:11 UTC, KacperKluka commented on UPDATING.md
> +- `animationStepsBetweenCameraUpdates` - How often should the camera updates be sent. Setting a higher value might improve UX but if it's too big it can lead to map marker moving out of the screen.
Good idea, let me know if now it is more explicit :wink: https://github.com/ably/ably-asset-tracking-android/pull/725/commits/8be9a59fd100e3071515e84de4048d37d6279253

2022-08-04 15:12 UTC, owenpearson commented on UPDATING.md
> +- `intentionalAnimationDelayInMilliseconds` - A constant delay added to the animation duration. It helps to smooth out movement when we receive a location update later than we've expected.
I did consider that when I was writing my comment and I think it's a valid point, but if I was a developer reading this documentation for the first time I would definitely want to know what the default values were. Maybe we could add comments next to the defaults values in the code just to remind developers that if we change them we also need to update the docs?

2022-08-04 15:14 UTC, owenpearson requested changes

2022-08-04 15:14 UTC, owenpearson commented on UPDATING.md
> +  One step is created for each location from a location update, so this can be thought of as amount of locations between camera updates.
```suggestion
  One step is created for each location from a location update, so this can be thought of as the number of locations between camera updates.
```

Looks much better 😄  just one small additional suggestion

2022-08-04 15:25 UTC, KacperKluka commented on UPDATING.md
> +  One step is created for each location from a location update, so this can be thought of as amount of locations between camera updates.
Fixed as a part of https://github.com/ably/ably-asset-tracking-android/pull/725/commits/45a3511993f21cd0baaf1d818fe87f359dc6e9f7 :grin:

2022-08-04 15:25 UTC, KacperKluka commented on UPDATING.md
> +- `intentionalAnimationDelayInMilliseconds` - A constant delay added to the animation duration. It helps to smooth out movement when we receive a location update later than we've expected.
Good idea :+1: https://github.com/ably/ably-asset-tracking-android/pull/725/commits/45a3511993f21cd0baaf1d818fe87f359dc6e9f7

2022-08-05 10:37 UTC, owenpearson approved these changes
LGTM 👍

2022-08-05 10:43 UTC, merged