Update builder examples for publisher and subscriber in the README
ably/ably-asset-tracking-android pull request #750
Opened 2022-09-01 07:56 UTC by KacperKluka

I've updated the examples of creating publisher and subscriber in our README.

2022-09-01 08:05 UTC, tbedford approved these changes

2022-09-01 15:18 UTC, QuintinWillison requested changes
A couple of small suggests to make it really clear for the app developer where they still need to inject their own code.

2022-09-01 15:18 UTC, QuintinWillison commented on README.md
> +        // log the message to internal or external loggers
```suggestion
        // TODO: log the message to internal or external loggers
```

2022-09-01 15:18 UTC, QuintinWillison commented on README.md
> +          // log the message to internal or external loggers
```suggestion
          // TODO: log the message to internal or external loggers
```

2022-09-01 15:18 UTC, QuintinWillison commented on README.md
> +            // create the notification for location updates background service
```suggestion
            // TODO: create the notification for location updates background service
```

2022-09-02 10:43 UTC, QuintinWillison approved these changes

2022-09-02 10:55 UTC, merged