Subscriber queue
ably/ably-asset-tracking-android pull request #763
Opened 2022-09-26 10:30 UTC by davyskiba

Introducing `WorkerQueue` to the subscriber SDK. Resolves #660

2022-09-26 10:31 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/CoreSubscriber.kt
> +internal interface SubscriberStateManipulator {
I'm not sure if this is the best name for this interface, any ideas?

2022-09-28 13:56 UTC, KacperKluka requested changes
I've spotted a few things 😉 Also please add unit tests for the workers that will check whether they are implemented correctly 🙇

2022-09-28 13:56 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StartConnectionWorker.kt
> +            subscriberStateManipulator.updateTrackableState(properties)
The same as above, when you use the properties (either modify or access or pass to another function) you have to be on the worker queue thread. So please move this line out of the `doAsyncWork` block. 😉

2022-09-28 13:56 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StartConnectionWorker.kt
> +                properties.presenceData,
We should not access the `properties` in the `doAsyncWork` block. Instead you should make a snapshot of the data you need from the properties and use this instead. For reference look at a [similar implementation in the publisher SDK](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt#L35). 😉

2022-09-28 13:56 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StopConnectionWorker.kt
> +        // We're using [runBlocking] on purpose as we want to block the whole publisher when it's stopping.
Copy paste typo 😉 
```suggestion
        // We're using [runBlocking] on purpose as we want to block the whole subscriber when it's stopping.
```

2022-09-28 13:56 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/UpdatePublisherPresenceWorker.kt
> +                    subscriberStateManipulator.updatePublisherResolutionInformation(presenceMessage.data)
Maybe let's replace those three methods with an `onPublisherEnter()` method? 🤔

2022-09-28 13:56 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/SubscribeForPresenceMessagesWorker.kt
> +                ably.disconnect(trackableId, properties.presenceData)
I've noticed that's how it was done in the old event queue implementation but it's wrong 🤔 We should not access the `properties` from outside the worker queue thread. But I guess since that's how it worked before we could leave it like that. But please create an issue for fixing it in the future, the fix would probably be creation of a new worker that would copy the current presence data and call this async disconnect method. 😉

2022-09-28 15:23 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/WorkerQueue.kt
> +            doAsyncWork = { block -> scope.launch { block() } },
88e440e7de18b5af056a0694b6c36b54517e832b

2022-09-28 15:23 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StopConnectionWorker.kt
> +        // We're using [runBlocking] on purpose as we want to block the whole publisher when it's stopping.
8d77da4dd7ebddb9e979f1d26c9b233f07b5ca0b

2022-09-28 15:23 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/Worker.kt
> +    )
9cd63f11c788cf4460441d5e3e759d3f90700d66

2022-09-28 15:23 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/Worker.kt
> +internal abstract class CallbackWorker(protected val callbackFunction: ResultCallbackFunction<Unit>) :
9cd63f11c788cf4460441d5e3e759d3f90700d66

2022-09-28 15:24 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StartConnectionWorker.kt
> +                properties.presenceData,
6a29a916880dda70e8244d43764faae7b06a7a53

2022-09-28 15:24 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StartConnectionWorker.kt
> +            subscriberStateManipulator.updateTrackableState(properties)
6a29a916880dda70e8244d43764faae7b06a7a53

2022-09-28 15:24 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/ChangeResolutionWorker.kt
> +            properties.presenceData = properties.presenceData.copy(resolution = resolution)
6a29a916880dda70e8244d43764faae7b06a7a53

2022-09-28 15:24 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/CoreSubscriber.kt
> +internal interface SubscriberStateManipulator {
I think it's better :) a2d4b27fdd336958ff29cba6f2100be17be4d02c

2022-09-30 10:33 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/CoreSubscriber.kt
> +    private val properties = Properties(initialResolution)
25a19f2f165cbee90161594437e6dba13b05fc81

2022-09-30 10:53 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/SubscribeForPresenceMessagesWorker.kt
> +                ably.disconnect(trackableId, properties.presenceData)
How about extracting it to a separate worker?
https://github.com/ably/ably-asset-tracking-android/compare/subscriberQueue...disconnectWorker

2022-10-03 09:27 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/SubscribeForPresenceMessagesWorker.kt
> +                ably.disconnect(trackableId, properties.presenceData)
It looks great, is it in this PR or somewhere else?

2022-10-03 10:33 UTC, KacperKluka approved these changes
LGTM 👍

2022-10-03 16:00 UTC, davyskiba commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/SubscribeForPresenceMessagesWorker.kt
> +                ably.disconnect(trackableId, properties.presenceData)
Just merged it into this PR 
30741a1c228b521f5a66144508e2dc3b0ae08d81

2022-10-03 16:20 UTC, merged