Start and stop the Ably connection manually depending on the number of added trackables
ably/ably-asset-tracking-android pull request #778
Opened 2022-10-13 11:54 UTC by KacperKluka

Another approach to the start/stop Ably connection issue, this time using the worker queue architecture to achieve this. Requirements:

- The connection should be stopped when the publisher is created (hence the `autoConnect = false` is used in the `Ably` wrapper)
- When the first trackable is added the connection should be started
- When the last trackable is removed the connection should be stopped

I've made sure that no trackables are being added when the Ably connection is starting or stopping by delaying the add worker if a connection change is happening at the moment.

2022-10-13 12:26 UTC, KacperKluka commented
Converting to draft as I've forgotten to make changes in the Subscriber SDK

2022-10-14 16:35 UTC, QuintinWillison requested changes
I have been having a bit of a think about the growing collection of `Boolean` fields in `PublisherProperties`. You already had `isStopped` but you're now adding `isConnectingToAbly` and `isStoppingAbly`. I think they're clearly pretty interrelated, so I wonder whether it might be better to perhaps introduce an enum so that you can only have one field which can ever be in one of a few expected states? The code is a little hard to reason about at the moment - for example, I worry about a state where `isConnectingToAbly` and `isStoppingAbly` both end up `true` at the same time. The compiler cannot stop this happening. The only protection is that the mutations of the properties instance are consistent across all parts of the codebase that have access to it, which is a maintainability risk. 🤔

2022-10-14 16:35 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                    properties.isConnectingToAbly = true
I find this property mutation curious and I'm not sure why it would be here. Can you explain? Or perhaps add some commentary to the code? It's just, given what's above it, it just smells wrong if you know what I mean. 🤔

2022-10-14 16:35 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +private const val WORK_DELAY_IN_MILLISECONDS = 200L
This value is clearly a little arbitrary. Could it be worth expanding the commentary here to explain:

- why this value was chosen
- what "connection manipulation" means
- what happens if we wait, the work is re-queued, and then we find that connection manipulation is still ongoing... I _think_ we'll keep retrying, but it's not 100% clear to me from just reading the code that this is the case (i.e. we'll keep retrying at a rate of approximately 5Hz)

2022-10-15 12:20 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                    properties.isConnectingToAbly = true
When we have no trackables the connection to Ably is closed, therefore, when we add the first trackable we have to start the connection. Previously this property was set to `true` because we wanted to let other workers know that we're currently connecting to Ably so they should wait until that's complete before attempting any Ably-related work (like adding another trackable). Now, instead of this boolean property we have a state value which hopefully will be more meaningful https://github.com/ably/ably-asset-tracking-android/pull/778/commits/878781a0d402e1e4fd0cc1ae55553fb88284b181 😉

2022-10-15 12:29 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +private const val WORK_DELAY_IN_MILLISECONDS = 200L
> why this value was chosen

I have to admit I just randomly chosen that value 😅 Now I wonder if repeating the operation 5 times per second isn't too often 🤔 It all depends on the actual time required to start the connection which depends on things like network connection. WDYT? Maybe it would be better to increase the delay to 500ms or even 1s? 🤔 

> what "connection manipulation" means

It means starting or stopping the connection and now I see that I've made this vague without a good reason 🤦‍♂️ I'll ammend the comment and make it explicit 👍 https://github.com/ably/ably-asset-tracking-android/pull/778/commits/1f2d78bd2edb85c6d24f2c7198be057ff197624f

> what happens if we wait, the work is re-queued, and then we find that connection manipulation is still ongoing... I think we'll keep retrying, but it's not 100% clear to me from just reading the code that this is the case (i.e. we'll keep retrying at a rate of approximately 5Hz)

You're right, I've added this info to the docs 🙇 https://github.com/ably/ably-asset-tracking-android/pull/778/commits/1f2d78bd2edb85c6d24f2c7198be057ff197624f

2022-10-19 16:20 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableFailedWorker.kt
> +            properties.state = if (isConnectedToAbly) PublisherState.CONNECTED else PublisherState.IDLE
We have to do it here because changing the `properties` have to be made from the main queue thread 😉

2022-10-19 16:34 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                if (properties.state == PublisherState.CONNECTING || properties.state == PublisherState.DISCONNECTING) {
https://github.com/ably/ably-asset-tracking-android/pull/778/commits/34574992c9cc5230c9a5670c7e55ef91d26f7086

2022-10-19 16:34 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +                        if (isAddingTheFirstTrackable) {
https://github.com/ably/ably-asset-tracking-android/pull/778/commits/aeb7d4bed50a2543806e271773d059a4e69614ea

2022-10-19 16:35 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +     * If the connection is already failed it throws a [ConnectionException].
Good point 👍  https://github.com/ably/ably-asset-tracking-android/pull/778/commits/b1a9c108208632d212e54d5fa1f1c6a5322d6a56

2022-10-19 16:35 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/CorePublisher.kt
> +                if (field != PublisherState.STOPPED) {
That's a good idea 👍 https://github.com/ably/ably-asset-tracking-android/pull/778/commits/df1289d36eb8d92efe9871ff339fff2d0d28784d

2022-10-20 11:27 UTC, davyskiba approved these changes

2022-10-20 13:43 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +private const val WORK_DELAY_IN_MILLISECONDS = 200L
@KacperKluka Perhaps you can add an issue to look at this again later, with the intention of improving the algorithm (if possible). Feel free to resolve this conversation on my behalf once you've created that issue. Thanks.

2022-10-20 13:43 UTC, QuintinWillison approved these changes

2022-10-20 13:48 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableWorker.kt
> +private const val WORK_DELAY_IN_MILLISECONDS = 200L
Here's the issue 😉 https://github.com/ably/ably-asset-tracking-android/issues/783

2022-10-20 14:11 UTC, merged