Feature/error proof wrapper
ably/ably-asset-tracking-android pull request #782
Opened 2022-10-18 12:57 UTC by davyskiba

This PR takes care of further error proofing Ably wrapper:

1. dropped our own channels list to avoid  potential multithreading issues in favor of using a channels list held by Ably-java 2d1bd5f48a35c011232d14c5f2e187f512dcaf86
2. reordered calls inside `failChannel` so that the listeners have a chance to get notified and deleted removing the failed channel because we can reuse it and reconnect to it 83ffe9612a4788d94f7a6208e9f3288424fa4fc9
3. ~~altered the `disconnect` method so it can no longer fail - kept `leavePresence` and moved all other clean-up calls outside to the `finally` block as they cannot fail. If I understand ably-java doc correctly, we should be using `ably.channels.release` instead of detaching the channel manually, and currently, this method eats all exceptions.~~ 91f122249fab0db874f32c595766e05837e0cbfe

2022-10-19 14:19 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> -                        channels[trackableId] = channel
Previously we only considered a channel to be active and added it to our channels list when it succeeded in `enterChannelPresence()` operation. Now it looks like after the `channels.get()` is called (from a few lines above) the channel will be considered active and available for other operations (such as subscribing to it). This will happen also when the enter presence operation fails as in the `catch` blocks we only call the callback and we do not release the channel that was created by the `channels.get()` call, am I right? 🤔

2022-10-19 14:19 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        leavePresence(channelToRemove, presenceData)
What will happen if this fails and throws an exception? Why do you consider a channel that has not left its presence as successfully closed? 🤔 Will Ably leave the presence of a channel automatically when the channel is released? 🤔

2022-10-20 11:46 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> -                        channels[trackableId] = channel
Right! I've missed this, should I add `channels.remove` to the catch block? 🤔

2022-10-20 11:53 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> -                        channels[trackableId] = channel
I think we should remove the channel when connecting to it fails, so the `remove` or even `release` would be a right choice here 🤔

2022-10-20 12:10 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        leavePresence(channelToRemove, presenceData)
If it fails, we log the exception and retry once. I'll probably add a catch here too 🤔 

I've assumed that Ably has to have some sort of auto-leave mechanism for cases when the connection is cut off, but haven't confirmed it yet - will try to confirm it.
If I understand correctly, leaving presence is actually notifying the channel that we are leaving by sending a message. I thought that if sending a message fails twice, we're already in some partially disconnected/failed state, and I'm not sure if we should keep the channel open 🤔

2022-10-21 08:44 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        leavePresence(channelToRemove, presenceData)
Just checked on the demo apps using the dev console - publisher presence was removed in roughly 40 seconds after entering airplane mode on the device

2022-10-24 10:28 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> -                        channels[trackableId] = channel
739dfefcbb1ab0c4c2f8dbdec49b004654771a38

2022-10-24 13:43 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        leavePresence(channelToRemove, presenceData)
After discussion and deeper testing reverted this change in f8da7f1b6cffcb4a7497b460dada70fd2f4b8b2e

2022-10-26 09:13 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        leavePresence(channelToRemove, presenceData)
I think you've meant https://github.com/ably/ably-asset-tracking-android/pull/782/commits/a70b6f35be5f4a0119e3fb05975bb17866b9d33c and I'm resolving this conversation 😉

2022-10-26 10:12 UTC, KacperKluka reviewed
Looks good 👍 Just one question 😉

2022-10-26 10:12 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        // Once a channel enters failed state we can reattach it again, so we're not removing the reference
Will this reattach happen? If yes then when? I'm asking because the idea was that when we receive a malformed location update message then the transport (channel) should be failed and stop operating 🤔

2022-10-27 13:38 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        // Once a channel enters failed state we can reattach it again, so we're not removing the reference
During connect, we attempt to reattach a failed channel

2022-10-28 09:54 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        // Once a channel enters failed state we can reattach it again, so we're not removing the reference
But the `connect()` method starts with this
```kotlin
if (!ably.channels.containsKey(trackableId)) {
  // start connection
}
```

so if I'm right since the failed channel is not removed from the channels, then this won't be executed, right? Therefore, the channel will never reattach? 😅

2022-10-28 11:16 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        // Once a channel enters failed state we can reattach it again, so we're not removing the reference
Right 😅 I think we could add checking channel state to this condition? 🤔

2022-10-28 11:55 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        // Once a channel enters failed state we can reattach it again, so we're not removing the reference
We could but this makes me wonder, is that worth the effort? 😅 I mean why don't we simply remove (release) the channel when it fails? 🤔

2022-11-02 12:30 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        // Once a channel enters failed state we can reattach it again, so we're not removing the reference
6272de5e94df24841f36bf1d1ab621778db59a59

2022-11-08 08:47 UTC, KacperKluka approved these changes
LGTM 👍

2022-11-14 10:07 UTC, KacperKluka requested changes
Almost there 😅

2022-11-14 10:07 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        if (!ably.channels.containsKey(trackableId)) {
I think you should either use `trackableId.toChannelName()` or switch to the `getChannelIfExists()` method 🤔

2022-11-14 10:07 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +            ably.channels.keySet().forEach { trackableId ->
I believe that now the `keySet()` will return channel names instead of trackable IDs 🤔 So the variable name should be changed to `channelName` and we should check if it still can be used later in the `disconnect()` method below 🤔

2022-11-14 10:07 UTC, KacperKluka commented on integration-testing-app/src/androidTest/java/com/ably/tracking/tests/PublisherAndSubscriberTests.kt
>          }
I wonder whether the "cleanup" code will be called if one of the assertions from the "then" section fail? I guess we should always stop the subscriber, even if the assertions fail. So maybe let's try a `try/catch/finally` approach to achieve this here? 🤔

2022-11-14 10:14 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        ably.channels.release(channel.name)
We could do that as a part of the cleanup, but aren't we relying on them to move the trackable to an offline state?

2022-11-14 11:06 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        if (!ably.channels.containsKey(trackableId)) {
99a6d64ca78b6e10db3c0ca41f1db7ec271b6d5d

2022-11-14 11:07 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +            ably.channels.keySet().forEach { trackableId ->
awesome you caught this <3 294406b4185e63ec760d692c2b005d2f9f14ba41

2022-11-14 11:07 UTC, davyskiba commented on integration-testing-app/src/androidTest/java/com/ably/tracking/tests/PublisherAndSubscriberTests.kt
>          }
I think this would be getting too complicated 🤔 
reordered it this way 3f883ca8516033bb9164a7e9c362d598c44f26aa

2022-11-14 12:43 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        if (!ably.channels.containsKey(trackableId)) {
aand  here a8cdb3ed1697e688c53019d74a4a1cb76800efc6

2022-11-14 15:53 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        ably.channels.release(channel.name)
Okay, so why are we calling the `channel.off()` in the [other case](https://github.com/ably/ably-asset-tracking-android/pull/782/files#diff-baf8644244d013d061c0a0d0bc74b8f8156783cc77f7796198b11172cccb9d38R442) when we are failing the channel? 🤔

2022-11-14 16:38 UTC, KacperKluka requested changes

2022-11-14 16:38 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private suspend fun safeDisconnectChannel(channelToRemove: Channel, presenceData: PresenceData) =
Why is this called `safe`? What's unsafe with the regular `disconnectChannel`? 🤔

2022-11-15 08:32 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private suspend fun safeDisconnectChannel(channelToRemove: Channel, presenceData: PresenceData) =
This one will never throw an exception

2022-11-15 09:43 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +        ably.channels.release(channel.name)
Right, sorry, I've got everything mixed up 🙈 If we add `channel.off()` here we won't receive the "channel went offline" event because it's triggered by the `ably.channels.release()` call 👍 So everything is fine here 👌

2022-11-15 10:03 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private suspend fun safeDisconnectChannel(channelToRemove: Channel, presenceData: PresenceData) =
Do you think we could change the name that would explain this method's behaviour in more detail? 🤔 Something like `disconnectChannelIgnoringErrors()` or perhaps `tryDisconnectChannel()` or something else? 🤔

2022-11-15 11:58 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private suspend fun safeDisconnectChannel(channelToRemove: Channel, presenceData: PresenceData) =
renamed to `tryDisconnectChannel` https://github.com/ably/ably-asset-tracking-android/pull/782/commits/cade10d817ea3988bc8863c716bdfeacf4116e9d

2022-11-15 12:44 UTC, merged