Add token based auth to the Java API
ably/ably-asset-tracking-android pull request #787
Opened 2022-10-24 10:25 UTC by KacperKluka

I've created an `AuthenticationFacade` static class that is responsible for creating all authentication options in the Java API. I've moved the `basic` auth to it and added `tokenRequest` and `jwt` auths that instead of coroutines use the `CompletableFuture`s.

2022-10-25 10:19 UTC, davyskiba approved these changes

2022-10-26 10:46 UTC, KacperKluka commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            .connection(new ConnectionConfiguration(AuthenticationFacade.basic("CLIENT_ID", "API_KEY"), null))
Those tests are just a way to show how the Java API can be used and not necessarily to test anything 😅 Therefore, I'd just leave it here as this should be easier for the users to see all options in one place 😉 WDYT?

2022-10-26 10:51 UTC, KacperKluka commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            return new TokenRequest() {
Good idea 👍 https://github.com/ably/ably-asset-tracking-android/pull/787/commits/ad9329d723cfd9d09cd3d07c5e4bf6362504e354

2022-10-31 12:48 UTC, QuintinWillison requested changes

2022-10-31 12:48 UTC, QuintinWillison commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            // get the token from you auth servers
```suggestion
            // get the token from your auth servers
```

2022-10-31 12:48 UTC, QuintinWillison commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            return "created-jwt";
This could perhaps be clearer to indicate that it's a placeholder - even the dashes, at the moment, make it look more 'official'. Perhaps:

```suggestion
            return "DUMMY PLACEHOLDER: RETURN JWT FROM AUTH SERVER HERE";
```

2022-10-31 12:48 UTC, QuintinWillison commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            // get the token from you auth servers
```suggestion
            // get the token from your auth servers
```

2022-10-31 12:48 UTC, QuintinWillison commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/EmptyTokenRequest.java
> +public class EmptyTokenRequest implements TokenRequest {
Perhaps some commentary on this class to explain that the values returned from the implemented getters are intentionally placeholder dummies, in order to demo how to implement this interface.

2022-10-31 12:48 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
Does this mean we're presenting a breaking change for those using this SDK's core interfaces from Java?

Or might we classify this as a bug fix? (i.e. based on the argument that this method should never have been visible to Java users) 🤔

2022-10-31 12:48 UTC, QuintinWillison commented on core-sdk-java/src/main/java/com/ably/tracking/java/AuthenticationFacade.kt
> +interface TokenRequestFunction {
I'm not sure I like the `Function` suffix on this interface and `JwtFunction` below.

I wonder if `Creator` or `CreationHandler` would be more classically Java idiomatic.

(while I recognise that this is a functional interface, we're not [annotating it with `FunctionalInterface`](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html) - a [known issue](https://github.com/ably/ably-asset-tracking-android/issues/173) in this codebase... so mixing in 'function' into interface names feels a bit strange)

2022-11-02 11:41 UTC, KacperKluka commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            return "created-jwt";
https://github.com/ably/ably-asset-tracking-android/pull/787/commits/ccf94c19bd2fbb41201098788c608b5ba2411b57

2022-11-02 11:41 UTC, KacperKluka commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/EmptyTokenRequest.java
> +public class EmptyTokenRequest implements TokenRequest {
https://github.com/ably/ably-asset-tracking-android/pull/787/commits/ccf94c19bd2fbb41201098788c608b5ba2411b57

2022-11-02 11:42 UTC, KacperKluka commented on core-sdk-java/src/main/java/com/ably/tracking/java/AuthenticationFacade.kt
> +interface TokenRequestFunction {
I didn't like the `Function` as well but no better name came to my mind 😅 I like the `Creator` one, it's much better 🙇 https://github.com/ably/ably-asset-tracking-android/pull/787/commits/aea31d514b5aab64e25169f7e16515652083f0a4

2022-11-02 11:46 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
Yes, that's a breaking change 🤔 Technically we don't need to do this because the `basic` auth can safely work without a facade, but I thought that it would be better if all auth options in Java are created from the same `AuthenticationFacade` object 🤔 So it's not a "bug", this is more of a consistency thing. WDYT we should do with it then? 🤔

2022-11-08 11:07 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
@mikelee638 - while this is technically a breaking change (therefore should be held off until the next `major` version bump), at the same time we're presenting in this pull request an enhancement that expands the scope of auth support... I'm also not aware of any customers who've been in contact that are using this from Java. So, perhaps we _can_ release this in a `minor` version bump. What do you think?

2022-11-08 11:41 UTC, mikelee638 commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
@QuintinWillison Yes, seems fine to me.

2022-11-08 11:46 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +        @JvmSynthetic
Thanks. I've added the `enhancement` label to both this PR and the linked issue.

2022-11-09 11:27 UTC, merged