Add the location animator to the Java API
ably/ably-asset-tracking-android pull request #791
Opened 2022-10-25 10:18 UTC by KacperKluka

I've created a facade for Java users that should allow them to use the `LocationAnimator` with all its features. In the process I've added a new module `ui-sdk-java` which will be published as an artefact.

2022-10-25 13:29 UTC, davyskiba approved these changes

2022-10-25 13:29 UTC, davyskiba commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            locationAnimatorFacade.animateLocationUpdate(locationUpdate, locationUpdateInterval.get());
What should we do with that in a real-world case?

2022-10-26 10:52 UTC, KacperKluka commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            locationAnimatorFacade.animateLocationUpdate(locationUpdate, locationUpdateInterval.get());
What do you mean? This more or less shows how to use it in an app 😉

2022-10-31 12:21 UTC, QuintinWillison requested changes
Perhaps this PR should also include an addition to the root readme? (i.e. [here](https://github.com/ably/ably-asset-tracking-android#java-users))

2022-10-31 12:21 UTC, QuintinWillison commented on ui-sdk-java/.gitignore
> +/build
I think you can remove this file entirely, as this folder is already covered [here](https://github.com/ably/ably-asset-tracking-android/blob/8016b0fb97be04332d0c4d39404933a944d444fc/.gitignore#L6) in the root Git ignore file.

2022-10-31 12:21 UTC, QuintinWillison commented on ui-sdk-java/build.gradle
> +dependencies {
I noticed [this](https://github.com/ably/ably-asset-tracking-android/blob/8016b0fb97be04332d0c4d39404933a944d444fc/subscribing-sdk-java/build.gradle#L13) in the Gradle file for the subscribing module/project. Is that not needed here?

2022-11-02 09:59 UTC, KacperKluka commented on ui-sdk-java/build.gradle
> +dependencies {
The dependency you mentioned is used when we want to convert coroutines to `CompletableFuture`s 😉 Here we only convert `Flow`s to listeners which does not require this library 👍

2022-11-02 10:03 UTC, KacperKluka commented on ui-sdk-java/.gitignore
> +/build
You're right 👍 https://github.com/ably/ably-asset-tracking-android/pull/791/commits/09a8a03ff0434c27d104f4556b1020fad9ec6e54

2022-11-02 12:07 UTC, davyskiba commented on subscribing-java-testing/src/test/java/com/ably/tracking/example/javasubscriber/UsageExamples.java
> +            locationAnimatorFacade.animateLocationUpdate(locationUpdate, locationUpdateInterval.get());
Sorry, looks like I've misclicked the line 😞 
I've meant to ask what exactly would "handle" mean in the following lines. Maybe we could be make more specific comment as an example?
```
// handle new map marker position
// handle new camera position
```

2022-11-08 11:18 UTC, QuintinWillison approved these changes

2022-11-10 13:21 UTC, merged