Allow to specify the remainPresentFor Ably transport parameter
ably/ably-asset-tracking-android pull request #806
Opened 2022-11-16 13:05 UTC by KacperKluka

Added the `remainPresentFor` parameter to the Ably configuration as according to the (docs)[https://ably.com/docs/realtime/presence#unstable-connections].

2022-11-16 16:54 UTC, QuintinWillison requested changes

2022-11-16 16:54 UTC, QuintinWillison commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +     * The minimum value can be 1 second (1000 milliseconds). If not set the default value will be used.
The last sentence, in its current form, is probably just adding confusion - I'm left asking the question "What is the default value?". It would be useful to make it clearer where that default is defined, probably with a link to [the documentation](https://ably.com/docs/realtime/presence#unstable-connections).

Also, given the fact that this SDK does nothing to enforce the 1000ms minimum, it's perhaps not appropriate to explicitly document that in the API as this is a service-side minimum... perhaps better left explained by the canonical documentation link I mentioned in my opening paragraph to this comment. 🤔

2022-11-17 10:47 UTC, davyskiba approved these changes
Code looks good :)

2022-11-17 10:50 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/connection/ConnectionConfigurationModels.kt
> +     * The minimum value can be 1 second (1000 milliseconds). If not set the default value will be used.
Good idea 👍 https://github.com/ably/ably-asset-tracking-android/pull/806/commits/d9c298660e7742120a563ae14c95b5fc948af9b2

2022-11-23 11:34 UTC, QuintinWillison approved these changes

2022-11-23 11:57 UTC, merged