Fix memory leak issue
ably/ably-asset-tracking-android pull request #812
Opened 2022-11-17 16:16 UTC by ikbalkaya

This is a fix for https://github.com/ably/ably-asset-tracking-android/issues/810

- Wraps the android context in a weak reference, so that is not kept after the service is destroyed
- Unsets the static mapbox notification provider when DefaultMapbox destroys MapboxNavigation
- Tidies up references to the PublisherService and various coroutines when it is shut down
- Passes a clone of the publisher service's notification to mapbox to prevent it keeping the service in scope when the publisher is shutdown (this has been raised with mapbox separately)
- Removes all ably connection listeners when the connection is shut down, to avoid the service leaking through these
- Removes all the ably channel state listeners when a channel state is disconnected, prior to being released, to work around an ably-java issue that leaks them

Closes #810 
Closes #815

2022-11-25 12:00 UTC, davyskiba requested changes

2022-11-25 12:00 UTC, davyskiba commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt
> +    val androidContext: WeakReference<Context>? = null,
I think this change is not necessary, as we're passing a strong reference to Mapbox anyway 🤔

2022-11-25 12:00 UTC, davyskiba commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt
> +    inner class Binder(private val weakService: WeakReference<PublisherService>) : android.os.Binder() {
As stated [in the kotlin doc](https://kotlinlang.org/docs/nested-classes.html#inner-classes), inner classes strongly reference outer classes as a language feature. To break this connection, we need to remove inner keyword on Binder class

2022-11-25 12:31 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt
> +    val androidContext: WeakReference<Context>? = null,
I think you are right here - In this case I suppose the issue stays with Mapbox. I will ping them 👍

2022-11-28 16:57 UTC, ikbalkaya commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt
> +    inner class Binder(private val weakService: WeakReference<PublisherService>) : android.os.Binder() {
This is no longer an inner class 9e03c14b39f0da189bbf48587dfa7cdade967541

2022-11-29 09:10 UTC, KacperKluka requested changes
Looks good, just a few suggestions 😉

2022-11-30 08:47 UTC, davyskiba commented on publishing-example-app/build.gradle
> +    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.10'
Since this is so easy to add, maybe it is worth adding to the subscriber example too?

2023-02-14 16:11 UTC, AndyTWF commented on publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt
> +        Log.d("onDestroy", "onDestroy: ")
Have done this

2023-02-14 16:12 UTC, AndyTWF commented on publishing-example-app/build.gradle
> +    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.10'
Done this

2023-02-15 11:20 UTC, davyskiba commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt
> +        fun stubOffAll() {
Do we need both `stubOffAll` and `stubOffNoListeners`?

2023-02-15 11:20 UTC, davyskiba commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt
>      fun stubConnectionOff() {
Do we need control over which overload is stubbed? In some other part we've been mocking all under in function

2023-02-15 11:29 UTC, AndyTWF commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt
> +        fun stubOffAll() {
Removed the latter!

2023-02-15 12:18 UTC, lawrence-forooghian commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt
> +                         * ...and calls `off` on the channel to unregister all listeners
Please can you propagate this prose description to the docstring for this method and subsequently to the prose comments in the test methods that call this method?

2023-02-15 12:55 UTC, AndyTWF commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt
> +                         * ...and calls `off` on the channel to unregister all listeners
Yes done :) d945ec50

2023-02-15 12:55 UTC, AndyTWF commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt
>      fun stubConnectionOff() {
Done :)

2023-02-15 14:05 UTC, davyskiba approved these changes

2023-02-16 12:08 UTC, lawrence-forooghian approved these changes

2023-02-16 13:05 UTC, merged

2023-03-10 09:43 UTC, kozaxinan commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +            ably.connection.off()
This can be handled in finally block.

2023-03-10 09:43 UTC, kozaxinan commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/BatteryDataProvider.kt
> +internal class DefaultBatteryDataProvider(context: Context) : BatteryDataProvider {
why is this provider is in use after the context is destroyed? would be easier to stop using old battery provider and just create a new one with new context?
this weak reference could create buggy scenarios after context is destroyed and cleaned up. wdyt?