Add more logs to the SDKs
ably/ably-asset-tracking-android pull request #813
Opened 2022-11-17 16:57 UTC by KacperKluka

I've added a bunch of logs to the SDKs:
- Publisher lifecycle logs
- Subscriber lifecycle logs
- Error logging for the Ably wrapper

2022-11-17 17:15 UTC, QuintinWillison requested changes
Furthermore, on the subject of logging failure/exception cases, I'm a bit worried that the `onError` implementations (`wrapInResultCallback`) that you've provided will also end up with confusing log output when the application itself also logs exceptions. There's also no way for the app developer to opt out of this behaviour, so my gut feeling is that this presents over-logging.

2022-11-17 17:15 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt
> +        logHandler?.v("$TAG Creating a publisher instance")
Looking at this message in context of required fields being missing then I think that might cause confusion when debugging. Perhaps consider moving this line to after the required fields check.

2022-11-17 17:15 UTC, QuintinWillison commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/SubscriberBuilder.kt
> +        logHandler?.v("$TAG Creating a subscriber instance")
Looking at this message in context of required fields being missing then I think that might cause confusion when debugging. Perhaps consider moving this line to after the required fields check.

2022-11-17 17:15 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt
> +            logHandler?.v("$TAG Creating a publisher instance failed due to missing required fields")
I generally avoid log-before-throw as more often than not it ends up with a situation where code above this also logs the exception and then when debugging it's difficult to ascertain how many exceptions were actually thrown - whether caught or uncaught.

Therefore, I think you should remove this log statement entirely. It an app developer has managed to call `start()` but is unaware that it's thrown them back an exception then I think they have larger problems afoot. 😬

2022-11-17 17:15 UTC, QuintinWillison commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/SubscriberBuilder.kt
> +            logHandler?.v("$TAG Creating a subscriber instance failed due to missing required fields")
Similar to my comment on publisher `start()`, I would suggest removing this log line completely. The app should be catching the exception.

2022-11-18 06:07 UTC, QuintinWillison commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt
> +            logHandler?.v("$TAG Creating a publisher instance failed due to missing required fields")
I'm removing this objection, given I've now [created an issue](https://github.com/ably/ably-asset-tracking-android/pull/813#ref-issue-1454514942) to look at this across all of our SDKs.

2022-11-18 06:07 UTC, QuintinWillison commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/SubscriberBuilder.kt
> +            logHandler?.v("$TAG Creating a subscriber instance failed due to missing required fields")
I'm removing this objection, given I've now [created an issue](https://github.com/ably/ably-asset-tracking-android/pull/813#ref-issue-1454514942) to look at this across all of our SDKs.

2022-11-18 07:18 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt
> +        logHandler?.v("$TAG Creating a publisher instance")
[0c143bd](https://github.com/ably/ably-asset-tracking-android/pull/813/commits/0c143bd404aa48d678d6b27fd29b8a82d8b31675)

2022-11-18 07:18 UTC, KacperKluka commented on subscribing-sdk/src/main/java/com/ably/tracking/subscriber/SubscriberBuilder.kt
> +        logHandler?.v("$TAG Creating a subscriber instance")
[0c143bd](https://github.com/ably/ably-asset-tracking-android/pull/813/commits/0c143bd404aa48d678d6b27fd29b8a82d8b31675)

2022-11-18 09:50 UTC, QuintinWillison approved these changes

2022-11-18 09:50 UTC, merged