Unnest nested interfaces
ably/ably-asset-tracking-android pull request #825
Opened 2022-12-01 17:34 UTC by ikbalkaya

I have un-nested and renamed all interfaces that were nested under `ResolutionPolicy` that was causing an issue when Java users were adding a publisher.

For detail and more context please visit this [internal Slack thread](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1665130953392569)

Note to reviewers 
*  I quickly renamed interfaces that made sense at the time but please let me know if you think of better names 
* I haven't thoroughly checked the impact of this change on users but our tests seems to pass as a result of the change. I just needed to change a snippet in example Java code. But considering those interfaces were public, I wonder what other impact might we have on users apart from they would have to update the name of interfaces (package shouldn't change)

2022-12-02 06:13 UTC, KacperKluka requested changes
Overall it looks good, just a few naming suggestions 😉 

I wonder, are there some other nested interfaces in AAT API that we should be worried about? 🤔

2022-12-02 06:13 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/HooksSubscriberSetListener.kt
> +interface HooksSubscriberSetListener {
All the other interfaces that were nested in the `ResolutionPolicy` have now names starting with `ResolutionPolicy`, however, this one doesn't. Maybe for consistency, this should be called `ResolutionPolicySubscriberSetListener`? 🤔

2022-12-02 06:13 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/HooksTrackableSetListener.kt
> +interface HooksTrackableSetListener {
Like above, maybe for consistency, this should be called `ResolutionPolicyTrackableSetListener`? 🤔

2022-12-02 11:23 UTC, davyskiba approved these changes

2022-12-06 11:22 UTC, ikbalkaya commented
Closing this as this is an issue with Android studio and not an issue with this repo - Filed a bug report https://issuetracker.google.com/issues/261386526

2022-12-06 11:22 UTC, closed without merging