Add architectural notes documentation
ably/ably-asset-tracking-android pull request #832
Opened 2022-12-08 12:48 UTC by KacperKluka

Added a few important notes on the architecture decisions we took and why we took them.

2022-12-09 09:25 UTC, QuintinWillison requested changes
Really useful. Thanks @KacperKluka! 💪 
A few suggestions, some aligned with [similar comments I just made in your other PR in the common repository](https://github.com/ably/ably-asset-tracking-common/pull/70#pullrequestreview-1211320731).

2022-12-09 09:25 UTC, QuintinWillison commented on CONTRIBUTING.md
> +Before contributing to this repository please read the [architecture decisions notes](/ArchitecturalNotes.md).
These two documents are peers so I think it's preferable for this to be relative, not absolute:

```suggestion
Before contributing to this repository please read the [architectural notes](ArchitecturalNotes.md).
```

2022-12-09 09:25 UTC, QuintinWillison commented on ArchitecturalNotes.md
> +The projects uses multiple gradle modules. Instead of repeating the same configuration in each of the modules we use
Gradle is a product name so should be cased as [Gradle do themselves](https://gradle.org/):

```suggestion
The projects uses multiple Gradle modules. Instead of repeating the same configuration in each of the modules we use
```

2022-12-09 09:25 UTC, QuintinWillison commented on ArchitecturalNotes.md
> +The project consists of multiple modules, each of them having different purpose.
```suggestion
The project consists of multiple modules, each of them having a different purpose.
Modules with `sdk` in their name are part of the public API of the SDK.
```

2022-12-09 09:25 UTC, QuintinWillison commented on ArchitecturalNotes.md
> +- `android-test-common` contains shared code for the Android integration tests.
Illustrating for this line only, but might be nice for all of these bullets...

```suggestion
- [`android-test-common`](android-test-common/) contains shared code for the Android integration tests.
```

2022-12-09 09:25 UTC, QuintinWillison commented on ArchitecturalNotes.md
> +## Custom location engines
Perhaps worth adding a sentence here that links to an issue in the backlog for this, assuming we have one?

2022-12-09 09:41 UTC, davyskiba commented on ArchitecturalNotes.md
> +The async work is performed on another thread from which you should not access or alter the `properties`. After the asynchronous work is done you should use the `postWork()` method
I think `asyncWork` is performed in a different coroutine context, but it is running on the same thread as we are using the queue with `CoroutineScope(singleThreadDispatcher + SupervisorJob())`

2022-12-09 10:25 UTC, KacperKluka commented on ArchitecturalNotes.md
> +
Good idea, let me know if that's what you had in mind 😉 https://github.com/ably/ably-asset-tracking-android/pull/832/commits/fcc939affe3980759f87f55090da3a04cb435811

2022-12-09 10:25 UTC, KacperKluka commented on ArchitecturalNotes.md
> +## Custom location engines
Good point, I've created an issue for it and added a link to the issue here 😉 https://github.com/ably/ably-asset-tracking-android/pull/832/commits/1c2c540491f3b1243e9844f16423720deb372565

2022-12-09 10:26 UTC, KacperKluka commented on ArchitecturalNotes.md
> +The async work is performed on another thread from which you should not access or alter the `properties`. After the asynchronous work is done you should use the `postWork()` method
Good point! Thanks 😁 https://github.com/ably/ably-asset-tracking-android/pull/832/commits/32c24382ba28c13663fd98c7b6222a2fba9de079

2022-12-09 11:15 UTC, QuintinWillison commented on ArchitecturalNotes.md
> +
Spot on, thanks! 😁

2022-12-09 11:15 UTC, QuintinWillison commented on ArchitecturalNotes.md
> +## Custom location engines
Thanks.

2022-12-09 11:16 UTC, QuintinWillison commented on ArchitecturalNotes.md
> +The async work is performed on another thread from which you should not access or alter the `properties`. After the asynchronous work is done you should use the `postWork()` method
Good spot, @davyskiba - nice! 😁

2022-12-09 11:17 UTC, QuintinWillison approved these changes

2022-12-14 07:42 UTC, QuintinWillison commented
Failing emulation runs, which I have already restarted several times for this pull request, are clearly unrelated to the content of this pull request so I'm going to merge it regardless.

2022-12-14 07:42 UTC, merged