Rid R8 minify missing class warning
ably/ably-asset-tracking-android pull request #850
Opened 2022-12-14 14:34 UTC by QuintinWillison

As seen [in this run](https://github.com/ably/ably-asset-tracking-android/actions/runs/3693590989/jobs/6253753819#step:5:616):

```
WARNING:Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/runner/work/ably-asset-tracking-android/ably-asset-tracking-android/integration-testing-app/build/outputs/mapping/debug/missing_rules.txt.

WARNING:R8: Missing class com.google.auto.value.AutoValue$Builder (referenced from: com.mapbox.api.directions.v5.models.Admin$Builder and 38 other contexts)
Missing class com.google.firebase.messaging.FirebaseMessaging (referenced from: void io.ably.lib.push.ActivationContext.getRegistrationToken(io.ably.lib.types.Callback))
```

I've used the lines suggested in the `missing_rules.txt` generated on my local machine after a `./gradlew check assemble`.

2022-12-15 15:00 UTC, davyskiba approved these changes

2022-12-16 12:22 UTC, ikbalkaya requested changes
I think we might need to keep before suppress the warning in one of the changes

2022-12-16 12:22 UTC, ikbalkaya commented on integration-testing-app/proguard-rules.pro
> +-dontwarn com.google.firebase.messaging.FirebaseMessaging
Shouldn't this have its -keep counterpart at top 🤔 
`-keep class com.google.firebase.messaging.** { *; }
`

2022-12-16 13:56 UTC, QuintinWillison commented on integration-testing-app/proguard-rules.pro
> +-dontwarn com.google.firebase.messaging.FirebaseMessaging
Looking at the logs from the assemble run for this PR there aren't any instances of `R8` warnings. I would rather not add this if it's not required, as all checks are passing and this is only for the integration testing app. Or did you spot something I'm missing? I included everything that the tools suggested I include (`missing_rules.txt`).

2022-12-16 14:04 UTC, ikbalkaya commented on integration-testing-app/proguard-rules.pro
> +-dontwarn com.google.firebase.messaging.FirebaseMessaging
Of course, Other classes above this has this pattern of `keep` and `dontwarn` I thought this one would need the same

2022-12-16 14:04 UTC, ikbalkaya approved these changes

2022-12-16 14:50 UTC, merged