location: sanitize locations from mapbox
ably/ably-asset-tracking-android pull request #864
Opened 2022-12-27 16:17 UTC by mschristensen

This commit ensures that new Location objects that have an invalid lat/lng/altitude component throw an IllegalArgumentException. Additionally, a sanitize() method is made available on the Location object that will gracefully convert any invalid values to a sensible default.

2022-12-27 16:23 UTC, mschristensen commented
@KacperKluka this is a WIP, but wanted some early feedback:

Am I on the right lines here with how to do this in an idiomatic Kotlin way? Or is there a better approach?

I think one potential problem with the require pattern could be that other instantiations of a Location with non-finite values for lat/lng/altitude could now throw (eek). So, perhaps we could return a special value, like a `data class ValidationError(val message: String)`, from the `sanitize()` method?

Still to add: similar logic for enhanced location updates and some tests.

2022-12-27 16:56 UTC, mschristensen commented
@KacperKluka I have just updated with a new approach that doesn't rely on throwing an exception. Any feedback appreciated :)

2022-12-27 17:36 UTC, KacperKluka reviewed
Nicely done, I like the fact that you managed to get rid of the `require` calls in the constructor 👏 A few suggestions from me 😉

2022-12-27 17:36 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/LocationUpdateModels.kt
> +    fun validate(): Pair<Location?, ArrayList<LocationValidationError>> {
While it works, using the `Pair` is a bit hacky 😉 I'd suggest using `Result<Location>` instead and then instead of `LocationValidationError` create an exception that holds a list of String messages. Also, I'm wondering whether we really need to return a new `Location` that is an exact copy of the current location from this method 🤔 Perhaps we could return the same location given that we are not updating its fields?

After applying all suggestions it would look something like this:
```kotlin
class LocationValidationException(val errors: List<String>): Exception("Failed to validate a location object")

data class Location(
    // ...
) {
    fun validate(): Result<Location> {
        // ...
        return if (errs.isNotEmpty()) {
            Result.failure(LocationValidationException(errs))
        } else {
            Result.success(this)
        }
    }
}
```

2022-12-27 17:36 UTC, KacperKluka commented on core-sdk/src/main/java/com/ably/tracking/LocationUpdateModels.kt
> +        val errs: ArrayList<LocationValidationError> = ArrayList<LocationValidationError>()
In Kotlin we tend to use lists instead of arrays, so I'd change this to a `MutableList` 😉 Also I think the less abbreviations the better so I'd change the name to `errors` or even `validationErrorMessages` 🤔 
```suggestion
        val errors: MutableList<LocationValidationError> = mutableListOf()
```

2022-12-27 17:36 UTC, KacperKluka commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/Mapbox.kt
> +                val (atLocation, errs) = rawLocation.toAssetTracking().sanitize().validate()
I think that the `sanitize()` and `validate()` steps are always wanted when we convert a `Location` to an AAT location, so I'd put those two methods inside the `toAssetTracking()` mapping function, WDYT? 🤔

2022-12-28 09:29 UTC, jaley commented
Given that there's little time for back and forth validation of this fix with real users, would it possible to reproduce the downstream crash in a unit test, then confirm that this PR fixes it?

Had a look around at `CorePublisherLocationUpdatesPublishingTest` seems like a relevant place for a "santizes location data" or similar unit test, there's already a mock of the Mapbox dependency there to inject invalid data.

WDYT, @KacperKluka & @mschristensen ?

2022-12-28 17:50 UTC, mschristensen commented
@KacperKluka  A couple of checks are not passing, but these appear to be flakes unrelated to this work, afaict (they differ each time they're run)?

2022-12-29 16:10 UTC, KacperKluka requested changes
Almost there 👍 A few more suggestions 😉

2022-12-29 16:10 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/MapboxTest.kt
> +        val mapboxLocationObserver =
Since those tests are quite long it would be great to have the [given/when/then](https://en.wikipedia.org/wiki/Given-When-Then) structure on them, however, that's not a critical problem, so feel free to ignore this suggestion 😉

2022-12-29 16:10 UTC, KacperKluka commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/MapboxTest.kt
> +                    Assert.assertTrue(it.latitude == 1.0)
Generally, it is better to use `Assert.assertEquals(1.0, it.latitude)` because in case of a failed assertion we receive more info about what went wrong. However, this doesn't affect the tests, so feel free to ignore this suggestion and leave the code as it is 😉

2022-12-30 11:48 UTC, mschristensen commented on core-sdk/src/main/java/com/ably/tracking/LocationUpdateModels.kt
> +     * Utility function that returns a successful result with the Location iff. it is valid.
Ah, I meant [if and only if](https://en.wikipedia.org/wiki/If_and_only_if#:~:text=In%20logic%20and%20related%20fields,true%20or%20both%20are%20false.), but will update for clarity!

2022-12-30 12:14 UTC, mschristensen commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/MapboxTest.kt
> +        val mapboxLocationObserver =
I'll skip this as I'm just making these changes in a spare ten minutes I have, but feel free to make them if you would prefer them to be there :)

2022-12-30 12:14 UTC, mschristensen commented on publishing-sdk/src/test/java/com/ably/tracking/publisher/MapboxTest.kt
> +                    Assert.assertTrue(it.latitude == 1.0)
I'll skip this as I'm just making these changes in a spare ten minutes I have, but feel free to make them if you would prefer them to be there :)

2022-12-30 13:38 UTC, KacperKluka approved these changes
LGTM 👍

2023-01-02 10:48 UTC, davyskiba approved these changes

2023-01-03 16:18 UTC, merged