Feature/remove add exceptions
ably/ably-asset-tracking-android pull request #883
Opened 2023-01-05 18:25 UTC by davyskiba

There were two issues with adding a trackable when offline ably real-time `connect()` and `channel.presence.get(true)`.
To address the first one, I've removed rethrowing connection timeout exception because we already handle reconnect.
For the second one, I have added a timeout to `SubscribeToTrackablePresenceMessagesWorker.` It is handled as a failure and is reattempted later.

Additionally, to make this task easier, I have renamed the three workers that are part of adding a trackable chain with names better reflecting what they do and removed an unused callback-based function to subscribe to presence messages.

Before merging this, I want to add a test for the connection timeout change

Resolves #871

2023-01-06 11:43 UTC, ikbalkaya reviewed
It would be good to clarify whether the explicit timeout is needed, otherwise looks good

2023-01-06 11:43 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/PrepareConnectionForTrackableWorker.kt
> + * This worker establishes Ably connection and enter trackable specific channel.
```suggestion
 * This worker establishes Ably connection and enters trackable to specific channel.
```

2023-01-06 11:43 UTC, ikbalkaya commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/SubscribeToTrackablePresenceMessagesWorker.kt
> +                withTimeout(SUBSCRIBE_TO_PRESENCE_TIMEOUT) {
I know you had put this on PR description but I remember having a conversation yesterday that we don't really want to introduce timeouts in the AAT SDK. Is it. Can you please check if it is possible to handle this case without explicit timeout ? (Eg. whether ably-java already have its own timeout and returns the result when appropriate)

2023-01-09 09:50 UTC, davyskiba commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/SubscribeToTrackablePresenceMessagesWorker.kt
> +                withTimeout(SUBSCRIBE_TO_PRESENCE_TIMEOUT) {
I think we need this timeout because `ably.subscribeForPresenceMessages` is calling [Presence.get(true)](https://github.com/ably/ably-java/blob/9786de65bd44c2f139a53ee235535cb7617cbc87/lib/src/main/java/io/ably/lib/realtime/Presence.java#L96) underneath which has no timeout and can hang indefinitely if a connection cannot be established

2023-01-10 10:02 UTC, ikbalkaya approved these changes

2023-01-10 13:00 UTC, KacperKluka requested changes
Overall looks good but I found a few things to discuss 😁

2023-01-10 13:33 UTC, davyskiba commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/SubscribeToTrackablePresenceMessagesWorker.kt
> +        private const val SUBSCRIBE_TO_PRESENCE_TIMEOUT = 2_000L
I was wondering if it should be even shorter than that 😅 
The idea is to try to subscribe smoothly or retry later, not to block the caller for an extended time.
But this is an arbitrarily chosen value, so I'm open to suggestions

2023-01-10 13:37 UTC, davyskiba commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/AddTrackableToPublisherWorker.kt
> +internal class AddTrackableToPublisherWorker(
6ef62daaa7b91f12242b3aac33465aaa3ebb8b97

2023-01-10 14:43 UTC, davyskiba commented on publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/SubscribeToTrackablePresenceMessagesWorker.kt
> +        private const val SUBSCRIBE_TO_PRESENCE_TIMEOUT = 2_000L
Great idea <3
ff8c83e57469d76cfcfdc6828b2187ffc403fa9c

2023-01-12 09:07 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        if (channel.state == ChannelState.failed) {
Great catch. After ably-java code investigation, I've confirmed that the channel will enter failed state only after getting an error message or when the connection enters a failed state. None of those should be handled here.
Removed failure result in 3a88195b09925df4b07bd0c55df9052cba3dea40

2023-01-12 10:16 UTC, KacperKluka approved these changes
LGTM, thanks! 👍

2023-01-12 10:30 UTC, davyskiba commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +                        if (channel.state == ChannelState.failed) {
Reinstate this check back as a channel can be failed when the token has no required capability, as pointed out by this test
 `RequestingNewTokenTest > shouldNotAddTrackableWhenRenewedTokenDoesNotHaveCapabilityForTrackableId` or when the connection is already in a failed state

2023-01-13 10:36 UTC, KacperKluka approved these changes

2023-01-13 17:13 UTC, jaley commented
Adding a note to highlight which `NetworkConnectivityTest` cases should be fixed by this issue. The TCP-level tests are now in main, so you can reproduce by merging in main and enabling these tests (they are currently disabled as they fail). 
`DisconnectAndSuspend` and `AttachUnresponsive` are not currently in main, they're on #886 

## faultBeforeAdingTrackable[TcpConnectionRefused]

Fails because we throw timeout exception on `track()` when offline:

```
01-13 15:12:36.048 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:12:36.045: [DefaultAbly] Timeout while waiting for Ably to connect com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:12:36.049 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:12:36.048: [DefaultAbly] Failed to start Ably connection com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:12:36.054 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:12:36.052: [DefaultPublisher] Publisher track operation failed com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 19007:  attempt to add active Trackable while fault active - failed - com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at com.ably.tracking.common.DefaultAbly.connectSuspending(Ably.kt:1026)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at com.ably.tracking.common.DefaultAbly.access$connectSuspending(Ably.kt:246)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at com.ably.tracking.common.DefaultAbly$connectSuspending$1.invokeSuspend(Unknown Source:16)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-13 15:12:36.056 19291 19319 D PUBLISHING SDK IT: 	at java.lang.Thread.run(Thread.java:1012)
```

## faultBeforeAdingTrackable[TcpConnectionUnresponsive]

Same as `faultBeforeAdingTrackable[TcpConnectionRefused]`

## faultBeforeAdingTrackable[AttachUnresponsive]

Similar to `faultBeforeAdingTrackable[TcpConnectionRefused]` in that the initial `track()` call times out
and an exception is thrown. Difference is that the underlying timeout is on `channe.attach()` instead of
the initial connection

Important that we ensure we fix this underlying cause, as it's different to the other cases, even though
the user-visible exception is the same.

```
01-13 15:15:21.021 19291 20518 D PUBLISHING SDK IT: 19457:  13-01-23 15:15:21.020: [DefaultAbly] Failed to suspend enter presence for channel com.ably.tracking.common.DefaultAblySdkRealtime$Channel@eb28e87.name com.ably.tracking.ConnectionException: Attach timed out for channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097
01-13 15:15:21.023 19291 20448 D PUBLISHING SDK IT: 19398:  13-01-23 15:15:21.022: [DefaultAbly] Failed to enter the presence of channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097 com.ably.tracking.ConnectionException: Attach timed out for channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097
01-13 15:15:21.024 19291 20448 D PUBLISHING SDK IT: 19398:  13-01-23 15:15:21.023: [DefaultAbly] Failed to connect for channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097 com.ably.tracking.ConnectionException: Attach timed out for channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097
01-13 15:15:21.027 19291 20448 D PUBLISHING SDK IT: 19398:  13-01-23 15:15:21.026: [DefaultAbly] Failed to connect for trackable bb25f6e2-340a-48f1-b0e8-2021d0ad9097 com.ably.tracking.ConnectionException: Attach timed out for channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097
01-13 15:15:21.029 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:15:21.029: [DefaultPublisher] Publisher track operation failed com.ably.tracking.ConnectionException: Attach timed out for channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 19007:  attempt to add active Trackable while fault active - failed - com.ably.tracking.ConnectionException: Attach timed out for channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: com.ably.tracking.ConnectionException: Attach timed out for channel tracking:bb25f6e2-340a-48f1-b0e8-2021d0ad9097
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 	at com.ably.tracking.common.AblyHelpersKt.toTrackingException(AblyHelpers.kt:61)
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 	at com.ably.tracking.common.DefaultAbly$enterPresenceSuspending$2$1.onError(Ably.kt:922)
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 	at io.ably.lib.realtime.Presence.failQueuedMessages(Presence.java:896)
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 	at io.ably.lib.realtime.Presence.setSuspended(Presence.java:948)
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 	at io.ably.lib.realtime.ChannelBase.setSuspended(ChannelBase.java:588)
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 	at io.ably.lib.realtime.ChannelBase$2.run(ChannelBase.java:431)
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 	at java.util.TimerThread.mainLoop(Timer.java:563)
01-13 15:15:21.030 19291 19319 D PUBLISHING SDK IT: 	at java.util.TimerThread.run(Timer.java:513)
```

## faultBeforeAdingTrackable[DisconnectAndSuspend]

The 10 second timeout waiting for Ably to connect kills the `track()` call.
Same as `faultBeforeAdingTrackable[TcpConnectionRefused]`, but note that this is blocking
the next part of the test, where we allow connection after 2 minutes.

```
01-13 15:18:02.487 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:18:02.485: [DefaultAbly] Timeout while waiting for Ably to connect com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:18:02.489 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:18:02.487: [DefaultAbly] Failed to start Ably connection com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:18:02.493 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:18:02.491: [DefaultPublisher] Publisher track operation failed com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:18:02.495 19291 19319 D PUBLISHING SDK IT: 19007:  attempt to add active Trackable while fault active - failed - com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:18:02.495 19291 19319 D PUBLISHING SDK IT: com.ably.tracking.ConnectionException: Timeout was thrown when waiting for Ably to connect
01-13 15:18:02.495 19291 19319 D PUBLISHING SDK IT: 	at com.ably.tracking.common.DefaultAbly.connectSuspending(Ably.kt:1026)
01-13 15:18:02.495 19291 19319 D PUBLISHING SDK IT: 	at com.ably.tracking.common.DefaultAbly.access$connectSuspending(Ably.kt:246)
01-13 15:18:02.495 19291 19319 D PUBLISHING SDK IT: 	at com.ably.tracking.common.DefaultAbly$connectSuspending$1.invokeSuspend(Unknown Sou [...]

2023-01-16 14:49 UTC, lawrence-forooghian reviewed
Some initial comments about the tests - will look more thoroughly afterwards 🙂

2023-01-16 14:49 UTC, lawrence-forooghian commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt
> +                givenConfig.connectionState?.let { connectionState ->
This needs a description of the behaviour:

```
* if ${givenConfig.connectionState != null} {
* ...that the connection’s `state` property returns ${givenConfig.connectionState}...
* }
```

2023-01-16 14:49 UTC, lawrence-forooghian commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt
> +                    // ...and checks the channel’s state ${thenConfig.numberOfChannelStateFetchesToVerifyAfterPresence} times...
All of these newly-added descriptions need to go into the `test` method’s docstring, and subsequently into the "Given / When / Then" descriptions of applicable test cases in `DefaultAblyTests`.

2023-01-16 15:22 UTC, davyskiba commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt
> +import com.ably.tracking.common.helper.DefaultAblyTestScenarios.Connect.Companion
982bdd316f34d738cd9f4b3e47f1156728bec9a4

2023-01-16 15:22 UTC, davyskiba commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt
> +                    // ...and checks the channel’s state ${thenConfig.numberOfChannelStateFetchesToVerifyAfterPresence} times...
9b4554e4abbd3ba665af6585842da54d841f8573

2023-01-16 15:56 UTC, lawrence-forooghian commented on common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt
> +                    // ...and checks the channel’s state ${thenConfig.numberOfChannelStateFetchesToVerifyAfterPresence} times...
I think that without it the tests would be 100% non-understandable 😄

2023-01-17 12:30 UTC, lawrence-forooghian commented
@jaley I'm going to double-check the list of fixed integration tests that you mentioned in https://github.com/ably/ably-asset-tracking-android/pull/883#issuecomment-1382153308, since as I mentioned in https://github.com/ably/ably-asset-tracking-android/issues/907#issuecomment-1384524042 it seems like `faultBeforeAddingTrackable[EnterFailedWithNonfatalNack]` is also now passing on this branch. (Perhaps this fault was added after you wrote that comment, I'm not sure. Do you remember which commit of the integration tests you tested this branch with?)

2023-01-17 12:59 UTC, lawrence-forooghian commented
Sorry @jaley, I think I might have misunderstood https://github.com/ably/ably-asset-tracking-android/pull/883#issuecomment-1382153308 – I thought you were saying that these were the test cases that you had observed as being fixed by this branch, but were those in fact your expectations for what would be fixed? Either way, I’ll compile an updated list of what’s fixed by this branch.

2023-01-18 15:09 UTC, lawrence-forooghian commented
My understanding was that this pull request would stop the publisher’s `track` and `add` methods from being able to fail with a `ConnectionException`. But both of these methods are still documented as being able to do exactly this. Have I missed something?

Here are the ways in which it seems like these methods can still fail with `ConnectionException`:

## PrepareConnectionForTrackableWorker

Calls [`ably.startConnection()`](https://github.com/ably/ably-asset-tracking-android/blob/9b4554e4abbd3ba665af6585842da54d841f8573/publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/PrepareConnectionForTrackableWorker.kt#L91) and [`ably.connect()`](https://github.com/ably/ably-asset-tracking-android/blob/9b4554e4abbd3ba665af6585842da54d841f8573/publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/PrepareConnectionForTrackableWorker.kt#L102-L106).

What can go wrong with these Ably wrapper operations?

- `startConnection()`: Although not mentioned in the docstring, my tests in [#914](https://github.com/ably/ably-asset-tracking-android/pull/914/) demonstrate that this can fail with a `ConnectionException`. The behaviour has changed in this PR but as it stands it can still throw `ConnectionException`.
- `connect()`: This is documented as being able to fail with a `ConnectionException`.

What does it do if one of these Ably wrapper operations fails with a `ConnectionException`?

- `startConnection()`:
   - From looking at code: passes it to `AddTrackableFailedWorker`, which seems unexpected since the end result is that the caller of `add` or `track` receives the `ConnectionException`
   - From looking at tests: we have no tests for this
- `connect()`:
   - From looking at code: passes it to `AddTrackableFailedWorker`, which seems unexpected since the end result is that the caller of `add` or `track` receives the `ConnectionException`
   - From looking at tests: existing test that shows that it does exactly this

2023-01-18 15:10 UTC, lawrence-forooghian commented
## Does this PR fix [the tests that James expected it to](https://github.com/ably/ably-asset-tracking-android/pull/883)?

- **TODO — understand why the tests are behaving non-deterministically**
- **TODO — understand why the tests aren’t timing out**

Testing by merging commit `f1557c2` of PR #886 into this branch.

- `faultBeforeAddingTrackable[TcpConnectionRefused]` — Test has been running for ~4 mins now, all it’s doing is printing the following once a minute:

  ```
  01-17 17:45:07.951 10304 10721 D PUBLISHING SDK IT: THREAD 252 is 'WebSocketConnectReadThread-252' [no Looper]
  01-17 17:45:07.951 10304 10721 D PUBLISHING SDK IT: 252:  Connection error  java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 13579) from /:: (port 58658): connect failed: ECONNREFUSED (Connection refused)
  ```

- `faultBeforeAddingTrackable[TcpConnectionUnresponsive]` — Test has been running for ~4 mins now, all it’s doing is printing the following every ~75 seconds:

  ```
  01-17 17:50:49.337 11094 11173 D PUBLISHING SDK IT: 141:  Layer4Proxy: proxy starting to run
  01-17 17:50:49.340 11094 11173 D PUBLISHING SDK IT: 141:  Layer4Proxy: proxy trying to accept
  01-17 17:50:49.377 11094 11355 D PUBLISHING SDK IT: THREAD 180 is 'Thread-42' [no Looper]
  01-17 17:50:49.386 11094 11355 D PUBLISHING SDK IT: 180:  Layer4ProxyConnection: GET /?key=4v8EIQ.F3rJog%3AHRzgFlPm12ZrMHK2QN7MDqKHWKtTPrTc-ol1tXeSZOI
  &v=1.0&format=msgpack&clientId=AatTestProxy_24d6ffb8-347c-4333-93be-a168dcd62679&heartbeats=false&agent=ably-java%2F1.2.22%20ably-asset-tracking-andro
  id-publisher-tests%2F1.5.1%20android%2F33 HTTP/1.1
  01-17 17:50:49.386 11094 11355 D PUBLISHING SDK IT: Connection: Upgrade
  01-17 17:50:49.386 11094 11355 D PUBLISHING SDK IT: Host: localhost:13579
  01-17 17:50:49.386 11094 11355 D PUBLISHING SDK IT: Sec-WebSocket-Key: xSkbsOYFLNpvFCgRxUsv8A==
  01-17 17:50:49.386 11094 11355 D PUBLISHING SDK IT: Sec-WebSocket-Version: 13                                                                         01-17 17:50:49.386 11094 11355 D PUBLISHING SDK IT: Upgrade: websocket
  01-17 17:50:49.386 11094 11355 D PUBLISHING SDK IT:
  01-17 17:50:49.856 11094 11356 D PUBLISHING SDK IT: THREAD 181 is 'Thread-43' [no Looper]
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: 181:  Layer4ProxyConnection: HTTP/1.1 101 Switching Protocols
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: Date: Tue, 17 Jan 2023 22:11:48 GMT
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: Connection: upgrade
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: Sec-Websocket-Accept: EVi8lpK7nfY39SQZss6SsMzmPIE=                                                01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: Upgrade: websocket
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: X-Cache: Miss from cloudfront
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: Via: 1.1 826b4bc277e070a005bd57e6e653dfee.cloudfront.net (CloudFront)
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: X-Amz-Cf-Pop: GRU3-C1
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT: X-Amz-Cf-Id: eakl9P3KCbFKZx91shwjYZaMa4TN69ong_OJeANydgBkHuuYGOO9Rg==
  01-17 17:50:49.872 11094 11356 D PUBLISHING SDK IT:
  ```

- `faultBeforeAddingTrackable[AttachUnresponsive]` — On first run, process crashed after 2m 12s with some inscrutable error. Second run, crashed with this, after 3m 32s:

  ```
  01-17 18:02:19.209 12324 12357 E TestRunner: ----- begin exception -----
  01-17 18:02:19.210 12324 12357 E TestRunner: com.ably.tracking.ConnectionException: Timeout was thrown when waiting for channel to attach
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at com.ably.tracking.common.DefaultAbly.waitForChannelReconnection(Ably.kt:918)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at com.ably.tracking.common.DefaultAbly.access$waitForChannelReconnection(Ably.kt:235)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at com.ably.tracking.common.DefaultAbly$waitForChannelReconnection$1.invokeSuspend(Unknown Source:17)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
  01-17 18:02:19.210 12324 12357 E TestRunner: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
  01-17 18:02:19.213 12324 12357 E TestRunner: ----- end exception -----
  01-17 18:02:19.237 12324 12357 I TestRunner: finished: faultBeforeAddingTrackable[AttachUnresponsive](com.ably.tracking.publisher.NetworkConnectivityTests)
  
  com.ably.tracking.ConnectionException: Timeout was thrown when waiting for channel to attach
  at com.ably.tracking.common.DefaultAbly.waitForChannelReconnection(Ably.kt:918)
  at com.ably.tracking.common.DefaultAbly.access$waitForChannelReconnection(Ably.kt:235)
  at com.ably.tracking.common.DefaultAbly$waitForChannelReconnection$1.invokeSuspend(Unknown Source:17)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
  ```

- `faultBeforeAddingTrackable[DisconnectAndSuspend]`

  Seems to be periodically printing the following:

  ```
  01-17 18:06:05.801 13115 13165 D PUBLISHING SDK IT: 119:  17-01-23 18:06:05.796: [DefaultAbly] Timeout while waiting for channel reconnection tracking:f114aa4f-7bb5-4c19-a6df-53cdb3eef524 com.ably.tracking.ConnectionException: Timeout was thrown when waiting for channel to attach
  01-17 18:06:05.807 13115 13165 D PUBLISHING SDK IT: 119:  17-01-23 18:06:05.802: [DefaultAbly] Failed to send message for channel tracking:f114aa4f-7bb5-4c19-a6df-53cdb3eef524 com.ably.tracking.ConnectionException: Timeout was thrown when waiting for channel to attach
  ```

  and then after 3m 8s it fails with the following:

  ```
  01-17 18:07:46.032 13115 13146 E TestRunner: failed: faultBeforeAddingTrackable[DisconnectAndSuspend](com.ably.tracking.publisher.NetworkConnectivityTests)
  01-17 18:07:46.051 13115 13146 E TestRunner: ----- begin exception -----
  01-17 18:07:46.058 13115 13146 E Test [...]

2023-01-18 15:16 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +     * If the operation doesn't complete in [timeoutInMilliseconds] it will return and let ably-java handle reconnection.
What's the logic behind having two different code paths here, one where ably-java connects within 10 seconds and one where it doesn't? Can we not apply the same handling in both cases - that is, just let ably-java do its thing and then once the connection becomes connected we handle it?

2023-01-18 15:20 UTC, lawrence-forooghian commented
This pull request is causing the failing test mentioned in #907 (`faultBeforeAddingTrackable[EnterFailedWithNonfatalNack]`) to pass, since even though the presence enter operation fails the trackable still enters the `online` state. This is inconsistent with the expected behaviour described in #871:

> If all of the operations required are in one of the following states:
> 
> * still in progress; or
> * succeeded; or
> * failed for a retriable reason
> 
> then it's `Offline`.

2023-01-18 16:24 UTC, KacperKluka commented
On our today's call, we agreed that we need to implement some kind of a retry mechanism for certain Ably operations. As a general rule:
- 4xx error codes represent non-retriable operations 
- 5xx error codes represent retriable operations.

The best place to add the retry logic would be the `WorkerQueue` but we have to decide whether it will be a general mechanism for retries or maybe something more use-case (or `Worker`) specific.

2023-01-26 15:48 UTC, closed without merging