Wrap `ably-java`’s `ChannelStateChange` in our own type
ably/ably-asset-tracking-android pull request #894
Opened 2023-01-11 18:46 UTC by lawrence-forooghian

I wanted to write unit tests that checked how `DefaultAbly` behaves in response to `AblySdkRealtime.on` emitting various `ChannelStateChange` values. However, I discovered that `ably-java`’s `ChannelStateChange` class does not have a public constructor. (For some reason, the analogous `ConnectionStateChange` class _does_ have a public constructor; not sure if this difference is intentional.) Furthermore, we cannot use MockK to create a useful mock of it, since its `current` etc values are implemented as Java fields as opposed to properties.

I wasn’t sure whether to modify ably-java to make `ConnectionStateChange` publicly constructible. I decided not to, partly because I wasn’t very keen to go through the process of another `ably-java` release, and partly because I’m not convinced that it _should_ be publicly constructible. I’m happy to be challenged on both these points, though.

Furthermore, using a type that can be mocked by MockK gives us extra benefits, like being able to verify which fields of `ConnectionStateChange` are actually being accessed in a given test scenario.

I feel a little bit out of my depth, Java/Kotlin-wise, with the code that manages the mapping of `AblySdkRealtime` listeners to `ably-java` listeners, so would appreciate a close eye on that.

2023-01-12 13:02 UTC, KacperKluka requested changes
A few suggestions from my side, but overall looks good 👍

2023-01-12 13:02 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/DefaultAblySdk.kt
> +            ablyJavaListeners.mapNotNull { it }.forEach { channel.off(it) }
We could refactor this code to be more Kotlin idiomatic but the most important thing that's missing is that we're never removing the listeners from the map. I think that after we unsubscribe a listener (by using `off()`) we should also remove it from the map 🤔 I've attached a suggestion to this comment with the refactoring and listeners removal. Feel free to apply it or create your own implementation 😁 

```suggestion
            val ablyJavaListeners: List<ChannelStateListener> = synchronized(this) {
                listeners.entries
                    .filter { it.value.get() == listener }
                    .mapNotNull { it.key }
                    .onEach { listeners.remove(it) }
            }

            ablyJavaListeners.forEach { channel.off(it) }

```

Changes from the suggestion in detail:
- changed `ablyJavaListeners` list items type to a non-nullable `ChannelStateListener` as map keys aren't nullable
- changed `ablyJavaListeners` to a `val` since the `synchronized` block can return a value
- place list manipulation operations on separate lines where there was more than 1 operation
- move the listener null check to the `synchronized` block where the list is created
- remove listeners that will be unsubscribed within an `onEach` operation in the `synchronized` block

2023-01-13 00:12 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/AblySdk.kt
> +        )
What difficulties were you thinking of? In my usage so far, I've been able to create mocks of this data class using `mockk<AblySdkRealtime.ChannelStateListener.ChannelStateChange>()`, and to use the normal `every` and `verify` methods on this mock’s properties with the desired effects.

2023-01-13 00:15 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private fun convertChannelStateChangeToTracking(channelStateChange: AblySdkRealtime.ChannelStateListener.ChannelStateChange): ConnectionStateChange {
I thought that the decision I'd made here was consistent with what you'd said in https://github.com/ably/ably-asset-tracking-android/pull/868#discussion_r1058889294, about extension functions only being intended for types that we don't control?

> The point of using extension functions is to extend the functionality of objects you can't control. However, right now we have control over the `AblySDKRealtime` interface so instead of using an extension function we can simply add the `closeSuspending()` method to the interface 🤔 But this is not critical, so feel free to do it as a part of this PR or create an issue for changing it later 😉

Since we have control of the newly-created `AblySdkRealtime.ChannelStateListener.ChannelStateChange` type, I didn't think an extension was appropriate?

2023-01-13 00:41 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/DefaultAblySdk.kt
> +            ablyJavaListeners.mapNotNull { it }.forEach { channel.off(it) }
I've actually realised that there's a broader problem with both of these approaches. I think I have a different approach, will comment later.

2023-01-13 02:53 UTC, lawrence-forooghian commented
@KacperKluka I realised that there was a large problem with the approach I'd taken above. We can't use any approach which stores state inside a `DefaultAblySdkRealtime.Channel` object, since these objects are very short-lived; we [re-create them each time a channel is fetched](https://github.com/ably/ably-asset-tracking-android/blob/94f4764ab89fb8383345e39a080379207564e819/common/src/main/java/com/ably/tracking/common/DefaultAblySdk.kt#L69-L95).

I suppose that we could change it so that the channels are not re-created each time, but then we'd have to make sure that we perform other kinds of bookkeeping such as getting rid of the channel when `dispose` is called on the `Channels` instance, which I'd prefer not to do, and leave that to `ably-java`.

So I’ve taken a different approach, which is actually much simpler. We store the `ably-java` listener inside the AAT listener itself. This also means there's no mutable state, and nothing that needs to be synchronised.

The only downside is that the `AblySdk*` interfaces get a bit more complicated - we need to introduce a generic parameter to represent the listener.

2023-01-13 02:54 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/DefaultAblySdk.kt
> +            ablyJavaListeners.mapNotNull { it }.forEach { channel.off(it) }
See https://github.com/ably/ably-asset-tracking-android/pull/894#issuecomment-1381248789 for the problem and the new approach.

2023-01-13 02:55 UTC, lawrence-forooghian commented
(I'd also suggest reviewing the PR commit by commit now, since there are some renamings that will make it hard to review as one diff.)

2023-01-13 15:46 UTC, KacperKluka requested changes
Almost there 👍

2023-01-13 15:46 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +class DefaultAbly<T : AblySdkChannelStateListener>
Perhaps a bit controversial but I usually try to [avoid single-letter generics](https://www.vojtechruzicka.com/break-java-generics-naming-convention/) as they introduce unnecessary cognitive load while analyzing the code 😉 What I do is I take the class that generic should extend and append `Type` to its end (like [here](https://github.com/ably/ably-asset-tracking-android/blob/main/common/src/main/java/com/ably/tracking/common/workerqueue/Worker.kt#L11)) but I wonder if that won't be too verbose and long in this case. Therefore, what would you think about renaming the `T` to `ChannelStateListenerType`? 🤔

2023-01-13 15:46 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/DefaultAblySdk.kt
> +class DefaultAblySdkChannelStateListener(val underlyingListener: AblySdkFactory.UnderlyingChannelStateListener<DefaultAblySdkChannelStateListener>) :
The IDE suggests me that the `underlyingListener` could be a `private val`, so if you don't plan to access it from tests or other places we might as well make it private 😉

2023-01-13 16:06 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/AblySdk.kt
> +        )
Actually, I was wrong, `mockk` technically allows you to mock `data class`es, sorry for that 😅 Still, this is not thought to be a good idea as discussed in a [mockk issue](https://github.com/mockk/mockk/issues/508) (arguments [here](https://github.com/mockk/mockk/issues/508#issuecomment-716763259) and [here](https://github.com/mockk/mockk/issues/508#issuecomment-712435784)) so we probably should either stick to using real instances of this `data class` in our tests or change it to an interface, depending on our use-case 🤔

2023-01-13 16:07 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/DefaultAblySdk.kt
> +            ablyJavaListeners.mapNotNull { it }.forEach { channel.off(it) }
Due to the above changes, this conversation is not valid, therefore, I'll resolve it.

2023-01-13 18:13 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +    private fun convertChannelStateChangeToTracking(channelStateChange: AblySdkRealtime.ChannelStateListener.ChannelStateChange): ConnectionStateChange {
OK, I've kept the previous extension and just changed the type that it's on 🙂

2023-01-13 18:13 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/AblySdk.kt
> +        )
I've changed it to an interface 👍

2023-01-13 18:14 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/Ably.kt
> +class DefaultAbly<T : AblySdkChannelStateListener>
Changed it, although it's longer now it's definitely more readable!

2023-01-13 18:14 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/DefaultAblySdk.kt
> +class DefaultAblySdkChannelStateListener(val underlyingListener: AblySdkFactory.UnderlyingChannelStateListener<DefaultAblySdkChannelStateListener>) :
Good catch! Changed it.

2023-01-14 21:55 UTC, KacperKluka approved these changes
Awesome work! 💪  LGTM, thanks 👍

2023-01-15 00:52 UTC, lawrence-forooghian commented on common/src/main/java/com/ably/tracking/common/DefaultAblySdk.kt
> +class DefaultAblySdkChannelStateListener(val underlyingListener: AblySdkFactory.UnderlyingChannelStateListener<DefaultAblySdkChannelStateListener>) :
Gonna resolve this conversation now you've approved and it's a small thing 🙂

2023-01-15 00:53 UTC, merged