Add methods for detecting retriable and fatal Ably exceptions
ably/ably-asset-tracking-android pull request #929
Opened 2023-01-20 14:53 UTC by KacperKluka

Added helper methods that will enable us to detect fatal and retriable errors. This should allow us to implement appropriate retry mechanisms for certain Ably operations (like presence enter and leave).

Open questions:
- should we only look at the `code` property or maybe also at the `statusCode`?
- how should we classify exceptions that have codes that doesn't start with either `4` or `5`?

2023-01-22 22:00 UTC, paddybyers requested changes
See inline comment

2023-01-22 22:00 UTC, paddybyers commented on common/src/main/java/com/ably/tracking/common/AblyHelpers.kt
> +    val firstErrorCodeDigit = errorInformation.code.toString().first()
This test needs to be on the `statusCode` and not the `code`. There are multiple code ranges that don't start with a 4 or a 5.

Personally I would be happier with a numerical comparison, ie `isRetriable(e) { return e.statusCode >= 500 }`

2023-01-22 23:05 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/AblyHelpers.kt
> +    val firstErrorCodeDigit = errorInformation.code.toString().first()
I used the `code` because as I [mentioned in the issue](https://github.com/ably/ably-asset-tracking-android/issues/927#issuecomment-1398455100) I noticed that the `statusCode` is an optional field. So if it is not set its value will be defaulted to `0`. But I guess we should not worry about it because all important errors will have the `statusCode` correctly set, right? I'll make the changes suggested in your comment 👍

2023-01-22 23:45 UTC, paddybyers commented on common/src/main/java/com/ably/tracking/common/AblyHelpers.kt
> +    val firstErrorCodeDigit = errorInformation.code.toString().first()
According to our spec, errors from REST requests that require a retry [are those with a `statusCode` of 500..504](https://sdk.ably.com/builds/ably/specification/main/features/#RSC15l3)

2023-01-22 23:46 UTC, paddybyers commented on common/src/main/java/com/ably/tracking/common/AblyHelpers.kt
> +    val firstErrorCodeDigit = errorInformation.code.toString().first()
These are all the currently defined error codes from the realtime system: https://github.com/ably/ably-common/blob/main/protocol/errors.json

You can't know whether it's retriable or not from the `code` .

2023-01-22 23:59 UTC, KacperKluka commented on common/src/main/java/com/ably/tracking/common/AblyHelpers.kt
> +    val firstErrorCodeDigit = errorInformation.code.toString().first()
I made the changes https://github.com/ably/ably-asset-tracking-android/pull/929/commits/3bda58378b8ca315839daeb5d4761de54ea85f57:
- using `statusCode` to check if an error is fatal or retriable
- errors with status code in the range 400-499 are considered as fatal
- errors with status code in the range 500-504 are considered as retriable
- all other codes are considered as non-fatal and non-retriable

2023-01-23 08:45 UTC, paddybyers commented
I don't think there's any case that's not a 4xx or a 5xx. I think I'd prefer that there's an error logged in that case - even if `statusCode == 0`.

2023-01-23 08:51 UTC, davyskiba approved these changes

2023-01-23 09:23 UTC, KacperKluka commented
> I don't think there's any case that's not a 4xx or a 5xx. I think I'd prefer that there's an error logged in that case - even if statusCode == 0.

@paddybyers I've created an issue for this (https://github.com/ably/ably-asset-tracking-android/issues/931) as this is a bit tricky to do right and seems a bit out of scope of this PR 😉

2023-01-23 09:50 UTC, paddybyers commented on common/src/main/java/com/ably/tracking/common/AblyHelpers.kt
> +    val firstErrorCodeDigit = errorInformation.code.toString().first()
I don't think there's any case that's not a 4xx or a 5xx. I think I'd prefer that there's an error logged in that case - even if statusCode == 0.

2023-01-23 09:53 UTC, merged